import type { Mensajes } from "./es";

export const en: Mensajes = {
  "tiempo.dias_one": "{n} day",
  "tiempo.dias_other": "{n} days",
  "tiempo.horas_one": "{n} hour",
  "tiempo.horas_other": "{n} hours",
  "tiempo.minutos_one": "{n} minute",
  "tiempo.minutos_other": "{n} minutes",
  "tiempo.menos_de_un_minuto": "less than a minute",
  "ventana.dias_one": "the last day",
  "ventana.dias_other": "the last {n} days",
  "ventana.horas_one": "the last hour",
  "ventana.horas_other": "the last {n} hours",
  "ventana.minutos_one": "the last minute",
  "ventana.minutos_other": "the last {n} minutes",
  "relativo.ahora": "just now",
  "relativo.min": "{n} min ago",
  "relativo.h": "{n} h ago",
  "relativo.d": "{n} d ago",

  "nav.diagnostico": "Diagnosis",
  "nav.trazas": "Traces",
  "nav.panel": "Dashboard",
  "nav.evaluaciones": "Test",
  "nav.prompts": "Prompts",
  "nav.ajustes": "Settings",

  "barra.proyecto": "Project",
  "barra.sin_proyectos": "No projects",
  "barra.rango": "Time range",
  "barra.idioma": "Language",
  "barra.avanzado": "Advanced",
  "barra.avanzado_ayuda": "Shows the technical layer: queries, attributes, identifiers",
  "barra.tu_cuenta": "Your account: {email}",
  "barra.organizacion": "Organization and account",
  "barra.salir": "Sign out",
  "rango.1": "24 hours",
  "rango.7": "7 days",
  "rango.30": "30 days",

  "estado.sin_backend.titulo": "We can't reach the backend",
  "estado.sin_backend.texto":
    "It isn't responding. If you're running locally, start it with {local}; for the full install, with {docker}.",
  "estado.reintentar": "Retry",
  "estado.sin_proyecto.titulo": "No projects yet",
  "estado.sin_proyecto.texto":
    "As soon as your agent sends its first run, it will show up here. Instrumenting it takes one line:",
  "estado.primer_proyecto":
    "On this install the agent needs a key to send traces. {enlace}: the snippet above appears there with the key filled in.",
  "estado.primer_proyecto.enlace": "Create one in Organization",
  "estado.demo.texto":
    "Just want to see it working? Load some sample traces (made-up data, in a separate project called “demo”) and see what it finds.",
  "estado.demo.cargando": "Loading…",
  "estado.demo.boton": "Load sample data",
  "estado.demo.terminal": "From a terminal: {comando}.",
  "estado.demo.error": "couldn't load them",
  "estado.sin_trazas.titulo": "Waiting for the first run of “{proyecto}”",
  "estado.sin_trazas.texto":
    "No traces from this project have arrived yet. As soon as you run your agent with Laplace enabled, it will show up here:",
  "estado.nada.titulo_con_aviso": "We found nothing to fix, but we couldn't look at everything",
  "estado.nada.titulo": "You're not wasting money right now",
  "estado.nada.texto":
    "We looked for repeated calls, steps using a more expensive model than they need, and context resent for no reason. There's none of that in this range.",
  "estado.clave.titulo": "This install requires a key",
  "estado.clave.sin_clave":
    "If you don't have one, whoever administers this organization creates it, in Organization → Keys.",
  "estado.clave.guardar": "Save and sign in",
  "estado.clave.con_cuenta": "Sign in with your account",
  "estado.clave.cookie":
    "It's checked and stored in a cookie only this Laplace can see: neither the page nor any script can read it, and it never goes in the URL, because whatever goes in the URL ends up in the logs of every proxy it passes through.",
  "estado.ajeno.titulo": "Your key doesn't give access to this project",
  "estado.ajeno.texto": "This key is for another project on this install.",
  "estado.ajeno.otra": "Use another key",
  "estado.volver": "Back",
  "diag.titulo": "Your agent “{proyecto}”",
  "diag.al_ritmo": "At the rate of {ventana}",
  "diag.en_datos": "Over {tiempo} of data",
  "diag.costara": "will cost you this month",
  "diag.ha_costado": "has cost you so far",
  "diag.contexto": "Context",
  "diag.cobertura": "Coverage",
  "diag.metricas": "Metrics",
  "diag.m.p95": "p95 latency",
  "diag.m.errores": "Runs with errors",
  "diag.m.tokens": "Tokens",
  "diag.m.trazas": "Traces",
  "diag.m.pasos": "Steps",
  "diag.m.coste": "Cost per run",
  "diag.m.cache": "Already saved by caching",
  "diag.m.datos": "Data observed",
  "diag.nada.aviso": "With that coverage, “nothing to fix” means “we don't know”, not “it's fine”.",
  "diag.nada.gastado": "You've spent {coste} across {ejecuciones} runs.",
  "diag.ver_trazas": "See all traces",
  "diag.cosas_one": "One thing to fix",
  "diag.cosas_other": "{n} things to fix",
  "comun.exportar_csv": "Export CSV",
  "diag.orden": "From the one that saves you the most money to the least.",
  "diag.cifras_proyeccion": "Figures are the 30-day projection of {ventana}.",
  "diag.cifras_gastado": "Figures are money already spent in {ventana}.",
  "diag.nota.proyeccion": "Amounts are an estimate from {ventana} of data, projected to 30 days. If your traffic changes, so do they.",
  "diag.nota.gastado": "Amounts are money {ya} in {ventana}, not a projection: there isn't enough data to estimate the month.",
  "diag.nota.ya_gastado": "already spent",
  "diag.nota.moneda": "Cost is in {moneda} because that's the currency providers bill in.",
  "diag.ver_mas_one": "See one more",
  "diag.ver_mas_other": "See {n} more",
  "diag.tiempo_one": "And one that costs no money, only time",
  "diag.tiempo_other": "And {n} that cost no money, only time",
  "diag.presupuesto": "Budget",
  "diag.presupuesto.invitar": "{enlace} and we'll warn you before you go over.",
  "diag.presupuesto.enlace": "Set a monthly budget",
  "diag.presupuesto.aria": "{n} percent of the budget",
  "estado.arreglado": "Fixed",
  "estado.ignorado": "Ignored",
  "estado.desaparecido": "No longer happens",
  "diag.apartados_one": "One problem that's no longer pending",
  "diag.apartados_other": "{n} problems that are no longer pending",
  "diag.desaparecido": "Hasn't happened since {fecha}. It doesn't count as savings: fixing it wouldn't give you anything back now.",
  "diag.ignorado_coste": "{coste} in the range, not counted as avoidable.",
  "csv.abierto": "open",
  "csv.si": "yes",
  "csv.no": "no",
  "csv.h.problema": "Problem",
  "csv.h.tipo": "Type",
  "csv.h.estado": "Status",
  "csv.h.gastado": "Already spent (USD)",
  "csv.h.al_mes": "Per month (USD)",
  "csv.h.suelo": "Is a floor",
  "csv.h.tokens": "Extra tokens",
  "csv.h.espera": "Avoidable wait (s)",
  "csv.h.ejecuciones": "Affected runs",
  "csv.h.arreglo": "Fix",
  "csv.nombre.problemas": "problems",
  "piezas.gap.aria": "{necesario} necessary cost, {evitable} avoidable",
  "piezas.gap.real": "{coste} of real work",
  "piezas.gap.tirando": "{coste} you're throwing away",
  "piezas.puesto": "Rank {n}",
  "piezas.tokens_de_mas": "extra tokens",
  "piezas.espera": "of avoidable waiting",
  "piezas.al_mes": "a month",
  "piezas.ya_gastado": "already spent",
  "piezas.reaparecido": "You marked it as fixed and it keeps showing up.",
  "piezas.marcado": "Marked as fixed.",
  "piezas.sin_tarifa": "Uses tokens; no price to put a figure on it",
  "piezas.suelo": "It's a floor: the real cost may be higher",
  "piezas.sin_verificar": "With an unverified price",
  "piezas.ver_arreglo": "See how to fix it →",
  "avisos.casi_todo": "Almost everything you spend is flagged below:",
  "avisos.casi_todo.cifras": "{evitable} of {total} ({pct}).",
  "avisos.casi_todo.porque": "Why don't we present it as savings?",
  "avisos.casi_todo.texto": "Because “you can stop paying for your agent” is almost never what it means. Usually there's a small or brand-new agent behind it where two or three steps are practically the whole bill, and fixing them changes those steps, not the whole agent. Look at each problem's breakdown before counting on this figure.",
  "avisos.no_lo_usas": "not used",
  "avisos.pct_aria": "{n} percent",
  "avisos.de_llamadas": "{n} of {total} calls",
  "avisos.incompleto": "This total is incomplete:",
  "avisos.incompleto.linea": "{n} steps without a price ({modelos}).",
  "avisos.incompleto.porque": "Their model isn't in our price table, so we don't know what they cost and they aren't added up. You can set a price in Settings, and what's already stored is recalculated.",
  "avisos.suelo": "It's a floor:",
  "avisos.suelo.linea_one": "on {n} step we charged the standard price.",
  "avisos.suelo.linea_other": "on {n} steps we charged the standard price.",
  "avisos.suelo.porque": "Long context, data residency or fast mode are separate billing tiers that the provider's response doesn't always reveal. The real cost may be somewhat higher, never lower. Each step says what the doubt is, in advanced mode.",
  "avisos.proyeccion": "Projection from {ventana} of data.",
  "avisos.proyeccion.porque": "It's what you've been sending, not the range the selector asks for. Spend and savings come from the same base: if one changes, so does the other.",
  "avisos.sin_proyectar": "Money already spent, not projected.",
  "avisos.sin_proyectar.linea": "The monthly forecast appears with {tiempo} of data.",
  "avisos.sin_proyectar.porque": "With {ventana} of data, multiplying up to 30 days gives a figure that doesn't hold: a ten-minute spike would turn into hundreds of dollars.",
  "avisos.mucho": "The estimated saving is {pct} of what you spend.",
  "avisos.mucho.porque": "That's a lot: it usually happens in small or brand-new agents, where a few steps dominate the bill. Before taking it at face value, look at each problem's breakdown.",
  "avisos.sin_dinero": "We can't calculate the money",
  "prob.no_aparece.titulo": "That problem no longer shows up",
  "prob.no_aparece.texto": "Either you fixed it, or it stopped happening in the range you're looking at. Congratulations either way.",
  "prob.que_pasa": "What's happening",
  "prob.deteccion": "How we detected it",
  "prob.deteccion.nota": "This is the query that actually ran, not a sample version. Rule thresholds are the same for every project: Settings decides what alerts, not what's detected.",
  "prob.traza": "The full trace",
  "prob.traza.texto": "A real run where the problem shows.",
  "prob.traza.abrir": "Open it to walk through it step by step →",
  "prob.atributos": "Attributes of the flagged step",
  "prob.arreglo": "How to fix it",
  "prob.ahorro": "How much you save",
  "prob.ahorro.ya": "In {ventana}, {coste} has already gone this way.",
  "prob.ahorro.mes": "At that rate, fixing it stops costing you {coste}.",
  "prob.ahorro.al_mes": "{coste} a month",
  "prob.ahorro.sin_mes": "We don't project the month yet: with {tiempo} of data, multiplying up to 30 days would give a figure that doesn't hold.",
  "prob.ahorro.suelo": "And it's a {suelo}: some steps here have a cost we can't confirm, so the real figure may be higher, never lower.",
  "prob.ahorro.suelo.palabra": "floor",
  "prob.ahorro.sin_verificar": "We haven't verified the price of {modelos}: it comes from LiteLLM's community table and may not match your bill, either way.",
  "prob.ahorro.tokens": "This uses {tokens} extra and {espera} of waiting in the analyzed range. How much money that is, we don't know: {motivo}.",
  "prob.ahorro.tokens.n": "{n} tokens",
  "prob.ahorro.sin_tarifa": "that model has no known price",
  "prob.ahorro.tiempo": "This problem doesn't cost you money: the repeated steps don't consume tokens. What it costs is waiting, {espera} in the analyzed range. Fixing it makes your agent answer sooner.",
  "prob.calculo": "Calculation:",
  "prob.solo_lectura": "Your role in this project ({rol}) lets you see it, not mark it as fixed or ignore it.",
  "prob.ver_afectadas": "See the affected traces",
  "prob.ver_ultimas": "See this step's latest runs",
  "tec.al_mes": "a month if nothing changes",
  "tec.ya_gastados": "already spent in {ventana}",
  "tec.espera": "of avoidable waiting in {ventana}",
  "tec.afectadas": "affected",
  "tec.vueltas_mas_one": "…{n} more round, all with the same answer.",
  "tec.vueltas_mas_other": "…{n} more rounds, all with the same answer.",
  "tec.identicas_mas_one": "…{n} more identical call, all with the same answer.",
  "tec.identicas_mas_other": "…{n} more identical calls, all with the same answer.",
  "tec.tarifa_aplicada": "applied price",
  "tec.tarifa_no_verificada": "unverified price",
  "tec.tarifa_asumida": "assumed price",
  "seg.error.guardar": "couldn't save",
  "seg.error.deshacer": "couldn't undo",
  "seg.error.crear": "couldn't create",
  "seg.titulo.ignorado": "You marked it as ignored",
  "seg.titulo.reaparecido": "You marked it as fixed, and it keeps showing up",
  "seg.titulo.arreglado": "You marked it as fixed",
  "seg.fecha": "On {fecha}.",
  "seg.antes": "Before, per run",
  "seg.despues": "After",
  "seg.ejecuciones": "{n} runs",
  "seg.ignorado.nota": "It doesn't count toward the avoidable total on the home page or send alerts.",
  "seg.deshacer": "Undo and put it back on the list",
  "seg.ya_arreglado": "Have you fixed it already?",
  "seg.ya_arreglado.texto": "Mark it and we'll check: we compare what each run cost before with what it costs after. If it keeps showing up the same, it goes back on the list.",
  "seg.nota.placeholder": "Why it isn't a problem (optional)",
  "seg.ignorar": "Ignore this problem",
  "comun.cancelar": "Cancel",
  "seg.arreglado.boton": "I've fixed it: check it",
  "seg.no_problema": "It's not a problem for me",
  "seg.probar.titulo": "Before switching, test it",
  "seg.probar.texto": "The saving is measured; whether {modelo} answers just as well isn't. Save this step's real runs and resend their calls to {modelo} with the command below: it runs on your machine, with your key and a spending cap, and the judge compares each answer with the original. Test will tell you whether it's just as accurate and how much less it costs.",
  "seg.probar.barato": "the cheap model",
  "seg.probar.ir": "Go to Test →",
  "seg.probar.crear": "Create the “{nombre}” set with these runs",
  "seg.tokens": "{n} tokens",
  "trazas.orden.coste": "Most expensive first",
  "trazas.orden.reciente": "Most recent",
  "trazas.orden.duracion": "Slowest",
  "trazas.tipo.cualquiera": "Any step",
  "trazas.tipo.llm": "With a model call",
  "trazas.tipo.tool": "With a tool",
  "trazas.tipo.retrieval": "With retrieval",
  "trazas.titulo": "Traces",
  "trazas.lead": "Each row is a complete run of your agent. Sorted by what they cost.",
  "trazas.buscar.contenido": "Search for an order, a phrase, an id…",
  "trazas.buscar.nombres": "Search by step, tool or trace id",
  "trazas.buscar": "Search",
  "trazas.donde": "Where to search",
  "trazas.en_nombres": "In names and ids",
  "trazas.en_contenido": "In prompts and answers",
  "trazas.estado": "Status",
  "trazas.estado.cualquiera": "Any status",
  "trazas.estado.error": "Errors only",
  "trazas.estado.ok": "Successful only",
  "trazas.tipo": "Step type",
  "trazas.orden": "Order",
  "trazas.modelo": "Model",
  "trazas.modelo.cualquiera": "Any model",
  "trazas.coste_minimo": "Minimum cost",
  "trazas.coste_minimo.aria": "Minimum cost in USD",
  "trazas.sesion.aria": "Session identifier",
  "trazas.filtrar": "Filter",
  "trazas.corta": "To search prompts and answers, type at least {n} characters.",
  "trazas.filtro.paso": "Only runs that go through the problem's step: {paso}",
  "trazas.filtro.usuario": "Only runs by user {usuario}",
  "trazas.quitar": "Remove",
  "trazas.ninguna": "No traces match",
  "trazas.ninguna.texto": "Try removing filters or widening the time range in the bar above.",
  "trazas.quitar_filtros": "Clear filters",
  "csv.h.traza": "Trace",
  "csv.h.agente": "Agent",
  "csv.h.inicio": "Start",
  "csv.h.sesion": "Session",
  "csv.h.usuario": "User",
  "csv.h.pasos": "Steps",
  "csv.h.tok_entrada": "Input tokens",
  "csv.h.tok_salida": "Output tokens",
  "csv.h.coste": "Cost (USD)",
  "csv.h.incompleto": "Incomplete cost",
  "csv.h.duracion": "Duration (ms)",
  "csv.h.modelos": "Models",
  "csv.nombre.trazas": "traces",
  "lista.n_trazas": "{n} traces",
  "lista.en_pausa": " · paused",
  "lista.cada": "Checked every {n} seconds",
  "lista.vivo.necesita": "Live mode needs most-recent order: clicking switches to it",
  "lista.vivo.pausar": "Live · pause",
  "lista.vivo.ver": "Watch live",
  "lista.col.traza": "Trace",
  "lista.col.modelos": "Models",
  "lista.col.pasos": "Steps",
  "lista.col.tokens": "Tokens",
  "lista.col.entrada": "Input",
  "lista.col.salida": "Output",
  "lista.col.coste": "Cost",
  "lista.col.duracion": "Duration",
  "lista.col.cuando": "When",
  "lista.col.bien": "OK?",
  "lista.todas": " (all in the range)",
  "lista.antiguas": "Older →",
  "lista.sin_backend": "The backend isn't responding; still trying.",
  "lista.nuevas_one": "{n} new trace since you turned it on.",
  "lista.nuevas_other": "{n} new traces since you turned it on.",
  "lista.esperando": "Waiting for new traces.",
  "lista.ultima": "Last check: {fecha}.",
  "lista.con_error": "with error",
  "lista.sin_nombre": "(unnamed)",
  "lista.bucle.ayuda": "Repeats steps with the same input",
  "lista.bucle": "loop",
  "lista.errores_one": "{n} error",
  "lista.errores_other": "{n} errors",
  "lista.sesion": " · session {id}",
  "lista.coste_incompleto": "incomplete cost",
  "conj.creado": "Set “{nombre}” created with this filter.",
  "conj.ir": "Go to Test",
  "conj.guardar": "Save these traces as a case set",
  "conj.nombre.placeholder": "Name, e.g. checkout-regressions",
  "conj.nombre.aria": "Set name",
  "conj.creando": "Creating…",
  "conj.boton": "Save (up to 50)",
  "traza.no_encontrada": "We can't find that trace",
  "traza.no_encontrada.texto": "The identifier may be wrong, or the trace may be older than what's kept.",
  "traza.todas": "All traces",
  "traza.problemas_one": "One detected problem happens in this run:",
  "traza.problemas_other": "{n} detected problems happen in this run:",
  "traza.estado.ignorado": "ignored",
  "traza.estado.reaparecido": "marked as fixed, but still happening",
  "traza.estado.arreglado": "marked as fixed",
  "traza.bien": "Is this run correct?",
  "traza.juez.sin_tarifa": "Judged with {modelo}. We don't know its cost: that model isn't in the price table.",
  "traza.juez.coste": "Judged with {modelo}. It cost {coste}.",
  "traza.juez.error": "the judge couldn't give an opinion",
  "traza.juez.juzgando": "Judging…",
  "traza.juez.opine": "Ask {modelo}",
  "traza.juez.ocultar": "Hide the judge's prompt",
  "traza.juez.ver": "See the judge's prompt",
  "traza.exportar": "Export trace as JSON",
  "traza.usuario": " · user {id}",
  "traza.coste.faltan": "cost ({n} steps without a price missing)",
  "traza.coste.sin_verificar": "cost (unverified price)",
  "traza.coste": "cost",
  "traza.tokens": "input / output tokens",
  "traza.duracion": "duration",
  "traza.pasos": "steps",
  "traza.llamadas": "model calls",
  "traza.herramientas": "tools",
  "traza.modelos": "models",
  "traza.cache_tokens": "tokens served from cache",
  "traza.cache_ahorro": "saved by caching",
  "traza.asumida": "steps with an assumed price",
  "traza.errores": "errors",
  "arbol.titulo": "Execution tree",
  "arbol.n_de": "{n} of {total} steps",
  "arbol.teclas": "↑↓ move · ←→ collapse",
  "arbol.plegar_todo": "Collapse all",
  "arbol.desplegar_todo": "Expand all",
  "arbol.desplegar": "expand",
  "arbol.plegar": "collapse",
  "arbol.misma_llamada": "Same call with the same input",
  "arbol.selecciona": "Select a step in the tree.",
  "arbol.prompt": "Prompt ({n})",
  "arbol.respuesta": "Response ({n})",
  "arbol.argumentos": "Arguments",
  "arbol.salida": "Output",
  "arbol.consulta": "Query",
  "arbol.documentos": "Documents ({n})",
  "arbol.entrada": "Input",
  "arbol.eventos": "Events ({n})",
  "arbol.evento": "event",
  "arbol.modelo": "model",
  "arbol.tok_entrada": "input tokens",
  "arbol.tok_entrada_est": "input tokens (estimated)",
  "arbol.tok_salida": "output tokens",
  "arbol.tok_salida_est": "output tokens (estimated)",
  "arbol.sin_precio": "price unknown",
  "arbol.coste_minimo": "minimum cost (assumed price)",
  "arbol.desde_cache": "from cache ({coste})",
  "arbol.escritos_cache": "written to cache ({coste})",
  "arbol.ahorro_cache": "saved by caching",
  "arbol.rama.pasos": "steps in the branch",
  "arbol.rama.error": "with errors",
  "arbol.rama.tokens": "tokens in the branch",
  "arbol.rama.coste": "cost of the branch",
  "arbol.mensaje": "message",
  "arbol.contenido": "content",
  "arbol.raiz": "(root)",
  "arbol.estimados": "true (we counted them)",
  "arbol.del_proveedor": "false (from the provider)",
  "arbol.ninguna": "none: unknown model",
  "arbol.atributos": "Raw attributes",
  "arbol.sin_contenido": "No content.",
  "arbol.copiado": "copied",
  "arbol.copiar": "copy",
  "arbol.misma_entrada": "Same call, same input",
  "ver.buena": "Mark this run as good",
  "ver.mala": "Mark this run as bad",
  "ver.solo_ver": "Your role only allows viewing",
  "ver.bien": "Good",
  "ver.mal": "Bad",
  "ver.ocultar": "Hide comment",
  "ver.ver": "See comment",
  "ver.comentar": "Comment",
  "ver.placeholder": "What failed, or why it's fine. Saved when you mark it.",
  "ver.nota": "The comment is saved with the verdict: press “{bien}” or “{mal}” again after writing it.",
  "ver.juez": "judge",
  "ver.no_guardado": "not saved",
  "ver.maquina": "machine verdict",
  "ver.juez_dice": "judge: {v}",
  "ver.bien_min": "good",
  "ver.mal_min": "bad",
  "ver.coste_desconocido": " unknown cost",
  "ver.persona": "person: {v}",
  "panel.titulo": "Your agent “{proyecto}”, per unit of work",
  "panel.por_ejecucion": "Per run",
  "panel.por_ejecucion.lead": "What one run of your agent costs. It's the figure that matters: spend rising because there's more work isn't a problem, and this separates the two.",
  "panel.totales": "Totals, for context",
  "panel.totales.lead": "They're down here on purpose: on their own they don't say whether something is wrong.",
  "panel.error.cargar": "couldn't load",
  "panel.quien": "Who spends the most",
  "panel.agrupar": "Group by",
  "panel.usuarios": "Users",
  "panel.sesiones": "Sessions",
  "panel.sin_usuario": "No run in this range says which user it belongs to. With {codigo} in your agent, you'll see here where the spend goes.",
  "panel.sin_sesion": "No run in this range says which session it belongs to. With {codigo} in your agent, you'll see here where the spend goes.",
  "panel.col.usuario": "User",
  "panel.col.sesion": "Session",
  "panel.col.ejecuciones": "Runs",
  "panel.col.por_ejecucion": "Per run",
  "panel.col.total": "Total",
  "panel.col.del_gasto": "Of spend",
  "panel.sin_etiqueta_usuario": "Also, {n} runs without a user ({coste}).",
  "panel.sin_etiqueta_sesion": "Also, {n} runs without a session ({coste}).",
  "panel.menos_de": "< {x}",
  "panel.sin_comparacion": "no comparison",
  "panel.vs_anterior": "{cambio} vs. the previous period",
  "panel.grafica.titulo": "Cost per run, in intervals of {tramo}",
  "panel.grafica.coste": "cost per run",
  "panel.grafica.ejecuciones": "runs",
  "panel.grafica.aria": "Cost per run per interval",
  "panel.grafica.punto": "{fecha} · {coste} per run · {n} runs",
  "panel.grafica.desde": " · from the first data point",
  "panel.grafica.nota": "Intervals without runs stay blank. That's not zero cost: there was nothing to run, and drawing it as zero would show a drop that never happened.",
  "panel.picos": "Spikes",
  "panel.picos.ninguno": "No interval is out of the ordinary in this range. The cost per run stays within what it usually costs.",
  "panel.picos.n_one": "One interval is out of the ordinary",
  "panel.picos.n_other": "{n} intervals are out of the ordinary",
  "panel.picos.lead": "Intervals where each run cost much more than usual. Most expensive first.",
  "panel.pico.cuando": "Started on {inicio} and lasted until {fin}",
  "panel.pico.de_mas": "extra",
  "panel.pico.texto_one": "In that interval each run cost {coste}, compared with the usual {base}: {veces} across {n} run.",
  "panel.pico.texto_other": "In that interval each run cost {coste}, compared with the usual {base}: {veces} across {n} runs.",
  "panel.pico.veces": "{n} times more",
  "panel.pico.ver_prompt": "see that prompt",
  "panel.pico.ver_trazas": "See that interval's traces",
  "panel.pico.orden": "Sorted by cost, most expensive first",
  "panel.pico.tramo": "interval",
  "panel.pico.base": "baseline",
  "panel.pico.mediana": "median of the intervals with runs",
  "ev.titulo": "Test the fixes for “{proyecto}” before you deploy them",
  "ev.lead": "This is the second step of the cycle: Diagnosis tells you what a fix gives back; here you check, on that step's real calls, that the agent is just as accurate with the fix in place.",
  "ev.conj.titulo": "Case sets",
  "ev.conj.lead": "Collections of {reales} runs of your agent. There are no made-up cases here: each comes from a trace that happened, and you can open it to see where it came from.",
  "ev.conj.reales": "real",
  "ev.conj.nombre": "Name",
  "ev.conj.cuantas": "How many traces",
  "ev.conj.crear": "Create from the most recent",
  "ev.conj.otro_filtro": "Want another filter? Filter in {explorador} and click “{guardar}”: the set keeps the filter it was built with, so its origin can be discussed later.",
  "ev.explorador": "the explorer",
  "ev.conj.ninguno": "There aren't any yet.",
  "ev.conj.col.conjunto": "Set",
  "ev.conj.col.casos": "Cases",
  "ev.conj.col.filtro": "Source filter",
  "ev.conj.col.creado": "Created",
  "ev.conj.sin_filtro": "no filter (most recent)",
  "ev.borrar": "Delete",
  "ev.tiradas": "Runs",
  "ev.tiradas.lead": "Each one is a pass of a set through a version of your agent. The SDK launches them in your process; only the report and the traces arrive here.",
  "ev.col.version": "Version",
  "ev.col.conjunto": "Set",
  "ev.col.casos": "Cases",
  "ev.col.personas": "People",
  "ev.col.juez": "Judge",
  "ev.col.coste": "Cost",
  "ev.col.juzgar": "Judging cost",
  "ev.col.cuando": "When",
  "ev.sin_tiradas": "No runs of a new version? Launch one with {codigo} pointing at this same Laplace. The traces it generates show up in {explorador} like any other, and the project is “{proyecto}”.",
  "ev.entre": "between {bajo} and {alto}",
  "ev.error.comparar": "couldn't compare",
  "ev.paso1": "Save a case set",
  "ev.paso1.texto": "Real runs of your agent. From {explorador}, filter and click “{guardar}”, or create it below from the most recent.",
  "ev.paso2": "Run it with the current version",
  "ev.paso2.texto": "The SDK launches the run in your process (Laplace doesn't run your agent):",
  "ev.paso3": "And again with the new version",
  "ev.paso3.texto": "Another prompt, another model: the same line with a different {variant}. With both runs, the accuracy and cost comparison appears here. Accuracy comes from your annotations or from the automatic judge.",
  "ev.comparar.titulo": "Compare two versions",
  "ev.comparar.pasos": "Three steps, and each one ticks itself off when done.",
  "ev.comparar.lead": "Accuracy and cost together. Both runs must be from the same set: comparing accuracy over different cases would say nothing.",
  "ev.a": "A — the baseline",
  "ev.b": "B — the new one",
  "ev.elige": "Choose a run",
  "ev.elige_a": "Choose A first",
  "ev.n_casos": "{n} cases",
  "ev.comparando": "Comparing…",
  "ev.comparar": "Compare",
  "ev.discrepan": "People and the judge disagree.",
  "ev.discrepan.texto": "It isn't a product bug: it's the most interesting fact this screen can give you. Either the judge is measuring something else, or whoever annotated and whoever wrote the judge's prompt don't mean the same thing by “good”. Look at the cases before trusting either.",
  "ev.costo": "What each one cost",
  "ev.costo.lead": "This has no margin: it isn't a sample, it's the bill for what ran. If you manage your prompts in Laplace, under each side you'll see {enlace}, read from the traces and not from the label you gave the run.",
  "ev.costo.enlace": "which version it ran with",
  "ev.juzgar_dos": "Judge both runs with {modelo}",
  "ev.cuesta": "It costs money: you'll be told how much as soon as it's done",
  "ev.tec.conjunto": "set",
  "ev.tec.casos": "cases",
  "ev.fuente.personas": "People",
  "ev.fuente.juez": "Judge (model)",
  "ev.de": "{a} of {b}",
  "ev.sin_anotar": " · {n} not annotated",
  "ev.wilson": "between {bajo} and {alto} (Wilson, 95%)",
  "ev.por_caso": "per case",
  "ev.tec.total": "total",
  "ev.tec.tokens": "tokens",
  "ev.tec.duracion": "duration",
  "ev.tec.reventados": "crashed",
  "ev.juez_costo": "Judging this run cost {coste} separately{desconocido}. It's our spend, not your agent's, which is why it's kept apart.",
  "ev.juez_desconocido": " (and some verdicts have an unknown cost)",
  "pr.titulo": "The prompts of “{proyecto}”",
  "pr.lead": "Each version with what it cost and how accurate it was on the real traffic that used it, so you can decide which one to keep in production with both figures in front of you.",
  "pr.error.abrir": "couldn't open",
  "pr.error.version": "couldn't change the version",
  "pr.en_produccion": "v{n} in production",
  "pr.cerrar": "Close",
  "pr.ver_versiones": "See versions and diff",
  "pr.reserva_one": "{n} run used the fallback text.",
  "pr.reserva_other": "{n} runs used the fallback text.",
  "pr.reserva.texto": "It means your agent couldn't fetch the prompt from Laplace and used the one in its code. That traffic is counted separately, not in the production version: adding it there would skew exactly the figure you're looking at.",
  "pr.acierto.nota": "A version's accuracy is that of the {enteras} it took part in, not of this prompt on its own. A run goes through several steps and, when it goes wrong, nobody has measured which one broke it. It's a useful signal, not an allocation of blame.",
  "pr.acierto.enteras": "whole runs",
  "pr.tec.versiones": "versions",
  "pr.tec.creado": "created",
  "pr.col.version": "Version",
  "pr.col.por_ejecucion": "Per run",
  "pr.col.ejecuciones": "Runs",
  "pr.col.tokens": "Tokens/run",
  "pr.col.ultimo": "Last used",
  "pr.produccion": "production",
  "pr.poner": "Put in production",
  "pr.ocultar_mudas": "Hide versions without traffic",
  "pr.ver_mudas_one": "See {n} version that didn't run in this range",
  "pr.ver_mudas_other": "See {n} versions that didn't run in this range",
  "pr.wilson": "{bajo}–{alto} (Wilson)",
  "pr.nuevo": "Move a prompt out of the code",
  "pr.nuevo.lead": "The name is what you'll fetch it with: {codigo}. The first version goes into production on its own; from the second on, saving and deploying are two separate actions.",
  "pr.nombre": "Name",
  "pr.nuevo.placeholder": "You are an assistant that answers in {{idioma}} and in fewer than three sentences.",
  "pr.crear": "Create and put in production",
  "pr.que_cambio": "What changed",
  "pr.de": "From",
  "pr.a": "To",
  "pr.elige_dos": "Choose two different versions to see the diff. With only one there's nothing to compare.",
  "pr.texto_v": "The text of v{n}",
  "pr.guardar_nueva": "Save a new version",
  "pr.guardar_nueva.lead": "Saving doesn't deploy. They're two separate actions on purpose: that's what lets you prepare a version calmly, and what makes the roll-back button possible.",
  "pr.texto.placeholder": "The prompt text. Use {{variable}} for whatever changes on each call.",
  "pr.guardando": "Saving…",
  "pr.guardar": "Save version",
  "pr.guardada": "It's saved, not served",
  "pr.historial": "Deployment history",
  "pr.col.cuando": "When",
  "pr.col.quien": "Who",
  "pr.col.nota": "Note",
  "pr.vuelta_atras": "rollback",
  "pr.historial.nota": "This history tells the story; it does {no} attribute spikes. For that, the {panel} uses the version that appears in the interval's traces, which is a measured fact and not a coincidence of timing.",
  "pr.no": "not",
  "pr.panel": "dashboard",
  "pr.borrar": "Delete this prompt",
  "pr.borrar.nota": "Traces are left untouched: they'll keep saying which version they ran with",
  "pr.sin_adoptar": "You don't manage any prompts here yet",
  "pr.sin_adoptar.1": "Your prompts live in your code, which is a perfectly reasonable place. What you lose is being able to answer “how much did the previous one cost and how accurate was it?”, because a {blame} knows what changed but not what happened afterwards.",
  "pr.sin_adoptar.2": "If you move them here, the SDK serves them and records in each trace which version ran. {nada}: it only gives you the text, and if Laplace doesn't respond, the SDK uses the saved copy or the fallback text you pass it.",
  "pr.sin_adoptar.nada": "Laplace still runs nothing of yours",
  "pr.sin_adoptar.3": "Meanwhile, below is what can be learned from your traces: which steps have changed instructions and when.",
  "pr.obs.titulo": "What shows in your traces",
  "pr.obs.nada": "Nothing yet.",
  "pr.obs.gestion": "This comes from the traces, not from prompt management: it's the sets of instructions each step has been seen running with. It helps you spot anything that changed outside of here.",
  "pr.obs.sin_gestion": "Each step of your agent, and the sets of instructions it has been seen running with in this range. If a step's instructions change between runs, that's a prompt change: we don't know the whole text (we only keep the beginning), but we do know when it changed and what it cost.",
  "pr.obs.cambio": "See a change you don't recognize? {enlace} and look at the full instructions of those runs.",
  "pr.obs.abrir": "Open it in the explorer",
  "pr.obs.no_versiones": "not versions",
  "pr.obs.llamadas": "calls in each run",
  "pr.obs.juego_one": "set of instructions",
  "pr.obs.juego_other": "sets of instructions",
  "pr.obs.col.instrucciones": "Instructions (beginning)",
  "pr.obs.col.desde": "From",
  "pr.obs.col.hasta": "Until",
  "pr.obs.sin_instrucciones": "(no instructions captured)",
  "comun.guardar": "Save",
  "comun.quitar": "Remove",
  "aj.titulo": "Settings for “{proyecto}”",
  "aj.lead": "Budget, alerts, prices and data. Each block saves on its own.",
  "aj.solo_lectura": "The budget, alerts and deleting the project are changed by an organization admin. Your role ({rol}) lets you see them.",
  "aj.pres.guardado": "Budget saved.",
  "aj.pres.quitado": "Budget removed.",
  "aj.pres.titulo": "Monthly budget",
  "aj.pres.lead": "Over the calendar month, which is what the provider bills. It alerts at 80% and 100% through the channels below, once each per month.",
  "aj.pres.dolares": "Dollars per month",
  "aj.error.borrar": "couldn't delete",
  "aj.datos": "Data",
  "aj.datos.retencion": "This install keeps traces for {n} days; anything older is deleted automatically every day.",
  "aj.datos.siempre": "This install keeps traces forever. To delete old data automatically, start it with LAPLACE_RETENTION_DAYS.",
  "aj.borrar.titulo": "Delete “{proyecto}” entirely.",
  "aj.borrar.texto": "Traces, annotations, case sets, prompts, budget and alerts. It can't be undone. Type the project name to confirm.",
  "aj.borrar.aria": "Project name to confirm",
  "aj.borrar.boton": "Delete the project",
  "aj.apariencia": "Appearance",
  "aj.en_navegador": "Saved in this browser.",
  "aj.tema": "Theme",
  "aj.tema.sistema": "Same as system",
  "aj.tema.claro": "Light",
  "aj.tema.oscuro": "Dark",
  "aj.euros": "Also show in euros",
  "aj.euros.lead": "Providers bill in dollars and that remains the figure. If you set an exchange rate, the euro equivalent appears next to the main amounts with “≈”. You set the rate and it's stored only in this browser: we don't download it from anywhere.",
  "aj.euros.tipo": "1 $ is … €",
  "aj.euros.guardado": "Rate saved.",
  "aj.euros.desactivados": "Euros turned off.",
  "aj.tar.guardada": "Price for {modelo} saved. {n} calls already stored now have their cost.",
  "aj.tar.quitada": "Price for {modelo} removed.",
  "aj.error.quitar": "couldn't remove",
  "aj.tar.titulo": "Custom prices",
  "aj.tar.lead": "For a model that isn't in our table, or one with a negotiated price. In dollars per million tokens, from the provider's page. Saving it also recalculates what you'd already sent. If the model runs on your machine, don't give it a price: nobody charges you.",
  "aj.tar.instalacion": "Prices apply to the whole install: only an install key can change them.",
  "aj.tar.sin_tarifa": "No price right now:",
  "aj.tar.modelo": "Model",
  "aj.tar.entrada": "Input",
  "aj.tar.salida": "Output",
  "aj.tar.entrada_m": "Input ($/M)",
  "aj.tar.salida_m": "Output ($/M)",
  "aj.tar.guardar": "Save price",
  "aj.al.prueba_ok": "Test message sent. Check the channel.",
  "aj.al.prueba_mal": "It didn't arrive through any channel. Check the addresses.",
  "aj.al.error.probar": "couldn't test",
  "aj.al.titulo": "Alerts",
  "aj.al.lead": "A message when a problem goes over the threshold in money already spent. The same alert is never repeated within the quiet period, and whatever you mark as fixed or ignored doesn't alert.",
  "aj.al.silenciadas": "Muted for this project.",
  "aj.al.activas": "On.",
  "aj.al.apagadas": "Off: add at least one channel.",
  "aj.al.slack_guardado": "Slack webhook saved.",
  "aj.al.slack_quitado": "Slack removed.",
  "aj.al.webhook_titulo": "Webhook (Teams, Discord, n8n…)",
  "aj.al.webhook_guardado": "Webhook saved.",
  "aj.al.webhook_quitado": "Webhook removed.",
  "aj.al.correo": "Email",
  "aj.al.correo_placeholder": "team@company.com",
  "aj.al.correo_guardado": "Email saved.",
  "aj.al.correo_quitado": "Email removed.",
  "aj.al.smtp": "The install's mail server is missing: start Laplace with LAPLACE_SMTP_HOST, LAPLACE_SMTP_USER and LAPLACE_SMTP_PASSWORD.",
  "aj.al.umbral": "Threshold (dollars already spent)",
  "aj.al.calma": "Quiet period per problem (hours)",
  "aj.al.umbral_guardado": "Threshold and quiet period saved.",
  "aj.al.que_avisa": "What alerts",
  "aj.al.reglas_guardadas": "Rules saved.",
  "aj.al.probar": "Send a test message",
  "aj.al.reactivadas": "Alerts turned back on.",
  "aj.al.silenciadas_ok": "Alerts muted.",
  "aj.al.reactivar": "Turn back on",
  "aj.al.silenciar": "Mute this project",
  "aj.al.puesto": " · set ({actual})",
  "aj.al.otro": "Paste another to change it",
  "aj.regla.repeticion": "Repetitions",
  "aj.regla.bucle": "Loops",
  "aj.regla.modelo_caro": "Expensive model",
  "aj.regla.contexto_fijo": "Uncached context",
  "titulo.ajustes": "Settings",
  "titulo.configurar": "Setup",
  "titulo.entrar": "Sign in",
  "titulo.evaluaciones": "Test",
  "titulo.invitacion": "Invitation",
  "titulo.organizacion": "Organization",
  "titulo.panel": "Dashboard",
  "titulo.problema": "Problem",
  "titulo.prompts": "Prompts",
  "titulo.traza": "Trace",
  "titulo.trazas": "Traces",
  "rol.lector": "viewer",
  "rol.miembro": "member",
  "rol.admin": "admin",
  "rol.propietario": "owner",
  "org.error.cargar": "couldn't load",
  "org.local.titulo": "Local mode has no accounts",
  "org.local.texto": "It's a process on your machine with your traces: there's nobody else to give access to. Accounts, roles and keys exist in the cloud install.",
  "org.tu_cuenta": "Your account",
  "org.eres": "You are {rol} of this organization.",
  "org.sin_org": "You don't belong to any organization yet: ask for an invitation.",
  "org.org": "Organization",
  "org.miembros": "Members",
  "org.col.persona": "Person",
  "org.col.rol": "Role",
  "org.col.desde": "Since",
  "org.tu": " · you",
  "org.rol_de": "Role of {email}",
  "org.ahora_es": "{email} is now {rol}.",
  "org.salir_confirm": "Leave the organization?",
  "org.quitar_confirm": "Remove {email}?",
  "org.hecho": "Done.",
  "org.salir": "Leave",
  "org.roles.nota": "Viewer: sees. Member: also annotates runs, marks problems and manages prompts and sets. Admin: also members, keys, alerts, budget and deleting. Removing someone ends their sessions immediately.",
  "org.invitar": "Invite",
  "org.email": "Email",
  "org.email_placeholder": "person@company.com",
  "org.enviado": "We've emailed them the link. You can also copy it:",
  "org.sin_correo": "This install has no email configured: send them this link yourself. It's only shown now, and it expires in 7 days.",
  "org.pendientes": "Pending",
  "org.caduca": "expires on {fecha}",
  "org.anulada": "Invitation cancelled.",
  "org.anular": "Cancel",
  "org.acc.configurar_instalacion": "set up the install",
  "org.acc.login": "signed in",
  "org.acc.login_fallido": "failed sign-in attempt",
  "org.acc.invitar": "invited",
  "org.acc.anular_invitacion": "cancelled the invitation of",
  "org.acc.aceptar_invitacion": "accepted the invitation as",
  "org.acc.cambiar_rol": "changed the role of",
  "org.acc.quitar_miembro": "removed",
  "org.acc.crear_clave": "created a key for",
  "org.acc.revocar_clave": "revoked the key",
  "org.acc.borrar_proyecto": "deleted the project",
  "org.registro": "Activity log",
  "org.cargando": "Loading…",
  "org.nada": "Nothing yet.",
  "org.alguien": "someone",
  "org.admin_instalacion": " · you administer this install",
  "org.pass_actual": "Current password",
  "org.pass_nueva": "New (10 characters or more)",
  "org.pass_cambiada": "Password changed. Other sessions have been signed out.",
  "org.pass_cambiar": "Change password",
  "org.cerrar_todo": "Sign out on all devices",
  "org.error.generico": "it couldn't be done",
  "cla.titulo": "API keys",
  "cla.lead": "One key per project: it's what your agent sends traces with. Type a new project name to create it.",
  "cla.proyecto": "Project",
  "cla.para_que": "What it's for",
  "cla.para_que_placeholder": "production ingest",
  "cla.caduca": "Expires",
  "cla.nunca": "never",
  "cla.30": "in 30 days",
  "cla.90": "in 90 days",
  "cla.365": "in a year",
  "cla.crear": "Create key",
  "cla.copiala": "Copy it now:",
  "cla.copiala.texto": "only its fingerprint is stored and it can't be shown again. If you lose it, revoke it and create another.",
  "cla.col.nombre": "Name",
  "cla.col.ultimo": "Last used",
  "cla.no_caduca": "doesn't expire",
  "cla.revocar_confirm": "Revoke “{nombre}”? It stops working immediately.",
  "cla.revocada": "Key revoked.",
  "cla.revocar": "Revoke",
  "cla.rotar": "To rotate a key: create the new one, switch it in your agent and revoke the old one.",
  "cla.copiado": "Copied",
  "cla.copiar": "Copy",
  "ent.error": "couldn't sign in",
  "ent.titulo": "Sign in to Laplace",
  "ent.contrasena": "Password",
  "ent.entrando": "Signing in…",
  "ent.entrar": "Sign in",
  "ent.sin_cuenta": "No account? Ask whoever administers your organization for an invitation.",
  "ent.tengo_clave": "I have an API key",
  "ent.comprobando": "Checking…",
  "ent.usar_clave": "Use the key",
  "conf.error": "couldn't set up",
  "conf.titulo": "Set up this install",
  "conf.texto": "There are no accounts yet. The first one administers the whole install and takes over the projects that already have data.",
  "conf.codigo": "Setup code",
  "conf.codigo.ayuda": "It's in the server log, on the line “no hay ninguna cuenta todavía”. With Docker: {comando}",
  "conf.org": "Your organization's name",
  "conf.org_placeholder": "My company",
  "conf.nombre": "Your name",
  "conf.contrasena": "Password (10 characters or more)",
  "conf.creando": "Creating…",
  "conf.crear": "Create the admin account",
  "inv.puede.lector": "see its projects' data",
  "inv.puede.miembro": "see, annotate runs, mark problems and manage prompts",
  "inv.puede.admin": "all of the above, plus members, keys, alerts and budget",
  "inv.puede.propietario": "everything, including making and removing owners",
  "inv.no_vale": "that invitation isn't valid",
  "inv.error": "couldn't accept",
  "inv.no_vale.titulo": "This invitation isn't valid",
  "inv.no_vale.texto": "{motivo}. Invitations expire after seven days and can only be used once: ask whoever invited you for another.",
  "inv.unete": "Join “{org}”",
  "inv.como": "As {rol}: you'll be able to {puede}.",
  "inv.con_cuenta": "You already have an account with this email: your password",
  "inv.elige": "Choose a password (10 characters or more)",
  "inv.uniendote": "Joining…",
  "inv.aceptar": "Accept the invitation",
  "nf.titulo": "This page doesn't exist",
  "nf.texto": "The link may be wrong, or point to something that's no longer there.",
  "nf.ir": "Go to the diagnosis",
  "err.titulo": "Something went wrong loading this screen",
  "err.texto": "We couldn't prepare the data. It's usually momentary: try again and, if it persists, check that the backend is up.",
  "prob.paso_titulo": "{titulo}.",
  // Errores de la API que no traen una frase propia.
  "api.fallo": "Error {estado} on {ruta}",
  "api.no_valida": "The request isn't valid: {campos}",
  // A1: un rango vacío no es un proyecto vacío.
  "estado.rango_vacio.titulo": "No runs in {ventana}",
  "estado.rango_vacio.ultima": "The last one arrived on {fecha}.",
  "estado.rango_vacio.fuera": "The last one arrived on {fecha}, before the {rango} you can look at here. Run your agent with Laplace enabled to see new data.",
  "estado.rango_vacio.boton": "Show {ventana}",
  // Menos texto (D-151): el héroe, el distintivo de confianza y la ficha.
  "diag.puedes.proy": "You can stop paying up to",
  "diag.puedes.al_mes": "a month",
  "diag.puedes.gastado": "You could have saved up to",
  "diag.puedes.en": "in {tiempo}",
  "diag.de_total.proy": "of the {total} it will cost you this month, at the pace of {ventana}.",
  "diag.de_total.gastado": "of the {total} spent over {tiempo} of data.",
  "conf.alta": "High confidence",
  "conf.media": "Medium confidence",
  "conf.baja": "Low confidence",
  "conf.notas_one": "{n} note",
  "conf.notas_other": "{n} notes",
  "conf.alta.texto": "All spend has a known rate and the avoidable share isn't out of proportion.",
  "conf.media.texto": "The figure is reliable, but read it with these notes.",
  "conf.baja.texto": "Some spend is missing or we can't see this agent well: don't take the figure as final.",
  "prob.por_que.plegado": "Why does it happen?",
  "prob.ahorro.como": "How is it calculated?",
  // Gráficos del Diagnóstico (D-152).
  "graf.titulo": "Where the money goes",
  "graf.dia": "Spend per day",
  "graf.hora": "Spend per hour",
  "graf.real": "real work",
  "graf.evitable": "avoidable",
  "graf.punto": "{fecha}: {coste}, of which {evitable} avoidable",
  "graf.aria": "Spend per period with the avoidable part on top",
  "graf.reparto": "How is the avoidable part split across days?",
  "graf.reparto.texto": "The avoidable part is measured over the whole range, not day by day. Here it is split in proportion to what each problem's step spent each day: the days add up to the figure above, and a day when that step didn't run gets nothing.",
  "graf.sin_repartir": "{coste} of avoidable spend couldn't be split: its step has no priced spend in this range.",
  "graf.pasos": "Cost per step",
  "graf.otros": "Other steps",
  "graf.paso.evitable": "{evitable} avoidable",
  // Textos que pinta el CSS (`content:`): el proveedor de idioma los pasa como variables.
  "css.porque": "why?",
  "css.avanzado": "advanced",
  // El grafo del agente en la vista de traza (D-153).
  "grafo.titulo": "How the agent is built",
  "grafo.lead": "One box per step and one arrow for each step that calls another, with how many times it did so in this run.",
  "grafo.aria": "Agent graph with {pasos} steps",
  "grafo.llamadas_one": "{n} call",
  "grafo.llamadas_other": "{n} calls",
  "grafo.errores_one": "{n} with an error",
  "grafo.errores_other": "{n} with errors",
  "grafo.tipo.agent": "agent",
  "grafo.tipo.llm": "model",
  "grafo.tipo.tool": "tool",
  "grafo.tipo.retrieval": "retrieval",
  "grafo.tipo.chain": "step",
  "grafo.tipo.otro": "other",
  "grafo.sin_tarifa": "no rate",
  "grafo.al_menos": "≥ {coste}",
  "aj.regla.prompt_caro": "More expensive prompt",
  "diag.ahorrado_one": "You've already stopped paying {coste} since you fixed one problem.",
  "diag.ahorrado_other": "You've already stopped paying {coste} since you fixed {n} problems.",
  "diag.ahorrado.suelo": "at least {coste}",
  "ciclo.titulo": "Where this problem stands",
  "ciclo.detectar": "Detect",
  "ciclo.probar": "Test",
  "ciclo.arreglar": "Fix",
  "ciclo.verificar": "Verify",
  "ciclo.estado.hecho": "done",
  "ciclo.estado.en_curso": "in progress",
  "ciclo.estado.pendiente": "pending",
  "ciclo.estado.fallo": "didn't work",
  "ciclo.detectar.hecho": "We found it in your traces.",
  "ciclo.probar.pendiente": "Test the fix on its real calls before changing anything.",
  "ciclo.probar.conjunto": "Its runs are saved in “{nombre}”; the test hasn't been run yet.",
  "ciclo.probar.hecho_one": "{n} run on “{nombre}”.",
  "ciclo.probar.hecho_other": "{n} runs on “{nombre}”.",
  "ciclo.probar.sin_paso": "This problem isn't about a single step: test it on the whole agent.",
  "ciclo.arreglar.pendiente": "Apply the fix and mark it here.",
  "ciclo.arreglar.hecho": "Marked as fixed on {fecha}.",
  "ciclo.verificar.pendiente": "We check it on our own once there are runs after the fix.",
  "ciclo.ignorado": "You ignored it: the cycle stops here.",
  "seg.probar.texto.prompt": "The cost difference is measured; whether v{a} is as accurate as v{b} isn't. Save this step's real runs as a case set and run them with each version: Test will tell you which one is more accurate and what each one costs.",
  "seg.probar.texto.otro": "The saving is measured; whether the fixed agent answers just as well isn't. Save this step's real runs as a case set and run them with the fix in place: Test will tell you whether it's just as accurate and how much less it costs.",
  "seg.probar.existe": "Already saved: “{nombre}”, {n} cases.",
  "seg.probar.arreglado": "fixed",
  "prob.prompt.titulo": "Go back to v{a} from Prompts",
  "prob.prompt.texto": "The card for “{prompt}” shows both versions with what each one costs and how accurate it is, and puts v{a} in production with one click.",
  "prob.prompt.ir": "Open “{prompt}” in Prompts →",
  "pr.hallazgo": "It shows up in Diagnosis: {titulo}.",
  "pr.hallazgo.ver": "See the problem →",
  "ev.por_probar.titulo": "Fixes to test",
  "ev.por_probar.lead": "The open problems from Diagnosis, with what they give back and whether they already have a test. Saving their runs creates the case set with that step's real calls.",
  "ev.por_probar.sin_probar": "not tested",
  "ev.por_probar.guardado": "saved, no run",
  "ev.por_probar.probado_one": "{n} run",
  "ev.por_probar.probado_other": "{n} runs",
  "ev.por_probar.guardar": "Save its runs",
  "ev.por_probar.guardado_como": "Saved as “{nombre}”. Run it with the fix in place:",
  "ev.por_probar.ver": "See the problem",
  "ev.por_probar.error": "couldn't save",
  "aj.contraste.alto": "High contrast",
  "aj.contraste.texto": "Opaque backgrounds, no transparency or blur, and text at maximum contrast. Works with both the light and the dark theme.",
  "arbol.envoltorio": "Same as “{hijo}”, which is inside: this step only wraps it.",
  "nav.clientes": "Customers",
  "titulo.clientes": "Customers",
  "cl.titulo": "Margin per customer for “{proyecto}”",
  "cl.lead": "What each customer pays you against what their work costs you, per month. The cost comes from their runs; what they pay, you enter.",
  "cl.aviso_one": "This customer is losing you money",
  "cl.aviso_other": "These {n} customers are losing you money",
  "cl.aviso.texto": "Their work costs you more than they pay. Check which Diagnosis problems happen in their runs, or review their price.",
  "cl.h.cliente": "Customer",
  "cl.h.ejecuciones": "Runs",
  "cl.h.coste": "Cost per month",
  "cl.h.ingresos": "Pays per month ($)",
  "cl.h.margen": "Margin per month",
  "cl.estado.pierde": "losing money",
  "cl.estado.ajustado": "thin margin",
  "cl.estado.gana": "profitable",
  "cl.estado.sin-ingresos": "no revenue",
  "cl.estado.sin-proyeccion": "little data",
  "cl.estado.sin-trafico": "no runs",
  "cl.ingresos.aria": "What {cliente} pays per month, in dollars",
  "cl.guardar": "Save",
  "cl.error.guardar": "couldn't save",
  "cl.sin_cliente": "{coste} from {n} runs don't say which customer they belong to: they're counted apart, not split up.",
  "cl.como.titulo": "How to say which customer each run is for",
  "cl.como.texto": "One line before the agent works for that customer. Evaluation runs don't count: they aren't any customer's work.",
  "cl.anadir": "Enter what a customer pays before their runs arrive",
  "cl.anadir.id": "Customer",
  "cl.anadir.importe": "Pays per month ($)",
  "diag.clientes": "Customers",
  "diag.clientes.pierden_one": "{n} customer is losing you money.",
  "diag.clientes.pierden_other": "{n} customers are losing you money.",
  "diag.clientes.ver": "See margin per customer",
  "trazas.filtro.cliente": "Only runs for customer {cliente}",
  "cl.problemas": "Happens in their runs:",
  "cl.ver_ejecuciones": "See their runs →",
  "aj.regla.cliente_pierde": "Customer losing money",
  "cl.stripe.titulo": "Revenue from Stripe",
  "cl.stripe.lead": "Instead of typing it in: what each customer pays comes from their invoices paid in the last month, brought to a month (an annual plan counts a twelfth). Each Stripe customer is matched to the one in your traces by metadata.laplace_customer_id, or by its id. A restricted key that can read invoices and customers is enough.",
  "cl.stripe.clave": "Stripe key",
  "cl.stripe.puesta": "Key set ({pista}).",
  "cl.stripe.ultima": "Last time: {fecha}, {n} customers.",
  "cl.stripe.nunca": "Nothing brought in yet.",
  "cl.stripe.traer": "Bring from Stripe",
  "cl.stripe.quitar": "Remove key",
  "cl.stripe.fuente": "Stripe",
};
