/**
 * Catálogo de origen (D-147). Define las claves: los otros idiomas se tipan contra él.
 *
 * Los huecos van entre llaves. Los que se rellenan con un elemento —un enlace, un
 * `<code>`— se rellenan con `tr()`; los demás, con `t()`. Los plurales son dos claves,
 * `_one` y `_other`, y se piden con `tn()`.
 */
export const es = {
  // Duraciones en palabras. Espejo de `span_label` y `window_label` del backend.
  "tiempo.dias_one": "{n} día",
  "tiempo.dias_other": "{n} días",
  "tiempo.horas_one": "{n} hora",
  "tiempo.horas_other": "{n} horas",
  "tiempo.minutos_one": "{n} minuto",
  "tiempo.minutos_other": "{n} minutos",
  "tiempo.menos_de_un_minuto": "menos de un minuto",
  "ventana.dias_one": "el último día",
  "ventana.dias_other": "los últimos {n} días",
  "ventana.horas_one": "la última hora",
  "ventana.horas_other": "las últimas {n} horas",
  "ventana.minutos_one": "el último minuto",
  "ventana.minutos_other": "los últimos {n} minutos",
  "relativo.ahora": "hace un momento",
  "relativo.min": "hace {n} min",
  "relativo.h": "hace {n} h",
  "relativo.d": "hace {n} d",

  "nav.diagnostico": "Diagnóstico",
  "nav.trazas": "Trazas",
  "nav.panel": "Panel",
  "nav.evaluaciones": "Probar",
  "nav.prompts": "Prompts",
  "nav.ajustes": "Ajustes",

  "barra.proyecto": "Proyecto",
  "barra.sin_proyectos": "Sin proyectos",
  "barra.rango": "Rango temporal",
  "barra.idioma": "Idioma",
  "barra.avanzado": "Avanzado",
  "barra.avanzado_ayuda": "Enseña la capa técnica: consultas, atributos, identificadores",
  "barra.tu_cuenta": "Tu cuenta: {email}",
  "barra.organizacion": "Organización y cuenta",
  "barra.salir": "Salir",
  "rango.1": "24 horas",
  "rango.7": "7 días",
  "rango.30": "30 días",

  "estado.sin_backend.titulo": "No podemos conectar con el backend",
  "estado.sin_backend.texto":
    "No responde. Si estás en local, arráncalo con {local}; si es la instalación completa, con {docker}.",
  "estado.reintentar": "Reintentar",
  "estado.sin_proyecto.titulo": "Todavía no hay ningún proyecto",
  "estado.sin_proyecto.texto":
    "En cuanto tu agente envíe su primera ejecución, aparecerá aquí. Instrumentarlo es una línea:",
  "estado.primer_proyecto":
    "En esta instalación el agente necesita una clave para enviar trazas. {enlace}: ahí mismo sale el fragmento de arriba con la clave puesta.",
  "estado.primer_proyecto.enlace": "Créala en Organización",
  "estado.demo.texto":
    "¿Sólo quieres verlo funcionando? Carga unas trazas de ejemplo —datos inventados, en un proyecto aparte llamado «demo»— y mira qué detecta.",
  "estado.demo.cargando": "Cargando…",
  "estado.demo.boton": "Cargar datos de ejemplo",
  "estado.demo.terminal": "Desde una terminal: {comando}.",
  "estado.demo.error": "no se han podido cargar",
  "estado.sin_trazas.titulo": "Esperando la primera ejecución de «{proyecto}»",
  "estado.sin_trazas.texto":
    "Todavía no ha llegado ninguna traza de este proyecto. En cuanto lances tu agente con Laplace activado, aparecerá aquí:",
  "estado.nada.titulo_con_aviso":
    "No hemos encontrado nada que arreglar, pero no hemos podido mirarlo todo",
  "estado.nada.titulo": "No estás tirando dinero ahora mismo",
  "estado.nada.texto":
    "Hemos buscado llamadas repetidas, pasos que usan un modelo más caro del que necesitan y contexto que se reenvía sin hacer falta. No hay nada de eso en este rango.",
  "estado.clave.titulo": "Esta instalación pide una clave",
  "estado.clave.sin_clave":
    "Si no tienes una, la crea quien administra esta organización, en Organización → Claves.",
  "estado.clave.guardar": "Guardar y entrar",
  "estado.clave.con_cuenta": "Entrar con tu cuenta",
  "estado.clave.cookie":
    "Se comprueba y se guarda en una cookie que sólo ve este Laplace: ni la página ni ningún script pueden leerla, y nunca va en la URL —lo que va en la URL acaba en los logs de cualquier proxy por el que pase—.",
  "estado.ajeno.titulo": "Tu clave no da acceso a este proyecto",
  "estado.ajeno.texto": "Esta clave sirve para otro proyecto de esta instalación.",
  "estado.ajeno.otra": "Usar otra clave",
  "estado.volver": "Volver",
  "diag.titulo": "Tu agente «{proyecto}»",
  "diag.al_ritmo": "Al ritmo de {ventana}",
  "diag.en_datos": "En {tiempo} de datos",
  "diag.costara": "te costará este mes",
  "diag.ha_costado": "te ha costado hasta ahora",
  "diag.contexto": "Contexto",
  "diag.cobertura": "Cobertura",
  "diag.metricas": "Métricas",
  "diag.m.p95": "Latencia p95",
  "diag.m.errores": "Ejecuciones con error",
  "diag.m.tokens": "Tokens",
  "diag.m.trazas": "Trazas",
  "diag.m.pasos": "Pasos",
  "diag.m.coste": "Coste por ejecución",
  "diag.m.cache": "Ya ahorrado por la caché",
  "diag.m.datos": "Datos observados",
  "diag.nada.aviso": "Con esa cobertura, «no hay nada que arreglar» significa «no lo sabemos», no «está bien».",
  "diag.nada.gastado": "Llevas {coste} gastados en {ejecuciones} ejecuciones.",
  "diag.ver_trazas": "Ver todas las trazas",
  "diag.cosas_one": "Una cosa que arreglar",
  "diag.cosas_other": "{n} cosas que arreglar",
  "comun.exportar_csv": "Exportar CSV",
  "diag.orden": "De la que más dinero te devuelve a la que menos.",
  "diag.cifras_proyeccion": "Las cifras son la proyección a 30 días de {ventana}.",
  "diag.cifras_gastado": "Las cifras son dinero ya gastado en {ventana}.",
  "diag.nota.proyeccion": "Los importes son una estimación a partir de {ventana} de datos, proyectada a 30 días. Si tu tráfico cambia, cambian.",
  "diag.nota.gastado": "Los importes son dinero {ya} en {ventana}, no una proyección: no hay datos suficientes para estimar el mes.",
  "diag.nota.ya_gastado": "ya gastado",
  "diag.nota.moneda": "El coste está en {moneda} porque es la moneda en la que facturan los proveedores.",
  "diag.ver_mas_one": "Ver uno más",
  "diag.ver_mas_other": "Ver {n} más",
  "diag.tiempo_one": "Y uno que no cuesta dinero, sólo tiempo",
  "diag.tiempo_other": "Y {n} que no cuestan dinero, sólo tiempo",
  "diag.presupuesto": "Presupuesto",
  "diag.presupuesto.invitar": "{enlace} y te avisamos antes de pasarte.",
  "diag.presupuesto.enlace": "Ponle un presupuesto mensual",
  "diag.presupuesto.aria": "{n} por ciento del presupuesto",
  "estado.arreglado": "Arreglado",
  "estado.ignorado": "Ignorado",
  "estado.desaparecido": "Ya no ocurre",
  "diag.apartados_one": "Un problema que ya no está pendiente",
  "diag.apartados_other": "{n} problemas que ya no están pendientes",
  "diag.desaparecido": "No ocurre desde el {fecha}. No cuenta como ahorro: arreglarlo ya no te devolvería nada.",
  "diag.ignorado_coste": "{coste} en el rango, que no cuentan como evitable.",
  "csv.abierto": "abierto",
  "csv.si": "sí",
  "csv.no": "no",
  "csv.h.problema": "Problema",
  "csv.h.tipo": "Tipo",
  "csv.h.estado": "Estado",
  "csv.h.gastado": "Ya gastado (USD)",
  "csv.h.al_mes": "Al mes (USD)",
  "csv.h.suelo": "Es un suelo",
  "csv.h.tokens": "Tokens de más",
  "csv.h.espera": "Espera evitable (s)",
  "csv.h.ejecuciones": "Ejecuciones afectadas",
  "csv.h.arreglo": "Arreglo",
  "csv.nombre.problemas": "problemas",
  "piezas.gap.aria": "{necesario} de coste necesario, {evitable} evitable",
  "piezas.gap.real": "{coste} de trabajo real",
  "piezas.gap.tirando": "{coste} que estás tirando",
  "piezas.puesto": "Puesto {n}",
  "piezas.tokens_de_mas": "tokens de más",
  "piezas.espera": "de espera evitable",
  "piezas.al_mes": "al mes",
  "piezas.ya_gastado": "ya gastado",
  "piezas.reaparecido": "Lo marcaste como arreglado y sigue saliendo.",
  "piezas.marcado": "Marcado como arreglado.",
  "piezas.sin_tarifa": "Gasta tokens; sin tarifa para ponerle precio",
  "piezas.suelo": "Es un suelo: el coste real puede ser mayor",
  "piezas.sin_verificar": "Con tarifa sin verificar",
  "piezas.ver_arreglo": "Ver cómo arreglarlo →",
  "avisos.casi_todo": "Casi todo lo que gastas está señalado aquí abajo:",
  "avisos.casi_todo.cifras": "{evitable} de {total} ({pct}).",
  "avisos.casi_todo.porque": "¿Por qué no lo presentamos como ahorro?",
  "avisos.casi_todo.texto": "Porque «puedes dejar de pagar tu agente» casi nunca es lo que significa. Lo que suele haber detrás es un agente pequeño o recién estrenado donde dos o tres pasos son prácticamente toda la factura, y arreglarlos cambia esos pasos, no el agente entero. Mira el desglose de cada problema antes de contar con esta cifra.",
  "avisos.no_lo_usas": "no lo usas",
  "avisos.pct_aria": "{n} por ciento",
  "avisos.de_llamadas": "{n} de {total} llamadas",
  "avisos.incompleto": "Este total está incompleto:",
  "avisos.incompleto.linea": "{n} pasos sin tarifa ({modelos}).",
  "avisos.incompleto.porque": "Su modelo no está en nuestra tabla de precios, así que no sabemos cuánto cuestan y no se suman. Puedes ponerle precio en Ajustes, y se recalcula lo ya guardado.",
  "avisos.suelo": "Es un suelo:",
  "avisos.suelo.linea_one": "en {n} paso hemos cobrado la tarifa estándar.",
  "avisos.suelo.linea_other": "en {n} pasos hemos cobrado la tarifa estándar.",
  "avisos.suelo.porque": "Contexto largo, residencia de datos o modo rápido son metros aparte que la respuesta del proveedor no siempre revela. El coste real puede ser algo mayor, nunca menor. En cada paso, en modo avanzado, se dice cuál es la duda.",
  "avisos.proyeccion": "Proyección desde {ventana} de datos.",
  "avisos.proyeccion.porque": "Es lo que llevas enviando, no el rango que pide el selector. Gasto y ahorro salen de la misma base: si cambia una, cambia la otra.",
  "avisos.sin_proyectar": "Dinero ya gastado, sin proyectar.",
  "avisos.sin_proyectar.linea": "La previsión mensual aparece con {tiempo} de datos.",
  "avisos.sin_proyectar.porque": "Con {ventana} de datos, multiplicar para llegar a 30 días da una cifra que no se sostiene: un pico de diez minutos se convertiría en cientos de dólares.",
  "avisos.mucho": "El ahorro estimado es el {pct} de lo que gastas.",
  "avisos.mucho.porque": "Es mucho: suele pasar en agentes pequeños o recién estrenados, donde unos pocos pasos dominan la factura. Antes de darlo por bueno, mira el desglose de cada problema.",
  "avisos.sin_dinero": "No podemos calcular el dinero",
  "prob.no_aparece.titulo": "Ese problema ya no aparece",
  "prob.no_aparece.texto": "O lo has arreglado, o ha dejado de darse en el rango que estás mirando. Enhorabuena en cualquiera de los dos casos.",
  "prob.que_pasa": "Qué está pasando",
  "prob.deteccion": "Cómo lo hemos detectado",
  "prob.deteccion.nota": "Es la consulta que se ha ejecutado, no una versión de ejemplo. Los umbrales de las reglas son los mismos para todos los proyectos: en Ajustes se decide qué avisa, no qué se detecta.",
  "prob.traza": "La traza completa",
  "prob.traza.texto": "Una ejecución real donde se ve el problema.",
  "prob.traza.abrir": "Ábrela para navegarla paso a paso →",
  "prob.atributos": "Atributos del paso señalado",
  "prob.arreglo": "Cómo arreglarlo",
  "prob.ahorro": "Cuánto te ahorras",
  "prob.ahorro.ya": "En {ventana} ya se han ido {coste} por aquí.",
  "prob.ahorro.mes": "A ese ritmo, arreglarlo te deja de costar {coste}.",
  "prob.ahorro.al_mes": "{coste} al mes",
  "prob.ahorro.sin_mes": "Todavía no proyectamos el mes: con {tiempo} de datos, multiplicar hasta 30 días daría una cifra que no se sostiene.",
  "prob.ahorro.suelo": "Y es un {suelo}: hay pasos aquí dentro cuyo coste no podemos confirmar, así que la cifra real puede ser mayor, nunca menor.",
  "prob.ahorro.suelo.palabra": "suelo",
  "prob.ahorro.sin_verificar": "La tarifa de {modelos} no la hemos verificado: sale de la tabla comunitaria de LiteLLM y puede no coincidir con tu factura, por arriba o por abajo.",
  "prob.ahorro.tokens": "Esto gasta {tokens} de más y {espera} de espera en el rango analizado. Cuánto dinero es, no lo sabemos: {motivo}.",
  "prob.ahorro.tokens.n": "{n} tokens",
  "prob.ahorro.sin_tarifa": "ese modelo no tiene tarifa conocida",
  "prob.ahorro.tiempo": "Este problema no te cuesta dinero: los pasos repetidos no consumen tokens. Lo que te cuesta es espera, {espera} en el rango analizado. Arreglarlo hace que tu agente responda antes.",
  "prob.calculo": "Cálculo:",
  "prob.solo_lectura": "Tu rol en este proyecto ({rol}) permite verlo, no marcarlo como arreglado ni ignorarlo.",
  "prob.ver_afectadas": "Ver las trazas afectadas",
  "prob.ver_ultimas": "Ver las últimas ejecuciones de este paso",
  "tec.al_mes": "al mes si no cambia nada",
  "tec.ya_gastados": "ya gastados en {ventana}",
  "tec.espera": "de espera evitable en {ventana}",
  "tec.afectadas": "afectadas",
  "tec.vueltas_mas_one": "…{n} vuelta más, todas con la misma respuesta.",
  "tec.vueltas_mas_other": "…{n} vueltas más, todas con la misma respuesta.",
  "tec.identicas_mas_one": "…{n} llamada idéntica más, todas con la misma respuesta.",
  "tec.identicas_mas_other": "…{n} llamadas idénticas más, todas con la misma respuesta.",
  "tec.tarifa_aplicada": "tarifa aplicada",
  "tec.tarifa_no_verificada": "tarifa no verificada",
  "tec.tarifa_asumida": "tarifa asumida",
  "seg.error.guardar": "no se ha podido guardar",
  "seg.error.deshacer": "no se ha podido deshacer",
  "seg.error.crear": "no se ha podido crear",
  "seg.titulo.ignorado": "Lo has marcado como ignorado",
  "seg.titulo.reaparecido": "Lo marcaste como arreglado, y sigue saliendo",
  "seg.titulo.arreglado": "Lo has marcado como arreglado",
  "seg.fecha": "El {fecha}.",
  "seg.antes": "Antes, por ejecución",
  "seg.despues": "Después",
  "seg.ejecuciones": "{n} ejecuciones",
  "seg.ignorado.nota": "No cuenta en el evitable del inicio ni manda alertas.",
  "seg.deshacer": "Deshacer y devolverlo a la lista",
  "seg.ya_arreglado": "¿Ya lo has arreglado?",
  "seg.ya_arreglado.texto": "Márcalo y lo comprobamos: comparamos lo que costaba cada ejecución antes con lo que cuesta después. Si sigue saliendo igual, vuelve a la lista.",
  "seg.nota.placeholder": "Por qué no es un problema (opcional)",
  "seg.ignorar": "Ignorar este problema",
  "comun.cancelar": "Cancelar",
  "seg.arreglado.boton": "Lo he arreglado: compruébalo",
  "seg.no_problema": "No es un problema para mí",
  "seg.probar.titulo": "Antes de cambiarlo, compruébalo",
  "seg.probar.texto": "El ahorro está medido; que {modelo} responda igual de bien, no. Guarda las ejecuciones reales de este paso y reenvía sus llamadas a {modelo} con la orden de abajo: corre en tu máquina, con tu clave y un tope de gasto, y el juez compara cada respuesta con la original. Probar te dirá si acierta igual y cuánto cuesta menos.",
  "seg.probar.barato": "el modelo barato",
  "seg.probar.ir": "Ir a Probar →",
  "seg.probar.crear": "Crear el conjunto «{nombre}» con estas ejecuciones",
  "seg.tokens": "{n} tokens",
  "trazas.orden.coste": "Más caras primero",
  "trazas.orden.reciente": "Más recientes",
  "trazas.orden.duracion": "Más lentas",
  "trazas.tipo.cualquiera": "Cualquier paso",
  "trazas.tipo.llm": "Con llamada a modelo",
  "trazas.tipo.tool": "Con herramienta",
  "trazas.tipo.retrieval": "Con búsqueda",
  "trazas.titulo": "Trazas",
  "trazas.lead": "Cada fila es una ejecución completa de tu agente. Ordenadas por lo que cuestan.",
  "trazas.buscar.contenido": "Buscar un pedido, una frase, un id…",
  "trazas.buscar.nombres": "Buscar por paso, herramienta o id de traza",
  "trazas.buscar": "Buscar",
  "trazas.donde": "Dónde buscar",
  "trazas.en_nombres": "En nombres e id",
  "trazas.en_contenido": "En prompts y respuestas",
  "trazas.estado": "Estado",
  "trazas.estado.cualquiera": "Cualquier estado",
  "trazas.estado.error": "Sólo con error",
  "trazas.estado.ok": "Sólo correctas",
  "trazas.tipo": "Tipo de paso",
  "trazas.orden": "Orden",
  "trazas.modelo": "Modelo",
  "trazas.modelo.cualquiera": "Cualquier modelo",
  "trazas.coste_minimo": "Coste mínimo",
  "trazas.coste_minimo.aria": "Coste mínimo en USD",
  "trazas.sesion.aria": "Identificador de sesión",
  "trazas.filtrar": "Filtrar",
  "trazas.corta": "Para buscar en prompts y respuestas escribe al menos {n} caracteres.",
  "trazas.filtro.paso": "Sólo las ejecuciones que pasan por el paso del problema: {paso}",
  "trazas.filtro.usuario": "Sólo las ejecuciones del usuario {usuario}",
  "trazas.quitar": "Quitar",
  "trazas.ninguna": "Ninguna traza coincide",
  "trazas.ninguna.texto": "Prueba a quitar filtros o a ampliar el rango temporal en la barra de arriba.",
  "trazas.quitar_filtros": "Quitar filtros",
  "csv.h.traza": "Traza",
  "csv.h.agente": "Agente",
  "csv.h.inicio": "Inicio",
  "csv.h.sesion": "Sesión",
  "csv.h.usuario": "Usuario",
  "csv.h.cliente": "Cliente",
  "csv.h.pasos": "Pasos",
  "csv.h.tok_entrada": "Tokens entrada",
  "csv.h.tok_salida": "Tokens salida",
  "csv.h.coste": "Coste (USD)",
  "csv.h.incompleto": "Coste incompleto",
  "csv.h.duracion": "Duración (ms)",
  "csv.h.modelos": "Modelos",
  "csv.nombre.trazas": "trazas",
  "lista.n_trazas": "{n} trazas",
  "lista.en_pausa": " · en pausa",
  "lista.cada": "Se comprueba cada {n} segundos",
  "lista.vivo.necesita": "El modo en vivo necesita el orden por más recientes: al pulsar se cambia",
  "lista.vivo.pausar": "En vivo · pausar",
  "lista.vivo.ver": "Ver en vivo",
  "lista.col.traza": "Traza",
  "lista.col.modelos": "Modelos",
  "lista.col.pasos": "Pasos",
  "lista.col.tokens": "Tokens",
  "lista.col.entrada": "Entrada",
  "lista.col.salida": "Salida",
  "lista.col.coste": "Coste",
  "lista.col.cliente": "Cliente",
  "lista.col.duracion": "Duración",
  "lista.col.cuando": "Cuándo",
  "lista.col.bien": "¿Bien?",
  "lista.todas": " (todas las del rango)",
  "lista.antiguas": "Más antiguas →",
  "lista.sin_backend": "El backend no responde; se sigue intentando.",
  "lista.nuevas_one": "{n} traza nueva desde que lo encendiste.",
  "lista.nuevas_other": "{n} trazas nuevas desde que lo encendiste.",
  "lista.esperando": "Esperando trazas nuevas.",
  "lista.ultima": "Última comprobación: {fecha}.",
  "lista.con_error": "con error",
  "lista.sin_nombre": "(sin nombre)",
  "lista.bucle.ayuda": "Repite pasos con la misma entrada",
  "lista.bucle": "bucle",
  "lista.errores_one": "{n} error",
  "lista.errores_other": "{n} errores",
  "lista.sesion": " · sesión {id}",
  "lista.coste_incompleto": "coste incompleto",
  "conj.creado": "Conjunto «{nombre}» creado con este filtro.",
  "conj.ir": "Ir a Probar",
  "conj.guardar": "Guardar estas trazas como conjunto de casos",
  "conj.nombre.placeholder": "Nombre, p. ej. regresiones-checkout",
  "conj.nombre.aria": "Nombre del conjunto",
  "conj.creando": "Creando…",
  "conj.boton": "Guardar (hasta 50)",
  "traza.no_encontrada": "No encontramos esa traza",
  "traza.no_encontrada.texto": "Puede que el identificador esté mal, o que la traza sea anterior a lo que se conserva.",
  "traza.todas": "Todas las trazas",
  "traza.diag.error": "No se pudo pedir el diagnóstico.",
  "traza.diag.sugerencia": "Qué cambiar:",
  "traza.diag.pie": "Diagnóstico de {modelo}, que costó {coste}. Cada afirmación cita los pasos de los que sale; las cifras de dinero las dan las reglas, no el modelo.",
  "traza.diag.coste_desconocido": "un importe que no sabemos (el modelo no está en la tabla de precios)",
  "traza.diag.tiradas_one": "Se descartó una afirmación que no citaba ningún paso de esta traza.",
  "traza.diag.tiradas_other": "Se descartaron {n} afirmaciones que no citaban pasos de esta traza.",
  "traza.diag.vacio": "Esta ejecución aún no tiene diagnóstico. Un modelo puede leerla y decir qué falló, citando cada paso.",
  "traza.diag.pidiendo": "Diagnosticando…",
  "traza.diag.otra_vez": "Diagnosticar otra vez",
  "traza.diag.pedir": "Diagnosticar con modelo",
  "traza.problemas_one": "En esta ejecución pasa un problema detectado:",
  "traza.problemas_other": "En esta ejecución pasan {n} problemas detectados:",
  "traza.estado.ignorado": "ignorado",
  "traza.estado.reaparecido": "marcado como arreglado, pero sigue",
  "traza.estado.arreglado": "marcado como arreglado",
  "traza.bien": "¿Esta ejecución está bien?",
  "traza.juez.sin_tarifa": "Juzgada con {modelo}. Su coste no lo sabemos: ese modelo no está en la tabla de precios.",
  "traza.juez.coste": "Juzgada con {modelo}. Ha costado {coste}.",
  "traza.juez.error": "el juez no ha podido opinar",
  "traza.juez.juzgando": "Juzgando…",
  "traza.juez.opine": "Que opine {modelo}",
  "traza.juez.ocultar": "Ocultar el prompt del juez",
  "traza.juez.ver": "Ver el prompt del juez",
  "traza.exportar": "Exportar traza en JSON",
  "traza.usuario": " · usuario {id}",
  "traza.coste.faltan": "coste (faltan {n} pasos sin tarifa)",
  "traza.coste.sin_verificar": "coste (tarifa no verificada)",
  "traza.coste": "coste",
  "traza.tokens": "tokens entrada / salida",
  "traza.duracion": "duración",
  "traza.pasos": "pasos",
  "traza.llamadas": "llamadas a modelo",
  "traza.herramientas": "herramientas",
  "traza.modelos": "modelos",
  "traza.cache_tokens": "tokens servidos desde caché",
  "traza.cache_ahorro": "que te ha ahorrado la caché",
  "traza.asumida": "pasos con tarifa asumida",
  "traza.errores": "errores",
  "arbol.titulo": "Árbol de ejecución",
  "arbol.n_de": "{n} de {total} pasos",
  "arbol.teclas": "↑↓ moverse · ←→ plegar",
  "arbol.plegar_todo": "Plegar todo",
  "arbol.desplegar_todo": "Desplegar todo",
  "arbol.desplegar": "desplegar",
  "arbol.plegar": "plegar",
  "arbol.misma_llamada": "Misma llamada con la misma entrada",
  "arbol.selecciona": "Selecciona un paso del árbol.",
  "arbol.prompt": "Prompt ({n})",
  "arbol.respuesta": "Respuesta ({n})",
  "arbol.argumentos": "Argumentos",
  "arbol.salida": "Salida",
  "arbol.consulta": "Consulta",
  "arbol.documentos": "Documentos ({n})",
  "arbol.entrada": "Entrada",
  "arbol.eventos": "Eventos ({n})",
  "arbol.evento": "evento",
  "arbol.modelo": "modelo",
  "arbol.tok_entrada": "tokens entrada",
  "arbol.tok_entrada_est": "tokens entrada (estimados)",
  "arbol.tok_salida": "tokens salida",
  "arbol.tok_salida_est": "tokens salida (estimados)",
  "arbol.sin_precio": "no sabemos el precio",
  "arbol.coste_minimo": "coste mínimo (tarifa asumida)",
  "arbol.desde_cache": "desde caché ({coste})",
  "arbol.escritos_cache": "escritos en caché ({coste})",
  "arbol.ahorro_cache": "que ha ahorrado la caché",
  "arbol.rama.pasos": "pasos de la rama",
  "arbol.rama.error": "con error",
  "arbol.rama.tokens": "tokens de la rama",
  "arbol.rama.coste": "coste de la rama",
  "arbol.mensaje": "mensaje",
  "arbol.contenido": "contenido",
  "arbol.raiz": "(raíz)",
  "arbol.estimados": "true (los contamos nosotros)",
  "arbol.del_proveedor": "false (del proveedor)",
  "arbol.ninguna": "ninguna: modelo desconocido",
  "arbol.atributos": "Atributos crudos",
  "arbol.sin_contenido": "Sin contenido.",
  "arbol.copiado": "copiado",
  "arbol.copiar": "copiar",
  "arbol.misma_entrada": "Misma llamada, misma entrada",
  "ver.buena": "Marcar esta ejecución como buena",
  "ver.mala": "Marcar esta ejecución como mala",
  "ver.solo_ver": "Tu rol sólo permite ver",
  "ver.bien": "Bien",
  "ver.mal": "Mal",
  "ver.ocultar": "Ocultar comentario",
  "ver.ver": "Ver comentario",
  "ver.comentar": "Comentar",
  "ver.placeholder": "Qué falló, o por qué está bien. Se guarda al marcar.",
  "ver.nota": "El comentario se guarda con el veredicto: vuelve a pulsar «{bien}» o «{mal}» después de escribirlo.",
  "ver.juez": "juez",
  "ver.no_guardado": "no se ha guardado",
  "ver.maquina": "veredicto de máquina",
  "ver.juez_dice": "juez: {v}",
  "ver.bien_min": "bien",
  "ver.mal_min": "mal",
  "ver.coste_desconocido": " coste desconocido",
  "ver.persona": "persona: {v}",
  "panel.titulo": "Tu agente «{proyecto}», por unidad de trabajo",
  "panel.por_ejecucion": "Por ejecución",
  "panel.por_ejecucion.lead": "Lo que cuesta una ejecución de tu agente. Es la cifra que importa: un gasto que sube porque hay más trabajo no es un problema, y esto lo separa.",
  "panel.totales": "Totales, como contexto",
  "panel.totales.lead": "Van aquí abajo a propósito: por sí solos no dicen si algo va mal.",
  "panel.error.cargar": "no se ha podido cargar",
  "panel.quien": "Quién gasta más",
  "panel.agrupar": "Agrupar por",
  "panel.usuarios": "Usuarios",
  "panel.sesiones": "Sesiones",
  "panel.sin_usuario": "Ninguna ejecución de este rango dice de qué usuario es. Con {codigo} en tu agente, aquí verás a quién se le va el gasto.",
  "panel.sin_sesion": "Ninguna ejecución de este rango dice de qué sesión es. Con {codigo} en tu agente, aquí verás a quién se le va el gasto.",
  "panel.col.usuario": "Usuario",
  "panel.col.sesion": "Sesión",
  "panel.col.ejecuciones": "Ejecuciones",
  "panel.col.por_ejecucion": "Por ejecución",
  "panel.col.total": "Total",
  "panel.col.del_gasto": "Del gasto",
  "panel.sin_etiqueta_usuario": "Además, {n} ejecuciones sin usuario ({coste}).",
  "panel.sin_etiqueta_sesion": "Además, {n} ejecuciones sin sesión ({coste}).",
  "panel.menos_de": "< {x}",
  "panel.sin_comparacion": "sin comparación",
  "panel.vs_anterior": "{cambio} vs. el periodo anterior",
  "panel.grafica.titulo": "Coste por ejecución, en tramos de {tramo}",
  "panel.grafica.coste": "coste por ejecución",
  "panel.grafica.ejecuciones": "ejecuciones",
  "panel.grafica.aria": "Coste por ejecución por tramo",
  "panel.grafica.punto": "{fecha} · {coste} por ejecución · {n} ejecuciones",
  "panel.grafica.desde": " · desde el primer dato",
  "panel.grafica.nota": "Los tramos sin ejecuciones se quedan en blanco. No es coste cero: es que no hubo nada que ejecutar, y pintarlo como cero dibujaría una bajada que no ha existido.",
  "panel.picos": "Picos",
  "panel.picos.ninguno": "Ningún tramo se sale de lo normal en este rango. El coste por ejecución se mantiene dentro de lo que cuesta habitualmente.",
  "panel.picos.n_one": "Un tramo se sale de lo normal",
  "panel.picos.n_other": "{n} tramos se salen de lo normal",
  "panel.picos.lead": "Tramos en los que cada ejecución costó mucho más que de costumbre. Del más caro al menos.",
  "panel.pico.cuando": "Empezó el {inicio}, y duró hasta las {fin}",
  "panel.pico.de_mas": "de más",
  "panel.pico.texto_one": "En ese tramo cada ejecución costó {coste}, frente a los {base} de costumbre: {veces} sobre {n} ejecución.",
  "panel.pico.texto_other": "En ese tramo cada ejecución costó {coste}, frente a los {base} de costumbre: {veces} sobre {n} ejecuciones.",
  "panel.pico.veces": "{n} veces más",
  "panel.pico.ver_prompt": "ver ese prompt",
  "panel.pico.ver_trazas": "Ver las trazas de ese tramo",
  "panel.pico.orden": "Ordenadas por coste, de la más cara a la más barata",
  "panel.pico.tramo": "tramo",
  "panel.pico.base": "línea base",
  "panel.pico.mediana": "mediana de los tramos con ejecuciones",
  "ev.titulo": "Prueba los arreglos de «{proyecto}» antes de desplegarlos",
  "ev.lead": "Es el segundo paso del ciclo: el Diagnóstico dice cuánto te devuelve un arreglo; aquí se comprueba, con las llamadas reales de ese paso, que el agente acierta igual con el arreglo puesto.",
  "ev.conj.titulo": "Conjuntos de casos",
  "ev.conj.lead": "Colecciones de ejecuciones {reales} de tu agente. No hay casos inventados aquí: cada uno sale de una traza que ocurrió, y se puede abrir para ver de dónde salió.",
  "ev.conj.reales": "reales",
  "ev.conj.nombre": "Nombre",
  "ev.conj.cuantas": "Cuántas trazas",
  "ev.conj.crear": "Crear desde las más recientes",
  "ev.conj.otro_filtro": "¿Quieres otro filtro? Fíltralo en {explorador} y pulsa «{guardar}»: el conjunto guarda el filtro con el que se formó, para que después se pueda discutir de dónde salió.",
  "ev.explorador": "el explorador",
  "ev.conj.ninguno": "Todavía no hay ninguno.",
  "ev.conj.col.conjunto": "Conjunto",
  "ev.conj.col.casos": "Casos",
  "ev.conj.col.filtro": "Filtro de origen",
  "ev.conj.col.creado": "Creado",
  "ev.conj.sin_filtro": "sin filtro (las más recientes)",
  "ev.borrar": "Borrar",
  "ev.tiradas": "Tiradas",
  "ev.tiradas.lead": "Cada una es una pasada de un conjunto por una versión de tu agente. Las lanza el SDK en tu proceso; aquí sólo llega el parte y las trazas.",
  "ev.col.version": "Versión",
  "ev.col.conjunto": "Conjunto",
  "ev.col.casos": "Casos",
  "ev.col.personas": "Personas",
  "ev.col.juez": "Juez",
  "ev.col.coste": "Coste",
  "ev.col.juzgar": "Juzgar costó",
  "ev.col.cuando": "Cuándo",
  "ev.sin_tiradas": "¿Sin tiradas de una versión nueva? Lánzala con {codigo} apuntando a este mismo Laplace. Las trazas que genere se ven en {explorador} como cualquier otra, y el proyecto es «{proyecto}».",
  "ev.entre": "entre {bajo} y {alto}",
  "ev.error.comparar": "no se ha podido comparar",
  "ev.paso1": "Guarda un conjunto de casos",
  "ev.paso1.texto": "Ejecuciones reales de tu agente. Desde {explorador}, filtra y pulsa «{guardar}», o créalo aquí abajo con las más recientes.",
  "ev.paso2": "Lánzalo con la versión actual",
  "ev.paso2.texto": "La tirada la lanza el SDK en tu proceso (Laplace no ejecuta tu agente):",
  "ev.paso3": "Y otra vez con la versión nueva",
  "ev.paso3.texto": "Otro prompt, otro modelo: la misma línea con otro {variant}. Con las dos tiradas, aquí aparece la comparación de acierto y coste. El acierto sale de tus anotaciones o del juez automático.",
  "ev.comparar.titulo": "Comparar dos versiones",
  "ev.comparar.pasos": "Tres pasos, y cada uno se marca solo cuando está hecho.",
  "ev.comparar.lead": "Acierto y coste a la vez. Las dos tiradas tienen que ser del mismo conjunto: comparar el acierto sobre casos distintos no diría nada.",
  "ev.a": "A — la de referencia",
  "ev.b": "B — la nueva",
  "ev.elige": "Elige una tirada",
  "ev.elige_a": "Elige A primero",
  "ev.n_casos": "{n} casos",
  "ev.comparando": "Comparando…",
  "ev.comparar": "Comparar",
  "ev.discrepan": "Las personas y el juez no dicen lo mismo.",
  "ev.discrepan.texto": "No es un fallo del producto: es el dato más interesante que puede darte esta pantalla. O el juez está midiendo otra cosa, o quien anotó y quien escribió el prompt del juez no entienden igual «bien». Mira los casos antes de fiarte de ninguno de los dos.",
  "ev.costo": "Lo que costó cada una",
  "ev.costo.lead": "Esto no lleva margen: no es una muestra, es la factura de lo que se ejecutó. Si gestionas tus prompts en Laplace, debajo de cada lado verás {enlace}, leída de las trazas y no de la etiqueta que le pusiste a la tirada.",
  "ev.costo.enlace": "con qué versión corrió",
  "ev.juzgar_dos": "Juzgar las dos tiradas con {modelo}",
  "ev.cuesta": "Cuesta dinero: se te dirá cuánto en cuanto termine",
  "ev.tec.conjunto": "conjunto",
  "ev.tec.casos": "casos",
  "ev.fuente.personas": "Personas",
  "ev.fuente.juez": "Juez (modelo)",
  "ev.de": "{a} de {b}",
  "ev.sin_anotar": " · {n} sin anotar",
  "ev.wilson": "entre {bajo} y {alto} (Wilson, 95 %)",
  "ev.por_caso": "por caso",
  "ev.tec.total": "total",
  "ev.tec.tokens": "tokens",
  "ev.tec.duracion": "duración",
  "ev.tec.reventados": "reventados",
  "ev.juez_costo": "Juzgar esta tirada costó {coste} aparte{desconocido}. Es gasto nuestro, no de tu agente, y por eso va separado.",
  "ev.juez_desconocido": " (y hay veredictos cuyo coste no sabemos)",
  "pr.titulo": "Los prompts de «{proyecto}»",
  "pr.lead": "Cada versión con lo que costó y lo que acertó sobre el tráfico real que la usó, para decidir cuál dejar en producción con las dos cifras delante.",
  "pr.error.abrir": "no se ha podido abrir",
  "pr.error.version": "no se ha podido cambiar la versión",
  "pr.en_produccion": "v{n} en producción",
  "pr.cerrar": "Cerrar",
  "pr.ver_versiones": "Ver versiones y diff",
  "pr.reserva_one": "{n} ejecución corrió con el texto de reserva.",
  "pr.reserva_other": "{n} ejecuciones corrieron con el texto de reserva.",
  "pr.reserva.texto": "Quiere decir que tu agente no pudo pedirle el prompt a Laplace y usó el que lleva en el código. Ese tráfico va contado aparte, no dentro de la versión en producción: sumarlo ahí falsearía justo la cifra que estás mirando.",
  "pr.acierto.nota": "El acierto de una versión es el de las {enteras} en las que participó, no el de este prompt aislado. Una ejecución pasa por varios pasos y, cuando sale mal, nadie ha medido cuál de ellos la estropeó. Es una señal útil, no un reparto de culpas.",
  "pr.acierto.enteras": "ejecuciones enteras",
  "pr.tec.versiones": "versiones",
  "pr.tec.creado": "creado",
  "pr.col.version": "Versión",
  "pr.col.por_ejecucion": "Por ejecución",
  "pr.col.ejecuciones": "Ejecuciones",
  "pr.col.tokens": "Tokens/ejec.",
  "pr.col.ultimo": "Último uso",
  "pr.produccion": "producción",
  "pr.poner": "Poner en producción",
  "pr.ocultar_mudas": "Ocultar las versiones sin tráfico",
  "pr.ver_mudas_one": "Ver {n} versión que no corrió en este rango",
  "pr.ver_mudas_other": "Ver {n} versiones que no corrieron en este rango",
  "pr.wilson": "{bajo}–{alto} (Wilson)",
  "pr.nuevo": "Sacar un prompt del código",
  "pr.nuevo.lead": "El nombre es con el que lo pedirás: {codigo}. La primera versión se pone en producción sola; a partir de la segunda, guardar y desplegar son dos gestos.",
  "pr.nombre": "Nombre",
  "pr.nuevo.placeholder": "Eres un asistente que responde en {{idioma}} y en menos de tres frases.",
  "pr.crear": "Crear y poner en producción",
  "pr.que_cambio": "Qué cambió",
  "pr.de": "De",
  "pr.a": "A",
  "pr.elige_dos": "Elige dos versiones distintas para ver el diff. Con una sola no hay nada que comparar.",
  "pr.texto_v": "El texto de la v{n}",
  "pr.guardar_nueva": "Guardar una versión nueva",
  "pr.guardar_nueva.lead": "Guardar no despliega. Son dos gestos distintos a propósito: es lo que te deja preparar una versión con calma y lo que hace que exista el botón de volver atrás.",
  "pr.texto.placeholder": "El texto del prompt. Usa {{variable}} para lo que cambie en cada llamada.",
  "pr.guardando": "Guardando…",
  "pr.guardar": "Guardar versión",
  "pr.guardada": "Queda guardada, no servida",
  "pr.historial": "Historial de despliegues",
  "pr.col.cuando": "Cuándo",
  "pr.col.quien": "Quién",
  "pr.col.nota": "Nota",
  "pr.vuelta_atras": "vuelta atrás",
  "pr.historial.nota": "Este historial cuenta la historia; {no} atribuye picos. Para eso el {panel} usa la versión que aparece en las trazas del tramo, que es un hecho medido y no una coincidencia de horarios.",
  "pr.no": "no",
  "pr.panel": "panel",
  "pr.borrar": "Borrar este prompt",
  "pr.borrar.nota": "Las trazas no se tocan: seguirán diciendo con qué versión corrieron",
  "pr.sin_adoptar": "Todavía no gestionas ningún prompt aquí",
  "pr.sin_adoptar.1": "Tus prompts viven en tu código, que es un sitio perfectamente razonable. Lo que se pierde con eso es poder responder a «¿cuánto me costaba el de antes y cuánto acertaba?», porque un {blame} sabe qué cambió y no sabe qué pasó después.",
  "pr.sin_adoptar.2": "Si los mueves aquí, el SDK los sirve y deja escrito en cada traza con qué versión se ejecutó. {nada}: sólo te da el texto, y si Laplace no responde, el SDK usa la copia guardada o el texto de reserva que le pases.",
  "pr.sin_adoptar.nada": "Laplace sigue sin ejecutar nada tuyo",
  "pr.sin_adoptar.3": "Mientras tanto, aquí abajo está lo que sí se puede saber de tus trazas: qué pasos han cambiado de instrucciones y cuándo.",
  "pr.obs.titulo": "Lo que se ve en tus trazas",
  "pr.obs.nada": "Nada todavía.",
  "pr.obs.gestion": "Esto sale de las trazas, no de la gestión de prompts: son los juegos de instrucciones con los que se ha visto ejecutar cada paso. Sirve para ver si algo cambió por fuera de aquí.",
  "pr.obs.sin_gestion": "Cada paso de tu agente, y los juegos de instrucciones con los que se le ha visto ejecutar en este rango. Si un paso cambia de instrucciones entre una ejecución y otra, es un cambio de prompt: no sabemos el texto entero (sólo guardamos el principio), pero sí cuándo cambió y qué costó.",
  "pr.obs.cambio": "¿Ves un cambio que no reconoces? {enlace} y mira las instrucciones completas de esas ejecuciones.",
  "pr.obs.abrir": "Ábrelo en el explorador",
  "pr.obs.no_versiones": "no son versiones",
  "pr.obs.llamadas": "llamadas en cada ejecución",
  "pr.obs.juego_one": "juego de instrucciones",
  "pr.obs.juego_other": "juegos de instrucciones",
  "pr.obs.col.instrucciones": "Instrucciones (principio)",
  "pr.obs.col.desde": "Desde",
  "pr.obs.col.hasta": "Hasta",
  "pr.obs.sin_instrucciones": "(sin instrucciones capturadas)",
  "comun.guardar": "Guardar",
  "comun.quitar": "Quitar",
  "aj.titulo": "Ajustes de «{proyecto}»",
  "aj.lead": "Presupuesto, avisos, tarifas y datos. Cada bloque se guarda por su cuenta.",
  "aj.solo_lectura": "Presupuesto, alertas y borrar el proyecto los cambia un admin de la organización. Tu rol ({rol}) permite verlos.",
  "aj.pres.guardado": "Presupuesto guardado.",
  "aj.pres.quitado": "Presupuesto quitado.",
  "aj.pres.titulo": "Presupuesto mensual",
  "aj.pres.lead": "Sobre el mes natural, que es el que factura el proveedor. Avisa al 80 % y al 100 % por los canales de abajo, una vez cada uno por mes.",
  "aj.pres.dolares": "Dólares al mes",
  "aj.control.titulo": "Tope y parada",
  "aj.control.lead": "Límites para cada ejecución del agente, que el SDK pide cada 30 segundos y aplica como laplace.guard. Se suman a los del código y manda el más estricto.",
  "aj.control.en_marcha": "Los agentes del proyecto están en marcha.",
  "aj.control.parado": "Parado desde {cuando}: ninguna llamada al modelo ni ningún paso se ejecuta hasta que se reanude.",
  "aj.control.parar": "Parar todo",
  "aj.control.reanudar": "Reanudar",
  "aj.control.parado_ok": "Parado. Los agentes se enteran en 30 segundos como mucho.",
  "aj.control.reanudado": "Reanudado. Las ejecuciones nuevas vuelven a funcionar; las que se pararon, no siguen.",
  "aj.control.tope": "Dólares por ejecución",
  "aj.control.bucles": "Vueltas sin avanzar",
  "aj.control.guardado": "Límites guardados. Los agentes los aplican en 30 segundos como mucho.",
  "aj.control.como": "Una ejecución es un laplace.guard del código o, si no lo hay, el paso de @observe más externo. Si Laplace no responde, el SDK sigue con lo último que recibió; si nunca recibió nada, el agente sigue sin límites.",
  "aj.control.tope_invalido": "El tope tiene que ser mayor que cero.",
  "aj.control.bucles_invalido": "Las vueltas tienen que ser un número entero de 2 o más.",
  "aj.error.borrar": "no se ha podido borrar",
  "aj.datos": "Datos",
  "aj.datos.retencion": "Esta instalación guarda las trazas {n} días; lo anterior se borra solo cada día.",
  "aj.datos.siempre": "Esta instalación guarda las trazas para siempre. Para borrar lo antiguo de forma automática, arráncala con LAPLACE_RETENTION_DAYS.",
  "aj.ret.dias": "Días que guarda este proyecto",
  "aj.ret.guardado": "Guardado: este proyecto guarda {n} días; lo anterior se borra una vez al día.",
  "aj.ret.quitado": "Quitado: este proyecto guarda lo que diga la instalación.",
  "aj.ret.explica": "Cada proyecto puede guardar menos que la instalación, no más. Lo anterior se borra una vez al día.",
  "aj.ret.manda_instalacion": "La instalación guarda {n} días y manda la más corta: este proyecto guarda {n}.",
  "aj.sujeto.titulo": "Borrar lo de una persona o un cliente.",
  "aj.sujeto.texto": "Se llevan las trazas enteras en las que aparece su id, no sólo los pasos que lo llevan. No se puede deshacer. Repite el id para confirmarlo.",
  "aj.sujeto.tipo": "Qué se borra",
  "aj.sujeto.persona": "Una persona (user_id)",
  "aj.sujeto.cliente": "Un cliente (customer_id)",
  "aj.sujeto.id": "Id de la persona o del cliente",
  "aj.sujeto.repite": "Repite el id",
  "aj.sujeto.boton": "Borrar sus trazas",
  "aj.sujeto.borrado": "Borradas {n} trazas de «{id}».",
  "aj.borrar.titulo": "Borrar «{proyecto}» entero.",
  "aj.borrar.texto": "Trazas, anotaciones, conjuntos de casos, prompts, presupuesto y alertas. No se puede deshacer. Escribe el nombre del proyecto para confirmarlo.",
  "aj.borrar.aria": "Nombre del proyecto para confirmar",
  "aj.borrar.boton": "Borrar el proyecto",
  "aj.apariencia": "Apariencia",
  "aj.en_navegador": "Se guarda en este navegador.",
  "aj.tema": "Tema",
  "aj.tema.sistema": "Como el sistema",
  "aj.tema.claro": "Claro",
  "aj.tema.oscuro": "Oscuro",
  "aj.euros": "Ver también en euros",
  "aj.euros.lead": "Los proveedores facturan en dólares y ésa sigue siendo la cifra. Si pones un tipo de cambio, al lado de los importes principales aparece el equivalente en euros con «≈». El tipo lo pones tú y se guarda sólo en este navegador: no lo descargamos de ninguna parte.",
  "aj.euros.tipo": "1 $ son … €",
  "aj.euros.guardado": "Tipo guardado.",
  "aj.euros.desactivados": "Euros desactivados.",
  "aj.tar.guardada": "Tarifa de {modelo} guardada. {n} llamadas ya guardadas tienen ahora su coste.",
  "aj.tar.quitada": "Tarifa de {modelo} quitada.",
  "aj.error.quitar": "no se ha podido quitar",
  "aj.tar.titulo": "Tarifas propias",
  "aj.tar.lead": "Para un modelo que no está en nuestra tabla, o uno con precio negociado. En dólares por millón de tokens, de la página del proveedor. Al guardarla se recalcula también lo que ya habías enviado. Si el modelo corre en tu máquina, no le pongas precio: no te cobra nadie.",
  "aj.tar.instalacion": "Las tarifas valen para toda la instalación: sólo las puede cambiar una clave de instalación.",
  "aj.tar.sin_tarifa": "Sin tarifa ahora mismo:",
  "aj.tar.modelo": "Modelo",
  "aj.tar.entrada": "Entrada",
  "aj.tar.salida": "Salida",
  "aj.tar.entrada_m": "Entrada ($/M)",
  "aj.tar.salida_m": "Salida ($/M)",
  "aj.tar.guardar": "Guardar tarifa",
  "aj.al.prueba_ok": "Mensaje de prueba enviado. Míralo en el canal.",
  "aj.al.prueba_mal": "No ha llegado por ningún canal. Revisa las direcciones.",
  "aj.al.error.probar": "no se ha podido probar",
  "aj.al.titulo": "Alertas",
  "aj.al.lead": "Un mensaje cuando un problema pasa del umbral en dinero ya gastado. Nunca se repite el mismo aviso dentro del periodo de calma, y lo que marques como arreglado o ignorado no avisa.",
  "aj.al.silenciadas": "Silenciadas para este proyecto.",
  "aj.al.activas": "Activas.",
  "aj.al.apagadas": "Apagadas: pon al menos un canal.",
  "aj.al.slack_guardado": "Webhook de Slack guardado.",
  "aj.al.slack_quitado": "Slack quitado.",
  "aj.al.webhook_titulo": "Webhook (Teams, Discord, n8n…)",
  "aj.al.webhook_guardado": "Webhook guardado.",
  "aj.al.webhook_quitado": "Webhook quitado.",
  "aj.al.correo": "Correo",
  "aj.al.correo_placeholder": "equipo@empresa.com",
  "aj.al.correo_guardado": "Correo guardado.",
  "aj.al.correo_quitado": "Correo quitado.",
  "aj.al.smtp": "Falta el servidor de correo de la instalación: arranca Laplace con LAPLACE_SMTP_HOST, LAPLACE_SMTP_USER y LAPLACE_SMTP_PASSWORD.",
  "aj.al.umbral": "Umbral (dólares ya gastados)",
  "aj.al.calma": "Calma por problema (horas)",
  "aj.al.umbral_guardado": "Umbral y calma guardados.",
  "aj.al.que_avisa": "Qué avisa",
  "aj.al.reglas_guardadas": "Reglas guardadas.",
  "aj.al.probar": "Enviar un mensaje de prueba",
  "aj.al.reactivadas": "Alertas reactivadas.",
  "aj.al.silenciadas_ok": "Alertas silenciadas.",
  "aj.al.reactivar": "Reactivar",
  "aj.al.silenciar": "Silenciar este proyecto",
  "aj.al.puesto": " · puesto ({actual})",
  "aj.al.otro": "Pega otro para cambiarlo",
  "aj.regla.repeticion": "Repeticiones",
  "aj.regla.bucle": "Bucles",
  "aj.regla.modelo_caro": "Modelo caro",
  "aj.regla.contexto_fijo": "Contexto sin caché",
  "titulo.ajustes": "Ajustes",
  "titulo.configurar": "Configurar",
  "titulo.entrar": "Entrar",
  "titulo.evaluaciones": "Probar",
  "titulo.invitacion": "Invitación",
  "titulo.organizacion": "Organización",
  "titulo.panel": "Panel",
  "titulo.problema": "Problema",
  "titulo.prompts": "Prompts",
  "titulo.traza": "Traza",
  "titulo.trazas": "Trazas",
  "rol.lector": "lector",
  "rol.miembro": "miembro",
  "rol.admin": "admin",
  "rol.propietario": "propietario",
  "org.error.cargar": "no se ha podido cargar",
  "org.local.titulo": "El modo local no tiene cuentas",
  "org.local.texto": "Es un proceso en tu máquina con tus trazas: no hay nadie más a quien darle acceso. Las cuentas, los roles y las claves existen en la instalación de nube.",
  "org.tu_cuenta": "Tu cuenta",
  "org.eres": "Eres {rol} de esta organización.",
  "org.sin_org": "No perteneces a ninguna organización todavía: pide una invitación.",
  "org.org": "Organización",
  "org.miembros": "Miembros",
  "org.col.persona": "Persona",
  "org.col.rol": "Rol",
  "org.col.desde": "Desde",
  "org.tu": " · tú",
  "org.rol_de": "Rol de {email}",
  "org.ahora_es": "{email} ahora es {rol}.",
  "org.salir_confirm": "¿Salir de la organización?",
  "org.quitar_confirm": "¿Quitar a {email}?",
  "org.hecho": "Hecho.",
  "org.salir": "Salir",
  "org.roles.nota": "Lector: ve. Miembro: además anota ejecuciones, marca problemas y gestiona prompts y conjuntos. Admin: además miembros, claves, alertas, presupuesto y borrar. Quitar a alguien cierra sus sesiones al momento.",
  "org.invitar": "Invitar",
  "org.email": "Email",
  "org.email_placeholder": "persona@empresa.com",
  "org.enviado": "Le hemos mandado el enlace por correo. También puedes copiarlo:",
  "org.sin_correo": "Esta instalación no tiene correo configurado: mándale tú este enlace. Sólo se enseña ahora, y caduca en 7 días.",
  "org.pendientes": "Pendientes",
  "org.caduca": "caduca el {fecha}",
  "org.anulada": "Invitación anulada.",
  "org.anular": "Anular",
  "org.acc.configurar_instalacion": "configuró la instalación",
  "org.acc.login": "entró",
  "org.acc.login_fallido": "intento de entrada fallido",
  "org.acc.invitar": "invitó a",
  "org.acc.anular_invitacion": "anuló la invitación de",
  "org.acc.aceptar_invitacion": "aceptó la invitación como",
  "org.acc.cambiar_rol": "cambió el rol de",
  "org.acc.quitar_miembro": "quitó a",
  "org.acc.crear_clave": "creó una clave para",
  "org.acc.revocar_clave": "revocó la clave",
  "org.acc.borrar_proyecto": "borró el proyecto",
  "org.acc.parar_proyecto": "paró los agentes del proyecto",
  "org.acc.reanudar_proyecto": "reanudó los agentes del proyecto",
  "ent.sso": "Entrar con SSO",
  "ent.sso_error.estado": "El inicio de sesión caducó o empezó en otro navegador. Vuelve a probar.",
  "ent.sso_error.cancelado": "El proveedor de identidad no completó el inicio de sesión.",
  "ent.sso_error.token": "La respuesta del proveedor no cuadra (emisor, cliente, caducidad o nonce). Avisa a quien lo administra.",
  "ent.sso_error.correo": "El proveedor no manda un correo verificado.",
  "ent.sso_error.dominio": "Ese correo no es de un dominio de la organización.",
  "ent.sso_error.proveedor": "El proveedor de identidad no responde.",
  "ent.sso_error.sin_invitacion": "Ya tienes cuenta con ese correo, pero no en esta organización: pide una invitación y luego entra con SSO.",
  "ent.sso_error.fuera": "Ya no eres de esa organización.",
  "ent.sso_error.otro": "No se pudo entrar con SSO.",
  "verif.ok": "Correo verificado",
  "verif.mal": "No se pudo verificar",
  "verif.sin_token": "Al enlace le falta el código.",
  "verif.seguir": "Ir a Laplace",
  "sso.titulo": "Inicio de sesión único (SSO) y SCIM",
  "sso.explica": "Tu gente entra con el proveedor de identidad de la organización (OpenID Connect: Okta, Entra ID, Google Workspace…), y el proveedor la da de alta y de baja por SCIM.",
  "sso.dominios": "Dominios de correo",
  "sso.guardar_dominios": "Guardar dominios",
  "sso.dominios_quien": "Los pone quien administra la instalación: dicen de quién son esos correos.",
  "sso.emisor": "Emisor (issuer)",
  "sso.cliente": "ID de cliente",
  "sso.secreto": "Secreto de cliente",
  "sso.secreto_guardado": "guardado; déjalo vacío para conservarlo",
  "sso.rol": "Rol de quien entra por primera vez",
  "sso.obligar": "Obligar a entrar por SSO con los correos de estos dominios",
  "sso.guardar": "Guardar SSO",
  "sso.guardado": "Guardado.",
  "sso.quitar": "Quitar SSO",
  "sso.quitado": "SSO quitado.",
  "sso.redireccion": "URL de redirección que hay que registrar en el proveedor:",
  "sso.scim": "SCIM",
  "sso.scim_explica": "URL base de SCIM 2.0 para el proveedor, con una clave de esta organización como Bearer:",
  "sso.scim_token": "Clave creada el {fecha}",
  "sso.scim_usado": "usada el {fecha}",
  "sso.scim_revocar": "Revocar",
  "sso.scim_revocado": "Clave revocada.",
  "sso.scim_crear": "Crear clave de SCIM",
  "sso.scim_una_vez": "Cópiala ahora: no se vuelve a enseñar.",
  "org.sin_verificar": "Tu correo no está verificado: Laplace no manda invitaciones en tu nombre hasta que lo esté.",
  "org.sin_verificar_sin_correo": "Tu correo no está verificado, y esta instalación no tiene servidor de correo para hacerlo.",
  "org.verificar": "Mandar el enlace",
  "org.verificacion_enviada": "Enlace enviado: mira tu correo.",
  "org.acc.login_sso": "entró por SSO",
  "org.acc.sso_rechazado": "no pudo entrar por SSO",
  "org.acc.configurar_sso": "configuró el SSO",
  "org.acc.quitar_sso": "quitó el SSO",
  "org.acc.dominios_sso": "puso los dominios",
  "org.acc.crear_token_scim": "creó una clave de SCIM",
  "org.acc.revocar_token_scim": "revocó una clave de SCIM",
  "org.acc.scim_alta": "dio de alta por SCIM a",
  "org.acc.scim_baja": "dio de baja por SCIM a",
  "org.acc.scim_activar": "reactivó por SCIM a",
  "org.acc.scim_desactivar": "desactivó por SCIM a",
  "org.registro": "Registro de actividad",
  "org.cargando": "Cargando…",
  "org.nada": "Nada todavía.",
  "org.alguien": "alguien",
  "org.admin_instalacion": " · administras esta instalación",
  "org.pass_actual": "Contraseña actual",
  "org.pass_nueva": "Nueva (10 caracteres o más)",
  "org.pass_cambiada": "Contraseña cambiada. Las demás sesiones se han cerrado.",
  "org.pass_cambiar": "Cambiar contraseña",
  "org.cerrar_todo": "Cerrar sesión en todos los dispositivos",
  "org.error.generico": "no se ha podido",
  "cla.titulo": "Claves de API",
  "cla.lead": "Una clave por proyecto: es con lo que tu agente manda trazas. Escribe un nombre de proyecto nuevo para crearlo.",
  "cla.proyecto": "Proyecto",
  "cla.para_que": "Para qué es",
  "cla.para_que_placeholder": "ingesta producción",
  "cla.caduca": "Caduca",
  "cla.nunca": "nunca",
  "cla.30": "en 30 días",
  "cla.90": "en 90 días",
  "cla.365": "en un año",
  "cla.crear": "Crear clave",
  "cla.copiala": "Cópiala ahora:",
  "cla.copiala.texto": "sólo se guarda su huella y no se puede volver a ver. Si la pierdes, revócala y crea otra.",
  "cla.col.nombre": "Nombre",
  "cla.col.ultimo": "Último uso",
  "cla.no_caduca": "no caduca",
  "cla.revocar_confirm": "¿Revocar «{nombre}»? Deja de servir al momento.",
  "cla.revocada": "Clave revocada.",
  "cla.revocar": "Revocar",
  "cla.rotar": "Para rotar una clave: crea la nueva, cámbiala en tu agente y revoca la vieja.",
  "cla.copiado": "Copiado",
  "cla.copiar": "Copiar",
  "ent.error": "no se ha podido entrar",
  "ent.titulo": "Entrar en Laplace",
  "ent.contrasena": "Contraseña",
  "ent.entrando": "Entrando…",
  "ent.entrar": "Entrar",
  "ent.sin_cuenta": "¿No tienes cuenta? Pide una invitación a quien administra tu organización.",
  "ent.tengo_clave": "Tengo una clave de API",
  "ent.comprobando": "Comprobando…",
  "ent.usar_clave": "Usar la clave",
  "conf.error": "no se ha podido configurar",
  "conf.titulo": "Configura esta instalación",
  "conf.texto": "Todavía no hay ninguna cuenta. La primera administra la instalación entera y se queda con los proyectos que ya tengan datos.",
  "conf.codigo": "Código de configuración",
  "conf.codigo.ayuda": "Está en el log del servidor, en la línea «no hay ninguna cuenta todavía». Con Docker: {comando}",
  "conf.org": "Nombre de tu organización",
  "conf.org_placeholder": "Mi empresa",
  "conf.nombre": "Tu nombre",
  "conf.contrasena": "Contraseña (10 caracteres o más)",
  "conf.creando": "Creando…",
  "conf.crear": "Crear la cuenta de administración",
  "inv.puede.lector": "ver los datos de sus proyectos",
  "inv.puede.miembro": "ver, anotar ejecuciones, marcar problemas y gestionar prompts",
  "inv.puede.admin": "todo lo anterior, más miembros, claves, alertas y presupuesto",
  "inv.puede.propietario": "todo, incluido hacer y deshacer propietarios",
  "inv.no_vale": "esa invitación no vale",
  "inv.error": "no se ha podido aceptar",
  "inv.no_vale.titulo": "Esta invitación no vale",
  "inv.no_vale.texto": "{motivo}. Las invitaciones caducan a los siete días y sólo sirven una vez: pide otra a quien te invitó.",
  "inv.unete": "Únete a «{org}»",
  "inv.como": "Como {rol}: podrás {puede}.",
  "inv.con_cuenta": "Ya tienes cuenta con este email: tu contraseña",
  "inv.elige": "Elige una contraseña (10 caracteres o más)",
  "inv.uniendote": "Uniéndote…",
  "inv.aceptar": "Aceptar la invitación",
  "nf.titulo": "Esta página no existe",
  "nf.texto": "El enlace puede estar mal, o apuntar a algo que ya no está.",
  "nf.ir": "Ir al diagnóstico",
  "err.titulo": "Algo ha fallado al cargar esta pantalla",
  "err.texto": "No hemos podido preparar los datos. Suele ser cosa de un momento: vuelve a intentarlo y, si sigue igual, revisa que el backend esté en pie.",
  "prob.paso_titulo": "{titulo}.",
  // Errores de la API que no traen una frase propia.
  "api.fallo": "Error {estado} en {ruta}",
  "api.no_valida": "La petición no es válida: {campos}",
  // A1: un rango vacío no es un proyecto vacío.
  "estado.rango_vacio.titulo": "No hay ejecuciones en {ventana}",
  "estado.rango_vacio.ultima": "La última llegó el {fecha}.",
  "estado.rango_vacio.fuera": "La última llegó el {fecha}, antes de los {rango} que se pueden mirar aquí. Lanza tu agente con Laplace activado para ver datos nuevos.",
  "estado.rango_vacio.boton": "Ver {ventana}",
  // Menos texto (D-151): el héroe, el distintivo de confianza y la ficha.
  "diag.puedes.proy": "Puedes dejar de pagar hasta",
  "diag.puedes.al_mes": "al mes",
  "diag.puedes.gastado": "Te habrías ahorrado hasta",
  "diag.puedes.en": "en {tiempo}",
  "diag.de_total.proy": "de los {total} que te costará este mes, al ritmo de {ventana}.",
  "diag.de_total.gastado": "de los {total} gastados en {tiempo} de datos.",
  "conf.alta": "Confianza alta",
  "conf.media": "Confianza media",
  "conf.baja": "Confianza baja",
  "conf.notas_one": "{n} nota",
  "conf.notas_other": "{n} notas",
  "conf.alta.texto": "Todo el gasto tiene tarifa conocida y la parte evitable no es desproporcionada.",
  "conf.media.texto": "La cifra es fiable pero hay que leerla con estas notas.",
  "conf.baja.texto": "Falta parte del gasto o no podemos ver bien este agente: no tomes la cifra como definitiva.",
  "prob.por_que.plegado": "¿Por qué pasa?",
  "prob.ahorro.como": "¿Cómo se calcula?",
  // Gráficos del Diagnóstico (D-152).
  "graf.titulo": "Dónde se va el dinero",
  "graf.dia": "Gasto por día",
  "graf.hora": "Gasto por hora",
  "graf.real": "trabajo real",
  "graf.evitable": "evitable",
  "graf.punto": "{fecha}: {coste}, de ellos {evitable} evitables",
  "graf.aria": "Gasto por tramo con la parte evitable encima",
  "graf.reparto": "¿Cómo se reparte lo evitable por días?",
  "graf.reparto.texto": "Lo evitable se mide sobre todo el rango, no día a día. Aquí se reparte en proporción a lo que gastó cada día el paso de cada problema: los días suman la cifra de arriba, y un día en que ese paso no trabajó no recibe nada.",
  "graf.sin_repartir": "{coste} evitables no se han podido repartir: su paso no tiene gasto con tarifa en este rango.",
  "graf.pasos": "Coste por paso",
  "graf.otros": "Otros pasos",
  "graf.paso.evitable": "{evitable} evitables",
  // Textos que pinta el CSS (`content:`): el proveedor de idioma los pasa como variables.
  "css.porque": "¿por qué?",
  "css.avanzado": "avanzado",
  // El grafo del agente en la vista de traza (D-153).
  "grafo.titulo": "Cómo está hecho el agente",
  "grafo.lead": "Un bloque por paso y una flecha por cada paso que llama a otro, con cuántas veces lo hizo en esta ejecución.",
  "grafo.aria": "Grafo del agente con {pasos} pasos",
  "grafo.llamadas_one": "{n} llamada",
  "grafo.llamadas_other": "{n} llamadas",
  "grafo.errores_one": "{n} con error",
  "grafo.errores_other": "{n} con error",
  "grafo.tipo.agent": "agente",
  "grafo.tipo.llm": "modelo",
  "grafo.tipo.tool": "herramienta",
  "grafo.tipo.retrieval": "búsqueda",
  "grafo.tipo.chain": "paso",
  "grafo.tipo.otro": "otro",
  "grafo.sin_tarifa": "sin tarifa",
  "grafo.al_menos": "≥ {coste}",
  "grafo.aprox": "≈ {coste}",
  "grafo.proyecto.titulo": "El agente entero",
  "grafo.proyecto.lead_one": "Todas las ejecuciones de los últimos {dias} días sumadas ({n} traza, sin tiradas de evaluación). Cada flecha dice cuántas veces un paso llamó a otro y lo que costaron esas llamadas.",
  "grafo.proyecto.lead_other": "Todas las ejecuciones de los últimos {dias} días sumadas ({n} trazas, sin tiradas de evaluación). Cada flecha dice cuántas veces un paso llamó a otro y lo que costaron esas llamadas.",
  "grafo.proyecto.fuera": "Hay {pasos} pasos más, con {llamadas} llamadas, que no se dibujan: aquí salen los más llamados.",
  "aj.regla.prompt_caro": "Prompt más caro",
  "aj.regla.cache_compartida": "Caché sin compartir",
  "diag.ahorrado_one": "Ya has dejado de pagar {coste} desde que arreglaste un problema.",
  "diag.ahorrado_other": "Ya has dejado de pagar {coste} desde que arreglaste {n} problemas.",
  "diag.ahorrado.suelo": "al menos {coste}",
  "ciclo.titulo": "Dónde está este problema",
  "ciclo.detectar": "Detectar",
  "ciclo.probar": "Probar",
  "ciclo.arreglar": "Arreglar",
  "ciclo.verificar": "Verificar",
  "ciclo.estado.hecho": "hecho",
  "ciclo.estado.en_curso": "en curso",
  "ciclo.estado.pendiente": "pendiente",
  "ciclo.estado.fallo": "no ha funcionado",
  "ciclo.detectar.hecho": "Lo hemos encontrado en tus trazas.",
  "ciclo.probar.pendiente": "Prueba el arreglo con sus llamadas reales antes de cambiar nada.",
  "ciclo.probar.conjunto": "Sus ejecuciones están guardadas en «{nombre}»; falta lanzar la prueba.",
  "ciclo.probar.hecho_one": "{n} tirada sobre «{nombre}».",
  "ciclo.probar.hecho_other": "{n} tiradas sobre «{nombre}».",
  "ciclo.probar.sin_paso": "Este problema no es de un solo paso: se prueba desde el agente entero.",
  "ciclo.arreglar.pendiente": "Aplica el arreglo y márcalo aquí.",
  "ciclo.arreglar.hecho": "Marcado como arreglado el {fecha}.",
  "ciclo.verificar.pendiente": "Lo comprobamos solo cuando haya ejecuciones después del arreglo.",
  "ciclo.ignorado": "Lo has ignorado: el ciclo se para aquí.",
  "seg.probar.texto.prompt": "La diferencia de coste está medida; que la v{a} acierte igual que la v{b}, no. Guarda las ejecuciones reales de este paso como conjunto de casos y lánzalas con cada versión: Probar te dirá cuál acierta más y cuánto cuesta cada una.",
  "seg.probar.texto.otro": "El ahorro está medido; que el agente arreglado responda igual, no. Guarda las ejecuciones reales de este paso como conjunto de casos y lánzalas con el arreglo puesto: Probar te dirá si acierta igual y cuánto cuesta menos.",
  "seg.probar.existe": "Ya están guardadas: «{nombre}», {n} casos.",
  "seg.probar.arreglado": "arreglado",
  "prob.prompt.titulo": "Vuelve a la v{a} desde Prompts",
  "prob.prompt.texto": "La ficha de «{prompt}» enseña las dos versiones con lo que cuesta y acierta cada una, y pone la v{a} en producción con un clic.",
  "prob.prompt.ir": "Abrir «{prompt}» en Prompts →",
  "pr.hallazgo": "Sale en el Diagnóstico: {titulo}.",
  "pr.hallazgo.ver": "Ver el problema →",
  "ev.por_probar.titulo": "Arreglos por probar",
  "ev.por_probar.lead": "Los problemas abiertos del Diagnóstico, con lo que te devuelven y si ya tienen su prueba. Guardar sus ejecuciones crea el conjunto con las llamadas reales de ese paso.",
  "ev.por_probar.sin_probar": "sin probar",
  "ev.por_probar.guardado": "guardado, sin tirada",
  "ev.por_probar.probado_one": "{n} tirada",
  "ev.por_probar.probado_other": "{n} tiradas",
  "ev.por_probar.guardar": "Guardar sus ejecuciones",
  "ev.por_probar.guardado_como": "Guardado como «{nombre}». Lánzalo con el arreglo puesto:",
  "ev.por_probar.ver": "Ver el problema",
  "ev.por_probar.error": "no se ha podido guardar",
  "aj.contraste.alto": "Alto contraste",
  "aj.contraste.texto": "Fondos opacos, sin transparencias ni desenfoque, y letra al máximo contraste. Vale para el tema claro y para el oscuro.",
  "arbol.envoltorio": "Lo mismo que «{hijo}», que va dentro: este paso sólo lo envuelve.",
  "nav.clientes": "Clientes",
  "titulo.clientes": "Clientes",
  "cl.titulo": "Margen por cliente de «{proyecto}»",
  "cl.lead": "Lo que te paga cada cliente frente a lo que te cuesta su trabajo, al mes. El coste sale de sus ejecuciones; lo que paga lo pones tú.",
  "cl.aviso_one": "Este cliente te hace perder dinero",
  "cl.aviso_other": "Estos {n} clientes te hacen perder dinero",
  "cl.aviso.texto": "Su trabajo te cuesta más de lo que te paga. Mira qué problemas del Diagnóstico pasan en sus ejecuciones, o revisa su precio.",
  "cl.h.cliente": "Cliente",
  "cl.h.ejecuciones": "Ejecuciones",
  "cl.h.coste": "Coste al mes",
  "cl.h.ingresos": "Paga al mes",
  "cl.h.margen": "Margen al mes",
  "cl.estado.pierde": "pierde dinero",
  "cl.estado.ajustado": "margen ajustado",
  "cl.estado.gana": "deja margen",
  "cl.estado.sin-ingresos": "sin ingresos",
  "cl.estado.sin-proyeccion": "pocos datos",
  "cl.estado.sin-trafico": "sin ejecuciones",
  "cl.h.evitable": "Evitable",
  "cl.estado.sin-cambio": "falta el tipo de cambio",
  "cl.moneda": "Moneda",
  "cl.moneda.aria": "Moneda de lo que paga {cliente}",
  "cl.suyo": "{dinero} suyos",
  "cl.cambio.titulo": "Tipos de cambio",
  "cl.cambio.lead": "Para los clientes que pagan en otra moneda: cuántos dólares vale una unidad. Los pones tú; no usamos un tipo que no hayas puesto.",
  "cl.cambio.tipo": "1 {moneda} = … US$",
  "cl.cambio.anadir": "Añadir moneda",
  "cl.cambio.guardado": "Tipos de cambio guardados.",
  "cl.ingresos.aria": "Lo que paga {cliente} al mes, en dólares",
  "cl.guardar": "Guardar",
  "cl.error.guardar": "no se ha podido guardar",
  "cl.sin_cliente": "{coste} de {n} ejecuciones no dicen de qué cliente son: se cuentan aparte, sin repartirlas.",
  "cl.como.titulo": "Cómo decir de qué cliente es cada ejecución",
  "cl.como.texto": "Una línea antes de que el agente trabaje para ese cliente. Las tiradas de evaluación no cuentan: no son trabajo de ningún cliente.",
  "cl.anadir": "Poner lo que paga un cliente que todavía no ha llegado",
  "cl.anadir.id": "Cliente",
  "cl.anadir.importe": "Paga al mes ($)",
  "diag.clientes": "Clientes",
  "diag.clientes.pierden_one": "{n} cliente te hace perder dinero.",
  "diag.clientes.pierden_other": "{n} clientes te hacen perder dinero.",
  "diag.clientes.ver": "Ver el margen por cliente",
  "trazas.filtro.cliente": "Sólo las ejecuciones del cliente {cliente}",
  "cl.problemas": "Pasa en sus ejecuciones:",
  "cl.ver_ejecuciones": "Ver sus ejecuciones →",
  "aj.regla.cliente_pierde": "Cliente que pierde dinero",
  "cl.stripe.titulo": "Ingresos desde Stripe",
  "cl.stripe.lead": "En lugar de escribirlos: lo que paga cada cliente sale de sus facturas pagadas del último mes, llevado a un mes (un plan anual cuenta su doceava parte). Cada cliente de Stripe se casa con el de tus trazas por metadata.laplace_customer_id, o por su id. Basta una clave restringida con lectura de facturas y clientes.",
  "cl.stripe.clave": "Clave de Stripe",
  "cl.stripe.puesta": "Clave puesta ({pista}).",
  "cl.stripe.ultima": "Última vez: {fecha}, {n} clientes.",
  "cl.stripe.nunca": "Todavía no se ha traído nada.",
  "cl.stripe.traer": "Traer de Stripe",
  "cl.stripe.quitar": "Quitar la clave",
  "cl.stripe.fuente": "Stripe",
  // Bot de pull requests (D-185).
  "aj.gh.titulo": "Pull requests en GitHub",
  "aj.gh.lead": "Laplace puede proponer el arreglo de un problema como pull request en tu repositorio: hoy, cambiar de modelo en la llamada exacta. Nunca escribe en la rama principal; fusionar es cosa tuya.",
  "aj.gh.puesto_app": "Conectado a {repo} con la GitHub App (instalación {n}).",
  "aj.gh.puesto_token": "Conectado a {repo} con un token ({pista}).",
  "aj.gh.repo": "Repositorio (dueño/nombre)",
  "aj.gh.rama": "Rama base (vacía: la principal)",
  "aj.gh.instalacion": "Número de instalación de la GitHub App",
  "aj.gh.token": "Token con permiso de contenido y pull requests",
  "aj.gh.guardar": "Guardar",
  "aj.gh.quitar": "Desconectar",
  "aj.gh.guardado": "Guardado.",
  "aj.gh.quitado": "Desconectado. El token se ha borrado.",
  "aj.gh.error": "No se ha podido guardar.",
  "prob.pr.titulo": "Proponerlo en el código",
  "prob.pr.lead": "Un pull request que cambia {de} por {a} en la llamada de este paso. Lo revisas y lo fusionas tú.",
  "prob.pr.conectar": "Conecta un repositorio de GitHub en Ajustes para proponerlo.",
  "prob.pr.abierto": "Pull request abierto: ábrelo en GitHub",
  "prob.pr.abrir": "Abrir pull request en {repo}",
  "prob.pr.error": "No se ha podido abrir el pull request.",
} as const;

export type Clave = keyof typeof es;
export type Mensajes = Record<Clave, string>;
