import type { Mensajes } from "./es";

// Les espaces avant « : ; ? ! » sont insécables (U+00A0), comme le veut la typographie.
export const fr: Mensajes = {
  "tiempo.dias_one": "{n} jour",
  "tiempo.dias_other": "{n} jours",
  "tiempo.horas_one": "{n} heure",
  "tiempo.horas_other": "{n} heures",
  "tiempo.minutos_one": "{n} minute",
  "tiempo.minutos_other": "{n} minutes",
  "tiempo.menos_de_un_minuto": "moins d’une minute",
  "ventana.dias_one": "le dernier jour",
  "ventana.dias_other": "les {n} derniers jours",
  "ventana.horas_one": "la dernière heure",
  "ventana.horas_other": "les {n} dernières heures",
  "ventana.minutos_one": "la dernière minute",
  "ventana.minutos_other": "les {n} dernières minutes",
  "relativo.ahora": "à l’instant",
  "relativo.min": "il y a {n} min",
  "relativo.h": "il y a {n} h",
  "relativo.d": "il y a {n} j",

  "nav.diagnostico": "Diagnostic",
  "nav.trazas": "Traces",
  "nav.panel": "Tableau de bord",
  "nav.evaluaciones": "Tester",
  "nav.prompts": "Prompts",
  "nav.ajustes": "Réglages",

  "barra.proyecto": "Projet",
  "barra.sin_proyectos": "Aucun projet",
  "barra.rango": "Période",
  "barra.idioma": "Langue",
  "barra.avanzado": "Avancé",
  "barra.avanzado_ayuda": "Affiche la couche technique : requêtes, attributs, identifiants",
  "barra.tu_cuenta": "Votre compte : {email}",
  "barra.organizacion": "Organisation et compte",
  "barra.salir": "Se déconnecter",
  "rango.1": "24 heures",
  "rango.7": "7 jours",
  "rango.30": "30 jours",

  "estado.sin_backend.titulo": "Impossible de joindre le backend",
  "estado.sin_backend.texto":
    "Il ne répond pas. En local, lancez-le avec {local} ; pour l’installation complète, avec {docker}.",
  "estado.reintentar": "Réessayer",
  "estado.sin_proyecto.titulo": "Aucun projet pour l’instant",
  "estado.sin_proyecto.texto":
    "Dès que votre agent enverra sa première exécution, elle apparaîtra ici. L’instrumenter tient en une ligne :",
  "estado.primer_proyecto":
    "Sur cette installation, l’agent a besoin d’une clé pour envoyer des traces. {enlace} : l’extrait ci-dessus y apparaît avec la clé déjà remplie.",
  "estado.primer_proyecto.enlace": "Créez-la dans Organisation",
  "estado.demo.texto":
    "Vous voulez juste le voir fonctionner ? Chargez des traces d’exemple (des données inventées, dans un projet à part nommé « demo ») et regardez ce qu’il détecte.",
  "estado.demo.cargando": "Chargement…",
  "estado.demo.boton": "Charger des données d’exemple",
  "estado.demo.terminal": "Depuis un terminal : {comando}.",
  "estado.demo.error": "impossible de les charger",
  "estado.sin_trazas.titulo": "En attente de la première exécution de « {proyecto} »",
  "estado.sin_trazas.texto":
    "Aucune trace de ce projet n’est encore arrivée. Dès que vous lancerez votre agent avec Laplace activé, elle apparaîtra ici :",
  "estado.nada.titulo_con_aviso":
    "Nous n’avons rien trouvé à corriger, mais nous n’avons pas pu tout examiner",
  "estado.nada.titulo": "Vous ne gaspillez pas d’argent en ce moment",
  "estado.nada.texto":
    "Nous avons cherché des appels répétés, des étapes qui utilisent un modèle plus cher que nécessaire et du contexte renvoyé sans raison. Il n’y a rien de tout cela sur cette période.",
  "estado.clave.titulo": "Cette installation demande une clé",
  "estado.clave.sin_clave":
    "Si vous n’en avez pas, la personne qui administre cette organisation la crée, dans Organisation → Clés.",
  "estado.clave.guardar": "Enregistrer et entrer",
  "estado.clave.con_cuenta": "Se connecter avec votre compte",
  "estado.clave.cookie":
    "Elle est vérifiée puis stockée dans un cookie que seul ce Laplace voit : ni la page ni aucun script ne peuvent la lire, et elle ne passe jamais dans l’URL, car ce qui passe dans l’URL finit dans les journaux de chaque proxy traversé.",
  "estado.ajeno.titulo": "Votre clé ne donne pas accès à ce projet",
  "estado.ajeno.texto": "Cette clé sert à un autre projet de cette installation.",
  "estado.ajeno.otra": "Utiliser une autre clé",
  "estado.volver": "Retour",
  "diag.titulo": "Votre agent « {proyecto} »",
  "diag.al_ritmo": "Au rythme observé sur {ventana}",
  "diag.en_datos": "Sur {tiempo} de données",
  "diag.costara": "vous coûtera ce mois-ci",
  "diag.ha_costado": "vous a coûté jusqu’ici",
  "diag.contexto": "Contexte",
  "diag.cobertura": "Couverture",
  "diag.metricas": "Métriques",
  "diag.m.p95": "Latence p95",
  "diag.m.errores": "Exécutions en erreur",
  "diag.m.tokens": "Tokens",
  "diag.m.trazas": "Traces",
  "diag.m.pasos": "Étapes",
  "diag.m.coste": "Coût par exécution",
  "diag.m.cache": "Déjà économisé grâce au cache",
  "diag.m.datos": "Données observées",
  "diag.nada.aviso": "Avec cette couverture, « rien à corriger » veut dire « nous ne savons pas », pas « tout va bien ».",
  "diag.nada.gastado": "Vous avez dépensé {coste} sur {ejecuciones} exécutions.",
  "diag.ver_trazas": "Voir toutes les traces",
  "diag.cosas_one": "Une chose à corriger",
  "diag.cosas_other": "{n} choses à corriger",
  "comun.exportar_csv": "Exporter en CSV",
  "diag.orden": "De celle qui vous fait économiser le plus à celle qui en fait économiser le moins.",
  "diag.cifras_proyeccion": "Les chiffres sont la projection sur 30 jours du rythme observé sur {ventana}.",
  "diag.cifras_gastado": "Les chiffres sont de l’argent déjà dépensé sur {ventana}.",
  "diag.nota.proyeccion": "Les montants sont une estimation à partir des données recueillies sur {ventana}, projetée sur 30 jours. Si votre trafic change, ils changent.",
  "diag.nota.gastado": "Les montants sont de l’argent {ya} sur {ventana}, pas une projection : il n’y a pas assez de données pour estimer le mois.",
  "diag.nota.ya_gastado": "déjà dépensé",
  "diag.nota.moneda": "Le coût est en {moneda} car c’est la devise dans laquelle facturent les fournisseurs.",
  "diag.ver_mas_one": "En voir un de plus",
  "diag.ver_mas_other": "En voir {n} de plus",
  "diag.tiempo_one": "Et un qui ne coûte pas d’argent, seulement du temps",
  "diag.tiempo_other": "Et {n} qui ne coûtent pas d’argent, seulement du temps",
  "diag.presupuesto": "Budget",
  "diag.presupuesto.invitar": "{enlace} et nous vous prévenons avant que vous le dépassiez.",
  "diag.presupuesto.enlace": "Fixez un budget mensuel",
  "diag.presupuesto.aria": "{n} pour cent du budget",
  "estado.arreglado": "Corrigé",
  "estado.ignorado": "Ignoré",
  "estado.desaparecido": "Ne se produit plus",
  "diag.apartados_one": "Un problème qui n’est plus en attente",
  "diag.apartados_other": "{n} problèmes qui ne sont plus en attente",
  "diag.desaparecido": "Ne se produit plus depuis le {fecha}. Cela ne compte pas comme une économie : le corriger ne vous rapporterait plus rien.",
  "diag.ignorado_coste": "{coste} sur la période, non comptés comme évitables.",
  "csv.abierto": "ouvert",
  "csv.si": "oui",
  "csv.no": "non",
  "csv.h.problema": "Problème",
  "csv.h.tipo": "Type",
  "csv.h.estado": "Statut",
  "csv.h.gastado": "Déjà dépensé (USD)",
  "csv.h.al_mes": "Par mois (USD)",
  "csv.h.suelo": "Est un plancher",
  "csv.h.tokens": "Tokens en trop",
  "csv.h.espera": "Attente évitable (s)",
  "csv.h.ejecuciones": "Exécutions concernées",
  "csv.h.arreglo": "Correction",
  "csv.nombre.problemas": "problemes",
  "piezas.gap.aria": "{necesario} de coût nécessaire, {evitable} évitable",
  "piezas.gap.real": "{coste} de travail réel",
  "piezas.gap.tirando": "{coste} que vous gaspillez",
  "piezas.puesto": "Rang {n}",
  "piezas.tokens_de_mas": "tokens en trop",
  "piezas.espera": "d’attente évitable",
  "piezas.al_mes": "par mois",
  "piezas.ya_gastado": "déjà dépensé",
  "piezas.reaparecido": "Vous l’avez marqué comme corrigé et il réapparaît.",
  "piezas.marcado": "Marqué comme corrigé.",
  "piezas.sin_tarifa": "Consomme des tokens ; pas de tarif pour le chiffrer",
  "piezas.suelo": "C’est un plancher : le coût réel peut être plus élevé",
  "piezas.sin_verificar": "Avec un tarif non vérifié",
  "piezas.ver_arreglo": "Voir comment le corriger →",
  "avisos.casi_todo": "Presque tout ce que vous dépensez est signalé ci-dessous :",
  "avisos.casi_todo.cifras": "{evitable} sur {total} ({pct}).",
  "avisos.casi_todo.porque": "Pourquoi ne pas le présenter comme une économie ?",
  "avisos.casi_todo.texto": "Parce que « vous pouvez arrêter de payer votre agent » n’est presque jamais ce que cela signifie. Il y a généralement derrière un petit agent ou un agent tout neuf où deux ou trois étapes représentent pratiquement toute la facture, et les corriger change ces étapes, pas l’agent entier. Regardez le détail de chaque problème avant de compter sur ce chiffre.",
  "avisos.no_lo_usas": "non utilisé",
  "avisos.pct_aria": "{n} pour cent",
  "avisos.de_llamadas": "{n} appels sur {total}",
  "avisos.incompleto": "Ce total est incomplet :",
  "avisos.incompleto.linea": "{n} étapes sans tarif ({modelos}).",
  "avisos.incompleto.porque": "Leur modèle n’est pas dans notre table des prix : nous ne savons pas ce qu’elles coûtent et elles ne sont pas additionnées. Vous pouvez fixer un prix dans Réglages, et ce qui est déjà enregistré est recalculé.",
  "avisos.suelo": "C’est un plancher :",
  "avisos.suelo.linea_one": "sur {n} étape, nous avons appliqué le tarif standard.",
  "avisos.suelo.linea_other": "sur {n} étapes, nous avons appliqué le tarif standard.",
  "avisos.suelo.porque": "Contexte long, résidence des données ou mode rapide sont des tarifs à part que la réponse du fournisseur ne révèle pas toujours. Le coût réel peut être un peu plus élevé, jamais moindre. Chaque étape indique le doute, en mode avancé.",
  "avisos.proyeccion": "Projection à partir des données recueillies sur {ventana}.",
  "avisos.proyeccion.porque": "C’est ce que vous envoyez, pas la période demandée par le sélecteur. Dépenses et économies viennent de la même base : si l’une change, l’autre aussi.",
  "avisos.sin_proyectar": "Argent déjà dépensé, sans projection.",
  "avisos.sin_proyectar.linea": "La prévision mensuelle apparaît à partir de {tiempo} de données.",
  "avisos.sin_proyectar.porque": "Avec les données recueillies sur {ventana}, multiplier pour arriver à 30 jours donne un chiffre qui ne tient pas : un pic de dix minutes deviendrait des centaines de dollars.",
  "avisos.mucho": "L’économie estimée représente {pct} de vos dépenses.",
  "avisos.mucho.porque": "C’est beaucoup : cela arrive souvent avec de petits agents ou des agents tout neufs, où quelques étapes dominent la facture. Avant de le tenir pour acquis, regardez le détail de chaque problème.",
  "avisos.sin_dinero": "Nous ne pouvons pas calculer l’argent",
  "prob.no_aparece.titulo": "Ce problème n’apparaît plus",
  "prob.no_aparece.texto": "Soit vous l’avez corrigé, soit il ne se produit plus sur la période affichée. Bravo dans les deux cas.",
  "prob.que_pasa": "Ce qui se passe",
  "prob.deteccion": "Comment nous l’avons détecté",
  "prob.deteccion.nota": "C’est la requête réellement exécutée, pas une version d’exemple. Les seuils des règles sont les mêmes pour tous les projets : Réglages décide de ce qui alerte, pas de ce qui est détecté.",
  "prob.traza": "La trace complète",
  "prob.traza.texto": "Une exécution réelle où le problème apparaît.",
  "prob.traza.abrir": "Ouvrez-la pour la parcourir étape par étape →",
  "prob.atributos": "Attributs de l’étape signalée",
  "prob.arreglo": "Comment le corriger",
  "prob.ahorro": "Combien vous économisez",
  "prob.ahorro.ya": "Sur {ventana}, {coste} sont déjà partis par ici.",
  "prob.ahorro.mes": "À ce rythme, le corriger vous évite de payer {coste}.",
  "prob.ahorro.al_mes": "{coste} par mois",
  "prob.ahorro.sin_mes": "Nous ne projetons pas encore le mois : avec {tiempo} de données, multiplier jusqu’à 30 jours donnerait un chiffre qui ne tient pas.",
  "prob.ahorro.suelo": "Et c’est un {suelo} : certaines étapes ici ont un coût que nous ne pouvons pas confirmer, le chiffre réel peut donc être plus élevé, jamais moindre.",
  "prob.ahorro.suelo.palabra": "plancher",
  "prob.ahorro.sin_verificar": "Nous n’avons pas vérifié le tarif de {modelos} : il vient de la table communautaire de LiteLLM et peut ne pas correspondre à votre facture, dans un sens ou dans l’autre.",
  "prob.ahorro.tokens": "Cela consomme {tokens} en trop et {espera} d’attente sur la période analysée. Combien d’argent cela représente, nous ne le savons pas : {motivo}.",
  "prob.ahorro.tokens.n": "{n} tokens",
  "prob.ahorro.sin_tarifa": "ce modèle n’a pas de tarif connu",
  "prob.ahorro.tiempo": "Ce problème ne vous coûte pas d’argent : les étapes répétées ne consomment pas de tokens. Ce qu’il coûte, c’est de l’attente, {espera} sur la période analysée. Le corriger permet à votre agent de répondre plus vite.",
  "prob.calculo": "Calcul :",
  "prob.solo_lectura": "Votre rôle dans ce projet ({rol}) permet de le voir, pas de le marquer comme corrigé ni de l’ignorer.",
  "prob.ver_afectadas": "Voir les traces concernées",
  "prob.ver_ultimas": "Voir les dernières exécutions de cette étape",
  "tec.al_mes": "par mois si rien ne change",
  "tec.ya_gastados": "déjà dépensés en {ventana}",
  "tec.espera": "d’attente évitable en {ventana}",
  "tec.afectadas": "concernées",
  "tec.vueltas_mas_one": "…{n} tour de plus, tous avec la même réponse.",
  "tec.vueltas_mas_other": "…{n} tours de plus, tous avec la même réponse.",
  "tec.identicas_mas_one": "…{n} appel identique de plus, tous avec la même réponse.",
  "tec.identicas_mas_other": "…{n} appels identiques de plus, tous avec la même réponse.",
  "tec.tarifa_aplicada": "tarif appliqué",
  "tec.tarifa_no_verificada": "tarif non vérifié",
  "tec.tarifa_asumida": "tarif supposé",
  "seg.error.guardar": "impossible d’enregistrer",
  "seg.error.deshacer": "impossible d’annuler",
  "seg.error.crear": "impossible de créer",
  "seg.titulo.ignorado": "Vous l’avez marqué comme ignoré",
  "seg.titulo.reaparecido": "Vous l’avez marqué comme corrigé, et il réapparaît",
  "seg.titulo.arreglado": "Vous l’avez marqué comme corrigé",
  "seg.fecha": "Le {fecha}.",
  "seg.antes": "Avant, par exécution",
  "seg.despues": "Après",
  "seg.ejecuciones": "{n} exécutions",
  "seg.ignorado.nota": "Il ne compte pas dans l’évitable de l’accueil et n’envoie pas d’alertes.",
  "seg.deshacer": "Annuler et le remettre dans la liste",
  "seg.ya_arreglado": "L’avez-vous déjà corrigé ?",
  "seg.ya_arreglado.texto": "Marquez-le et nous vérifions : nous comparons le coût de chaque exécution avant et après. S’il réapparaît à l’identique, il revient dans la liste.",
  "seg.nota.placeholder": "Pourquoi ce n’est pas un problème (facultatif)",
  "seg.ignorar": "Ignorer ce problème",
  "comun.cancelar": "Annuler",
  "seg.arreglado.boton": "Je l’ai corrigé : vérifiez",
  "seg.no_problema": "Ce n’est pas un problème pour moi",
  "seg.probar.titulo": "Avant de changer, testez",
  "seg.probar.texto": "L’économie est mesurée ; que {modelo} réponde aussi bien, non. Enregistrez les exécutions réelles de cette étape comme jeu de cas et lancez-les avec le nouveau modèle : Tester vous dira s’il est aussi juste et combien il coûte en moins.",
  "seg.probar.barato": "le modèle bon marché",
  "seg.probar.ir": "Aller à Tester →",
  "seg.probar.crear": "Créer le jeu « {nombre} » avec ces exécutions",
  "seg.tokens": "{n} tokens",
  "trazas.orden.coste": "Les plus chères d’abord",
  "trazas.orden.reciente": "Les plus récentes",
  "trazas.orden.duracion": "Les plus lentes",
  "trazas.tipo.cualquiera": "N’importe quelle étape",
  "trazas.tipo.llm": "Avec un appel de modèle",
  "trazas.tipo.tool": "Avec un outil",
  "trazas.tipo.retrieval": "Avec une recherche",
  "trazas.titulo": "Traces",
  "trazas.lead": "Chaque ligne est une exécution complète de votre agent. Triées par coût.",
  "trazas.buscar.contenido": "Rechercher une commande, une phrase, un id…",
  "trazas.buscar.nombres": "Rechercher par étape, outil ou id de trace",
  "trazas.buscar": "Rechercher",
  "trazas.donde": "Où chercher",
  "trazas.en_nombres": "Dans les noms et id",
  "trazas.en_contenido": "Dans les prompts et réponses",
  "trazas.estado": "Statut",
  "trazas.estado.cualquiera": "N’importe quel statut",
  "trazas.estado.error": "Seulement en erreur",
  "trazas.estado.ok": "Seulement réussies",
  "trazas.tipo": "Type d’étape",
  "trazas.orden": "Tri",
  "trazas.modelo": "Modèle",
  "trazas.modelo.cualquiera": "N’importe quel modèle",
  "trazas.coste_minimo": "Coût minimum",
  "trazas.coste_minimo.aria": "Coût minimum en USD",
  "trazas.sesion.aria": "Identifiant de session",
  "trazas.filtrar": "Filtrer",
  "trazas.corta": "Pour chercher dans les prompts et réponses, saisissez au moins {n} caractères.",
  "trazas.filtro.paso": "Seulement les exécutions qui passent par l’étape du problème : {paso}",
  "trazas.filtro.usuario": "Seulement les exécutions de l’utilisateur {usuario}",
  "trazas.quitar": "Retirer",
  "trazas.ninguna": "Aucune trace ne correspond",
  "trazas.ninguna.texto": "Essayez de retirer des filtres ou d’élargir la période dans la barre du haut.",
  "trazas.quitar_filtros": "Retirer les filtres",
  "csv.h.traza": "Trace",
  "csv.h.agente": "Agent",
  "csv.h.inicio": "Début",
  "csv.h.sesion": "Session",
  "csv.h.usuario": "Utilisateur",
  "csv.h.pasos": "Étapes",
  "csv.h.tok_entrada": "Tokens d’entrée",
  "csv.h.tok_salida": "Tokens de sortie",
  "csv.h.coste": "Coût (USD)",
  "csv.h.incompleto": "Coût incomplet",
  "csv.h.duracion": "Durée (ms)",
  "csv.h.modelos": "Modèles",
  "csv.nombre.trazas": "traces",
  "lista.n_trazas": "{n} traces",
  "lista.en_pausa": " · en pause",
  "lista.cada": "Vérifié toutes les {n} secondes",
  "lista.vivo.necesita": "Le mode en direct nécessite le tri par plus récentes : cliquer le change",
  "lista.vivo.pausar": "En direct · pause",
  "lista.vivo.ver": "Voir en direct",
  "lista.col.traza": "Trace",
  "lista.col.modelos": "Modèles",
  "lista.col.pasos": "Étapes",
  "lista.col.tokens": "Tokens",
  "lista.col.entrada": "Entrée",
  "lista.col.salida": "Sortie",
  "lista.col.coste": "Coût",
  "lista.col.duracion": "Durée",
  "lista.col.cuando": "Quand",
  "lista.col.bien": "Correct ?",
  "lista.todas": " (toutes celles de la période)",
  "lista.antiguas": "Plus anciennes →",
  "lista.sin_backend": "Le backend ne répond pas ; nouvelle tentative en cours.",
  "lista.nuevas_one": "{n} nouvelle trace depuis l’activation.",
  "lista.nuevas_other": "{n} nouvelles traces depuis l’activation.",
  "lista.esperando": "En attente de nouvelles traces.",
  "lista.ultima": "Dernière vérification : {fecha}.",
  "lista.con_error": "en erreur",
  "lista.sin_nombre": "(sans nom)",
  "lista.bucle.ayuda": "Répète des étapes avec la même entrée",
  "lista.bucle": "boucle",
  "lista.errores_one": "{n} erreur",
  "lista.errores_other": "{n} erreurs",
  "lista.sesion": " · session {id}",
  "lista.coste_incompleto": "coût incomplet",
  "conj.creado": "Jeu « {nombre} » créé avec ce filtre.",
  "conj.ir": "Aller à Tester",
  "conj.guardar": "Enregistrer ces traces comme jeu de cas",
  "conj.nombre.placeholder": "Nom, p. ex. regressions-paiement",
  "conj.nombre.aria": "Nom du jeu",
  "conj.creando": "Création…",
  "conj.boton": "Enregistrer (jusqu’à 50)",
  "traza.no_encontrada": "Trace introuvable",
  "traza.no_encontrada.texto": "L’identifiant est peut-être erroné, ou la trace est plus ancienne que la durée de conservation.",
  "traza.todas": "Toutes les traces",
  "traza.problemas_one": "Un problème détecté se produit dans cette exécution :",
  "traza.problemas_other": "{n} problèmes détectés se produisent dans cette exécution :",
  "traza.estado.ignorado": "ignoré",
  "traza.estado.reaparecido": "marqué comme corrigé, mais persiste",
  "traza.estado.arreglado": "marqué comme corrigé",
  "traza.bien": "Cette exécution est-elle correcte ?",
  "traza.juez.sin_tarifa": "Jugée avec {modelo}. Nous ne connaissons pas son coût : ce modèle n’est pas dans la table des prix.",
  "traza.juez.coste": "Jugée avec {modelo}. Cela a coûté {coste}.",
  "traza.juez.error": "le juge n’a pas pu se prononcer",
  "traza.juez.juzgando": "Évaluation…",
  "traza.juez.opine": "Demander l’avis de {modelo}",
  "traza.juez.ocultar": "Masquer le prompt du juge",
  "traza.juez.ver": "Voir le prompt du juge",
  "traza.exportar": "Exporter la trace en JSON",
  "traza.usuario": " · utilisateur {id}",
  "traza.coste.faltan": "coût ({n} étapes sans tarif manquantes)",
  "traza.coste.sin_verificar": "coût (tarif non vérifié)",
  "traza.coste": "coût",
  "traza.tokens": "tokens entrée / sortie",
  "traza.duracion": "durée",
  "traza.pasos": "étapes",
  "traza.llamadas": "appels de modèle",
  "traza.herramientas": "outils",
  "traza.modelos": "modèles",
  "traza.cache_tokens": "tokens servis depuis le cache",
  "traza.cache_ahorro": "économisés grâce au cache",
  "traza.asumida": "étapes au tarif supposé",
  "traza.errores": "erreurs",
  "arbol.titulo": "Arbre d’exécution",
  "arbol.n_de": "{n} étapes sur {total}",
  "arbol.teclas": "↑↓ se déplacer · ←→ replier",
  "arbol.plegar_todo": "Tout replier",
  "arbol.desplegar_todo": "Tout déplier",
  "arbol.desplegar": "déplier",
  "arbol.plegar": "replier",
  "arbol.misma_llamada": "Même appel avec la même entrée",
  "arbol.selecciona": "Sélectionnez une étape dans l’arbre.",
  "arbol.prompt": "Prompt ({n})",
  "arbol.respuesta": "Réponse ({n})",
  "arbol.argumentos": "Arguments",
  "arbol.salida": "Sortie",
  "arbol.consulta": "Requête",
  "arbol.documentos": "Documents ({n})",
  "arbol.entrada": "Entrée",
  "arbol.eventos": "Événements ({n})",
  "arbol.evento": "événement",
  "arbol.modelo": "modèle",
  "arbol.tok_entrada": "tokens d’entrée",
  "arbol.tok_entrada_est": "tokens d’entrée (estimés)",
  "arbol.tok_salida": "tokens de sortie",
  "arbol.tok_salida_est": "tokens de sortie (estimés)",
  "arbol.sin_precio": "prix inconnu",
  "arbol.coste_minimo": "coût minimum (tarif supposé)",
  "arbol.desde_cache": "depuis le cache ({coste})",
  "arbol.escritos_cache": "écrits en cache ({coste})",
  "arbol.ahorro_cache": "économisés grâce au cache",
  "arbol.rama.pasos": "étapes de la branche",
  "arbol.rama.error": "en erreur",
  "arbol.rama.tokens": "tokens de la branche",
  "arbol.rama.coste": "coût de la branche",
  "arbol.mensaje": "message",
  "arbol.contenido": "contenu",
  "arbol.raiz": "(racine)",
  "arbol.estimados": "true (comptés par nous)",
  "arbol.del_proveedor": "false (du fournisseur)",
  "arbol.ninguna": "aucun : modèle inconnu",
  "arbol.atributos": "Attributs bruts",
  "arbol.sin_contenido": "Aucun contenu.",
  "arbol.copiado": "copié",
  "arbol.copiar": "copier",
  "arbol.misma_entrada": "Même appel, même entrée",
  "ver.buena": "Marquer cette exécution comme bonne",
  "ver.mala": "Marquer cette exécution comme mauvaise",
  "ver.solo_ver": "Votre rôle ne permet que de consulter",
  "ver.bien": "Bien",
  "ver.mal": "Mal",
  "ver.ocultar": "Masquer le commentaire",
  "ver.ver": "Voir le commentaire",
  "ver.comentar": "Commenter",
  "ver.placeholder": "Ce qui a échoué, ou pourquoi c’est correct. Enregistré au marquage.",
  "ver.nota": "Le commentaire est enregistré avec le verdict : appuyez de nouveau sur « {bien} » ou « {mal} » après l’avoir écrit.",
  "ver.juez": "juge",
  "ver.no_guardado": "non enregistré",
  "ver.maquina": "verdict automatique",
  "ver.juez_dice": "juge : {v}",
  "ver.bien_min": "bien",
  "ver.mal_min": "mal",
  "ver.coste_desconocido": " coût inconnu",
  "ver.persona": "personne : {v}",
  "panel.titulo": "Votre agent « {proyecto} », par unité de travail",
  "panel.por_ejecucion": "Par exécution",
  "panel.por_ejecucion.lead": "Ce que coûte une exécution de votre agent. C’est le chiffre qui compte : des dépenses qui augmentent parce qu’il y a plus de travail ne sont pas un problème, et ceci fait la différence.",
  "panel.totales": "Totaux, pour le contexte",
  "panel.totales.lead": "Ils sont ici exprès : à eux seuls, ils ne disent pas si quelque chose ne va pas.",
  "panel.error.cargar": "impossible de charger",
  "panel.quien": "Qui dépense le plus",
  "panel.agrupar": "Regrouper par",
  "panel.usuarios": "Utilisateurs",
  "panel.sesiones": "Sessions",
  "panel.sin_usuario": "Aucune exécution de cette période n’indique son utilisateur. Avec {codigo} dans votre agent, vous verrez ici qui dépense.",
  "panel.sin_sesion": "Aucune exécution de cette période n’indique sa session. Avec {codigo} dans votre agent, vous verrez ici qui dépense.",
  "panel.col.usuario": "Utilisateur",
  "panel.col.sesion": "Session",
  "panel.col.ejecuciones": "Exécutions",
  "panel.col.por_ejecucion": "Par exécution",
  "panel.col.total": "Total",
  "panel.col.del_gasto": "Des dépenses",
  "panel.sin_etiqueta_usuario": "Par ailleurs, {n} exécutions sans utilisateur ({coste}).",
  "panel.sin_etiqueta_sesion": "Par ailleurs, {n} exécutions sans session ({coste}).",
  "panel.menos_de": "< {x}",
  "panel.sin_comparacion": "sans comparaison",
  "panel.vs_anterior": "{cambio} par rapport à la période précédente",
  "panel.grafica.titulo": "Coût par exécution, par tranches de {tramo}",
  "panel.grafica.coste": "coût par exécution",
  "panel.grafica.ejecuciones": "exécutions",
  "panel.grafica.aria": "Coût par exécution par tranche",
  "panel.grafica.punto": "{fecha} · {coste} par exécution · {n} exécutions",
  "panel.grafica.desde": " · depuis la première donnée",
  "panel.grafica.nota": "Les tranches sans exécution restent vides. Ce n’est pas un coût nul : il n’y avait rien à exécuter, et le dessiner comme zéro montrerait une baisse qui n’a pas eu lieu.",
  "panel.picos": "Pics",
  "panel.picos.ninguno": "Aucune tranche ne sort de l’ordinaire sur cette période. Le coût par exécution reste dans ses valeurs habituelles.",
  "panel.picos.n_one": "Une tranche sort de l’ordinaire",
  "panel.picos.n_other": "{n} tranches sortent de l’ordinaire",
  "panel.picos.lead": "Tranches où chaque exécution a coûté bien plus que d’habitude. De la plus chère à la moins chère.",
  "panel.pico.cuando": "A commencé le {inicio} et a duré jusqu’à {fin}",
  "panel.pico.de_mas": "en trop",
  "panel.pico.texto_one": "Dans cette tranche, chaque exécution a coûté {coste}, contre {base} d’habitude : {veces} sur {n} exécution.",
  "panel.pico.texto_other": "Dans cette tranche, chaque exécution a coûté {coste}, contre {base} d’habitude : {veces} sur {n} exécutions.",
  "panel.pico.veces": "{n} fois plus",
  "panel.pico.ver_prompt": "voir ce prompt",
  "panel.pico.ver_trazas": "Voir les traces de cette tranche",
  "panel.pico.orden": "Triées par coût, de la plus chère à la moins chère",
  "panel.pico.tramo": "tranche",
  "panel.pico.base": "base de référence",
  "panel.pico.mediana": "médiane des tranches avec exécutions",
  "ev.titulo": "Testez les corrections de « {proyecto} » avant de les déployer",
  "ev.lead": "C’est la deuxième étape du cycle : le Diagnostic dit ce que rapporte une correction ; ici, on vérifie sur les appels réels de cette étape que l’agent est aussi juste avec la correction en place.",
  "ev.conj.titulo": "Jeux de cas",
  "ev.conj.lead": "Des collections d’exécutions {reales} de votre agent. Aucun cas inventé ici : chacun provient d’une trace qui a eu lieu, et on peut l’ouvrir pour voir d’où il vient.",
  "ev.conj.reales": "réelles",
  "ev.conj.nombre": "Nom",
  "ev.conj.cuantas": "Combien de traces",
  "ev.conj.crear": "Créer à partir des plus récentes",
  "ev.conj.otro_filtro": "Vous voulez un autre filtre ? Filtrez dans {explorador} et cliquez sur « {guardar} » : le jeu conserve le filtre qui l’a formé, pour qu’on puisse ensuite discuter de son origine.",
  "ev.explorador": "l’explorateur",
  "ev.conj.ninguno": "Il n’y en a encore aucun.",
  "ev.conj.col.conjunto": "Jeu",
  "ev.conj.col.casos": "Cas",
  "ev.conj.col.filtro": "Filtre d’origine",
  "ev.conj.col.creado": "Créé",
  "ev.conj.sin_filtro": "sans filtre (les plus récentes)",
  "ev.borrar": "Supprimer",
  "ev.tiradas": "Lancements",
  "ev.tiradas.lead": "Chacun est un passage d’un jeu par une version de votre agent. Le SDK les lance dans votre processus ; seuls le rapport et les traces arrivent ici.",
  "ev.col.version": "Version",
  "ev.col.conjunto": "Jeu",
  "ev.col.casos": "Cas",
  "ev.col.personas": "Personnes",
  "ev.col.juez": "Juge",
  "ev.col.coste": "Coût",
  "ev.col.juzgar": "Coût de l’évaluation",
  "ev.col.cuando": "Quand",
  "ev.sin_tiradas": "Pas de lancement d’une nouvelle version ? Lancez-le avec {codigo} en pointant vers ce même Laplace. Les traces générées apparaissent dans {explorador} comme les autres, et le projet est « {proyecto} ».",
  "ev.entre": "entre {bajo} et {alto}",
  "ev.error.comparar": "impossible de comparer",
  "ev.paso1": "Enregistrez un jeu de cas",
  "ev.paso1.texto": "Des exécutions réelles de votre agent. Depuis {explorador}, filtrez et cliquez sur « {guardar} », ou créez-le ci-dessous avec les plus récentes.",
  "ev.paso2": "Lancez-le avec la version actuelle",
  "ev.paso2.texto": "Le SDK lance le passage dans votre processus (Laplace n’exécute pas votre agent) :",
  "ev.paso3": "Et encore avec la nouvelle version",
  "ev.paso3.texto": "Un autre prompt, un autre modèle : la même ligne avec un autre {variant}. Avec les deux passages, la comparaison de justesse et de coût apparaît ici. La justesse vient de vos annotations ou du juge automatique.",
  "ev.comparar.titulo": "Comparer deux versions",
  "ev.comparar.pasos": "Trois étapes, chacune se coche toute seule une fois faite.",
  "ev.comparar.lead": "Justesse et coût ensemble. Les deux passages doivent porter sur le même jeu : comparer la justesse sur des cas différents ne dirait rien.",
  "ev.a": "A — la référence",
  "ev.b": "B — la nouvelle",
  "ev.elige": "Choisissez un passage",
  "ev.elige_a": "Choisissez A d’abord",
  "ev.n_casos": "{n} cas",
  "ev.comparando": "Comparaison…",
  "ev.comparar": "Comparer",
  "ev.discrepan": "Les personnes et le juge ne disent pas la même chose.",
  "ev.discrepan.texto": "Ce n’est pas un bug du produit : c’est l’information la plus intéressante que cet écran puisse vous donner. Soit le juge mesure autre chose, soit la personne qui a annoté et celle qui a écrit le prompt du juge n’entendent pas la même chose par « bien ». Regardez les cas avant de vous fier à l’un ou l’autre.",
  "ev.costo": "Ce qu’a coûté chacune",
  "ev.costo.lead": "Ceci n’a pas de marge : ce n’est pas un échantillon, c’est la facture de ce qui a été exécuté. Si vous gérez vos prompts dans Laplace, sous chaque côté vous verrez {enlace}, lue dans les traces et non dans l’étiquette donnée au passage.",
  "ev.costo.enlace": "avec quelle version il a tourné",
  "ev.juzgar_dos": "Évaluer les deux passages avec {modelo}",
  "ev.cuesta": "Cela coûte de l’argent : vous saurez combien dès que ce sera fini",
  "ev.tec.conjunto": "jeu",
  "ev.tec.casos": "cas",
  "ev.fuente.personas": "Personnes",
  "ev.fuente.juez": "Juge (modèle)",
  "ev.de": "{a} sur {b}",
  "ev.sin_anotar": " · {n} non annotés",
  "ev.wilson": "entre {bajo} et {alto} (Wilson, 95 %)",
  "ev.por_caso": "par cas",
  "ev.tec.total": "total",
  "ev.tec.tokens": "tokens",
  "ev.tec.duracion": "durée",
  "ev.tec.reventados": "plantés",
  "ev.juez_costo": "Évaluer ce passage a coûté {coste} à part{desconocido}. C’est notre dépense, pas celle de votre agent, d’où la séparation.",
  "ev.juez_desconocido": " (et le coût de certains verdicts est inconnu)",
  "pr.titulo": "Les prompts de « {proyecto} »",
  "pr.lead": "Chaque version avec ce qu’elle a coûté et sa justesse sur le trafic réel qui l’a utilisée, pour décider laquelle garder en production avec les deux chiffres sous les yeux.",
  "pr.error.abrir": "impossible d’ouvrir",
  "pr.error.version": "impossible de changer de version",
  "pr.en_produccion": "v{n} en production",
  "pr.cerrar": "Fermer",
  "pr.ver_versiones": "Voir les versions et le diff",
  "pr.reserva_one": "{n} exécution a utilisé le texte de secours.",
  "pr.reserva_other": "{n} exécutions ont utilisé le texte de secours.",
  "pr.reserva.texto": "Cela signifie que votre agent n’a pas pu récupérer le prompt auprès de Laplace et a utilisé celui de son code. Ce trafic est compté à part, pas dans la version en production : l’y ajouter fausserait justement le chiffre que vous regardez.",
  "pr.acierto.nota": "La justesse d’une version est celle des {enteras} auxquelles elle a participé, pas celle de ce prompt isolé. Une exécution passe par plusieurs étapes et, quand elle échoue, personne n’a mesuré laquelle l’a gâchée. C’est un signal utile, pas une répartition des torts.",
  "pr.acierto.enteras": "exécutions entières",
  "pr.tec.versiones": "versions",
  "pr.tec.creado": "créé",
  "pr.col.version": "Version",
  "pr.col.por_ejecucion": "Par exécution",
  "pr.col.ejecuciones": "Exécutions",
  "pr.col.tokens": "Tokens/exéc.",
  "pr.col.ultimo": "Dernière utilisation",
  "pr.produccion": "production",
  "pr.poner": "Mettre en production",
  "pr.ocultar_mudas": "Masquer les versions sans trafic",
  "pr.ver_mudas_one": "Voir {n} version qui n’a pas tourné sur cette période",
  "pr.ver_mudas_other": "Voir {n} versions qui n’ont pas tourné sur cette période",
  "pr.wilson": "{bajo}–{alto} (Wilson)",
  "pr.nuevo": "Sortir un prompt du code",
  "pr.nuevo.lead": "Le nom est celui avec lequel vous le demanderez : {codigo}. La première version passe en production toute seule ; à partir de la deuxième, enregistrer et déployer sont deux gestes distincts.",
  "pr.nombre": "Nom",
  "pr.nuevo.placeholder": "Vous êtes un assistant qui répond en {{idioma}} et en moins de trois phrases.",
  "pr.crear": "Créer et mettre en production",
  "pr.que_cambio": "Ce qui a changé",
  "pr.de": "De",
  "pr.a": "À",
  "pr.elige_dos": "Choisissez deux versions différentes pour voir le diff. Avec une seule, il n’y a rien à comparer.",
  "pr.texto_v": "Le texte de la v{n}",
  "pr.guardar_nueva": "Enregistrer une nouvelle version",
  "pr.guardar_nueva.lead": "Enregistrer ne déploie pas. Ce sont deux gestes distincts exprès : c’est ce qui vous permet de préparer une version tranquillement, et ce qui rend possible le bouton de retour arrière.",
  "pr.texto.placeholder": "Le texte du prompt. Utilisez {{variable}} pour ce qui change à chaque appel.",
  "pr.guardando": "Enregistrement…",
  "pr.guardar": "Enregistrer la version",
  "pr.guardada": "Enregistrée, pas servie",
  "pr.historial": "Historique des déploiements",
  "pr.col.cuando": "Quand",
  "pr.col.quien": "Qui",
  "pr.col.nota": "Note",
  "pr.vuelta_atras": "retour arrière",
  "pr.historial.nota": "Cet historique raconte l’histoire ; il n’attribue {no} les pics. Pour cela, le {panel} utilise la version présente dans les traces de la tranche, qui est un fait mesuré et non une coïncidence d’horaires.",
  "pr.no": "pas",
  "pr.panel": "tableau de bord",
  "pr.borrar": "Supprimer ce prompt",
  "pr.borrar.nota": "Les traces ne sont pas modifiées : elles indiqueront toujours avec quelle version elles ont tourné",
  "pr.sin_adoptar": "Vous ne gérez encore aucun prompt ici",
  "pr.sin_adoptar.1": "Vos prompts vivent dans votre code, ce qui est tout à fait raisonnable. Ce que vous perdez, c’est la possibilité de répondre à « combien coûtait l’ancien et à quel point était-il juste ? », car un {blame} sait ce qui a changé mais pas ce qui s’est passé ensuite.",
  "pr.sin_adoptar.2": "Si vous les déplacez ici, le SDK les sert et note dans chaque trace la version utilisée. {nada} : il vous donne seulement le texte, et si Laplace ne répond pas, le SDK utilise la copie enregistrée ou le texte de secours que vous lui passez.",
  "pr.sin_adoptar.nada": "Laplace n’exécute toujours rien de votre côté",
  "pr.sin_adoptar.3": "En attendant, voici ce qu’on peut savoir de vos traces : quelles étapes ont changé d’instructions et quand.",
  "pr.obs.titulo": "Ce qu’on voit dans vos traces",
  "pr.obs.nada": "Rien pour l’instant.",
  "pr.obs.gestion": "Ceci vient des traces, pas de la gestion des prompts : ce sont les jeux d’instructions avec lesquels chaque étape a été vue tourner. Cela permet de repérer ce qui a changé en dehors d’ici.",
  "pr.obs.sin_gestion": "Chaque étape de votre agent, et les jeux d’instructions avec lesquels elle a été vue tourner sur cette période. Si les instructions d’une étape changent d’une exécution à l’autre, c’est un changement de prompt : nous ne connaissons pas le texte entier (nous ne gardons que le début), mais nous savons quand il a changé et ce qu’il a coûté.",
  "pr.obs.cambio": "Vous voyez un changement que vous ne reconnaissez pas ? {enlace} et regardez les instructions complètes de ces exécutions.",
  "pr.obs.abrir": "Ouvrez-le dans l’explorateur",
  "pr.obs.no_versiones": "ce ne sont pas des versions",
  "pr.obs.llamadas": "appels par exécution",
  "pr.obs.juego_one": "jeu d’instructions",
  "pr.obs.juego_other": "jeux d’instructions",
  "pr.obs.col.instrucciones": "Instructions (début)",
  "pr.obs.col.desde": "Depuis",
  "pr.obs.col.hasta": "Jusqu’à",
  "pr.obs.sin_instrucciones": "(aucune instruction capturée)",
  "comun.guardar": "Enregistrer",
  "comun.quitar": "Retirer",
  "aj.titulo": "Réglages de « {proyecto} »",
  "aj.lead": "Budget, alertes, tarifs et données. Chaque bloc s’enregistre séparément.",
  "aj.solo_lectura": "Le budget, les alertes et la suppression du projet sont gérés par un admin de l’organisation. Votre rôle ({rol}) permet de les consulter.",
  "aj.pres.guardado": "Budget enregistré.",
  "aj.pres.quitado": "Budget retiré.",
  "aj.pres.titulo": "Budget mensuel",
  "aj.pres.lead": "Sur le mois civil, celui que facture le fournisseur. Alerte à 80 % et à 100 % par les canaux ci-dessous, une fois chacun par mois.",
  "aj.pres.dolares": "Dollars par mois",
  "aj.error.borrar": "impossible de supprimer",
  "aj.datos": "Données",
  "aj.datos.retencion": "Cette installation conserve les traces {n} jours ; ce qui est plus ancien est supprimé automatiquement chaque jour.",
  "aj.datos.siempre": "Cette installation conserve les traces indéfiniment. Pour supprimer automatiquement les anciennes, lancez-la avec LAPLACE_RETENTION_DAYS.",
  "aj.borrar.titulo": "Supprimer « {proyecto} » entièrement.",
  "aj.borrar.texto": "Traces, annotations, jeux de cas, prompts, budget et alertes. C’est irréversible. Saisissez le nom du projet pour confirmer.",
  "aj.borrar.aria": "Nom du projet pour confirmer",
  "aj.borrar.boton": "Supprimer le projet",
  "aj.apariencia": "Apparence",
  "aj.en_navegador": "Enregistré dans ce navigateur.",
  "aj.tema": "Thème",
  "aj.tema.sistema": "Comme le système",
  "aj.tema.claro": "Clair",
  "aj.tema.oscuro": "Sombre",
  "aj.euros": "Afficher aussi en euros",
  "aj.euros.lead": "Les fournisseurs facturent en dollars et c’est ce chiffre qui fait foi. Si vous saisissez un taux de change, l’équivalent en euros apparaît à côté des montants principaux avec « ≈ ». C’est vous qui fixez le taux, enregistré uniquement dans ce navigateur : nous ne le téléchargeons de nulle part.",
  "aj.euros.tipo": "1 $ vaut … €",
  "aj.euros.guardado": "Taux enregistré.",
  "aj.euros.desactivados": "Euros désactivés.",
  "aj.tar.guardada": "Tarif de {modelo} enregistré. {n} appels déjà enregistrés ont maintenant leur coût.",
  "aj.tar.quitada": "Tarif de {modelo} retiré.",
  "aj.error.quitar": "impossible de retirer",
  "aj.tar.titulo": "Tarifs personnalisés",
  "aj.tar.lead": "Pour un modèle absent de notre table, ou avec un prix négocié. En dollars par million de tokens, d’après la page du fournisseur. L’enregistrer recalcule aussi ce que vous aviez déjà envoyé. Si le modèle tourne sur votre machine, ne lui mettez pas de prix : personne ne vous facture.",
  "aj.tar.instalacion": "Les tarifs s’appliquent à toute l’installation : seule une clé d’installation peut les modifier.",
  "aj.tar.sin_tarifa": "Sans tarif pour l’instant :",
  "aj.tar.modelo": "Modèle",
  "aj.tar.entrada": "Entrée",
  "aj.tar.salida": "Sortie",
  "aj.tar.entrada_m": "Entrée ($/M)",
  "aj.tar.salida_m": "Sortie ($/M)",
  "aj.tar.guardar": "Enregistrer le tarif",
  "aj.al.prueba_ok": "Message de test envoyé. Regardez le canal.",
  "aj.al.prueba_mal": "Il n’est arrivé par aucun canal. Vérifiez les adresses.",
  "aj.al.error.probar": "impossible de tester",
  "aj.al.titulo": "Alertes",
  "aj.al.lead": "Un message quand un problème dépasse le seuil en argent déjà dépensé. La même alerte n’est jamais répétée pendant la période de calme, et ce que vous marquez comme corrigé ou ignoré n’alerte pas.",
  "aj.al.silenciadas": "Coupées pour ce projet.",
  "aj.al.activas": "Actives.",
  "aj.al.apagadas": "Désactivées : ajoutez au moins un canal.",
  "aj.al.slack_guardado": "Webhook Slack enregistré.",
  "aj.al.slack_quitado": "Slack retiré.",
  "aj.al.webhook_titulo": "Webhook (Teams, Discord, n8n…)",
  "aj.al.webhook_guardado": "Webhook enregistré.",
  "aj.al.webhook_quitado": "Webhook retiré.",
  "aj.al.correo": "E-mail",
  "aj.al.correo_placeholder": "equipe@entreprise.com",
  "aj.al.correo_guardado": "E-mail enregistré.",
  "aj.al.correo_quitado": "E-mail retiré.",
  "aj.al.smtp": "Le serveur de messagerie de l’installation manque : lancez Laplace avec LAPLACE_SMTP_HOST, LAPLACE_SMTP_USER et LAPLACE_SMTP_PASSWORD.",
  "aj.al.umbral": "Seuil (dollars déjà dépensés)",
  "aj.al.calma": "Calme par problème (heures)",
  "aj.al.umbral_guardado": "Seuil et calme enregistrés.",
  "aj.al.que_avisa": "Ce qui alerte",
  "aj.al.reglas_guardadas": "Règles enregistrées.",
  "aj.al.probar": "Envoyer un message de test",
  "aj.al.reactivadas": "Alertes réactivées.",
  "aj.al.silenciadas_ok": "Alertes coupées.",
  "aj.al.reactivar": "Réactiver",
  "aj.al.silenciar": "Couper ce projet",
  "aj.al.puesto": " · défini ({actual})",
  "aj.al.otro": "Collez-en un autre pour le changer",
  "aj.regla.repeticion": "Répétitions",
  "aj.regla.bucle": "Boucles",
  "aj.regla.modelo_caro": "Modèle cher",
  "aj.regla.contexto_fijo": "Contexte sans cache",
  "titulo.ajustes": "Réglages",
  "titulo.configurar": "Configuration",
  "titulo.entrar": "Connexion",
  "titulo.evaluaciones": "Tester",
  "titulo.invitacion": "Invitation",
  "titulo.organizacion": "Organisation",
  "titulo.panel": "Tableau de bord",
  "titulo.problema": "Problème",
  "titulo.prompts": "Prompts",
  "titulo.traza": "Trace",
  "titulo.trazas": "Traces",
  "rol.lector": "lecteur",
  "rol.miembro": "membre",
  "rol.admin": "admin",
  "rol.propietario": "propriétaire",
  "org.error.cargar": "impossible de charger",
  "org.local.titulo": "Le mode local n’a pas de comptes",
  "org.local.texto": "C’est un processus sur votre machine avec vos traces : il n’y a personne d’autre à qui donner accès. Les comptes, les rôles et les clés existent dans l’installation cloud.",
  "org.tu_cuenta": "Votre compte",
  "org.eres": "Vous êtes {rol} de cette organisation.",
  "org.sin_org": "Vous n’appartenez encore à aucune organisation : demandez une invitation.",
  "org.org": "Organisation",
  "org.miembros": "Membres",
  "org.col.persona": "Personne",
  "org.col.rol": "Rôle",
  "org.col.desde": "Depuis",
  "org.tu": " · vous",
  "org.rol_de": "Rôle de {email}",
  "org.ahora_es": "{email} est maintenant {rol}.",
  "org.salir_confirm": "Quitter l’organisation ?",
  "org.quitar_confirm": "Retirer {email} ?",
  "org.hecho": "C’est fait.",
  "org.salir": "Quitter",
  "org.roles.nota": "Lecteur : consulte. Membre : annote aussi les exécutions, marque les problèmes et gère les prompts et les jeux. Admin : gère aussi les membres, les clés, les alertes, le budget et la suppression. Retirer quelqu’un ferme ses sessions immédiatement.",
  "org.invitar": "Inviter",
  "org.email": "E-mail",
  "org.email_placeholder": "personne@entreprise.com",
  "org.enviado": "Nous lui avons envoyé le lien par e-mail. Vous pouvez aussi le copier :",
  "org.sin_correo": "Cette installation n’a pas de messagerie configurée : envoyez-lui vous-même ce lien. Il n’est affiché que maintenant et expire dans 7 jours.",
  "org.pendientes": "En attente",
  "org.caduca": "expire le {fecha}",
  "org.anulada": "Invitation annulée.",
  "org.anular": "Annuler",
  "org.acc.configurar_instalacion": "a configuré l’installation",
  "org.acc.login": "s’est connecté",
  "org.acc.login_fallido": "tentative de connexion échouée",
  "org.acc.invitar": "a invité",
  "org.acc.anular_invitacion": "a annulé l’invitation de",
  "org.acc.aceptar_invitacion": "a accepté l’invitation en tant que",
  "org.acc.cambiar_rol": "a changé le rôle de",
  "org.acc.quitar_miembro": "a retiré",
  "org.acc.crear_clave": "a créé une clé pour",
  "org.acc.revocar_clave": "a révoqué la clé",
  "org.acc.borrar_proyecto": "a supprimé le projet",
  "org.registro": "Journal d’activité",
  "org.cargando": "Chargement…",
  "org.nada": "Rien pour l’instant.",
  "org.alguien": "quelqu’un",
  "org.admin_instalacion": " · vous administrez cette installation",
  "org.pass_actual": "Mot de passe actuel",
  "org.pass_nueva": "Nouveau (10 caractères ou plus)",
  "org.pass_cambiada": "Mot de passe changé. Les autres sessions ont été fermées.",
  "org.pass_cambiar": "Changer le mot de passe",
  "org.cerrar_todo": "Se déconnecter de tous les appareils",
  "org.error.generico": "impossible",
  "cla.titulo": "Clés d’API",
  "cla.lead": "Une clé par projet : c’est avec elle que votre agent envoie des traces. Saisissez un nouveau nom de projet pour le créer.",
  "cla.proyecto": "Projet",
  "cla.para_que": "À quoi elle sert",
  "cla.para_que_placeholder": "ingestion production",
  "cla.caduca": "Expire",
  "cla.nunca": "jamais",
  "cla.30": "dans 30 jours",
  "cla.90": "dans 90 jours",
  "cla.365": "dans un an",
  "cla.crear": "Créer une clé",
  "cla.copiala": "Copiez-la maintenant :",
  "cla.copiala.texto": "seule son empreinte est conservée et elle ne pourra plus être affichée. Si vous la perdez, révoquez-la et créez-en une autre.",
  "cla.col.nombre": "Nom",
  "cla.col.ultimo": "Dernière utilisation",
  "cla.no_caduca": "n’expire pas",
  "cla.revocar_confirm": "Révoquer « {nombre} » ? Elle cesse de fonctionner immédiatement.",
  "cla.revocada": "Clé révoquée.",
  "cla.revocar": "Révoquer",
  "cla.rotar": "Pour faire tourner une clé : créez la nouvelle, remplacez-la dans votre agent et révoquez l’ancienne.",
  "cla.copiado": "Copié",
  "cla.copiar": "Copier",
  "ent.error": "connexion impossible",
  "ent.titulo": "Se connecter à Laplace",
  "ent.contrasena": "Mot de passe",
  "ent.entrando": "Connexion…",
  "ent.entrar": "Se connecter",
  "ent.sin_cuenta": "Pas de compte ? Demandez une invitation à la personne qui administre votre organisation.",
  "ent.tengo_clave": "J’ai une clé d’API",
  "ent.comprobando": "Vérification…",
  "ent.usar_clave": "Utiliser la clé",
  "conf.error": "configuration impossible",
  "conf.titulo": "Configurez cette installation",
  "conf.texto": "Il n’y a encore aucun compte. Le premier administre toute l’installation et récupère les projets qui ont déjà des données.",
  "conf.codigo": "Code de configuration",
  "conf.codigo.ayuda": "Il se trouve dans le journal du serveur, à la ligne « no hay ninguna cuenta todavía ». Avec Docker : {comando}",
  "conf.org": "Nom de votre organisation",
  "conf.org_placeholder": "Mon entreprise",
  "conf.nombre": "Votre nom",
  "conf.contrasena": "Mot de passe (10 caractères ou plus)",
  "conf.creando": "Création…",
  "conf.crear": "Créer le compte d’administration",
  "inv.puede.lector": "voir les données de ses projets",
  "inv.puede.miembro": "consulter, annoter des exécutions, marquer des problèmes et gérer les prompts",
  "inv.puede.admin": "tout ce qui précède, plus les membres, les clés, les alertes et le budget",
  "inv.puede.propietario": "tout, y compris nommer et retirer des propriétaires",
  "inv.no_vale": "cette invitation n’est pas valide",
  "inv.error": "impossible d’accepter",
  "inv.no_vale.titulo": "Cette invitation n’est pas valide",
  "inv.no_vale.texto": "{motivo}. Les invitations expirent au bout de sept jours et ne servent qu’une fois : demandez-en une autre à la personne qui vous a invité.",
  "inv.unete": "Rejoignez « {org} »",
  "inv.como": "En tant que {rol} : vous pourrez {puede}.",
  "inv.con_cuenta": "Vous avez déjà un compte avec cet e-mail : votre mot de passe",
  "inv.elige": "Choisissez un mot de passe (10 caractères ou plus)",
  "inv.uniendote": "Adhésion…",
  "inv.aceptar": "Accepter l’invitation",
  "nf.titulo": "Cette page n’existe pas",
  "nf.texto": "Le lien est peut-être erroné, ou pointe vers quelque chose qui n’existe plus.",
  "nf.ir": "Aller au diagnostic",
  "err.titulo": "Un problème est survenu au chargement de cet écran",
  "err.texto": "Nous n’avons pas pu préparer les données. C’est généralement passager : réessayez et, si cela persiste, vérifiez que le backend fonctionne.",
  "prob.paso_titulo": "{titulo}.",
  // Errores de la API que no traen una frase propia.
  "api.fallo": "Erreur {estado} sur {ruta}",
  "api.no_valida": "La requête n’est pas valide : {campos}",
  // A1: un rango vacío no es un proyecto vacío.
  "estado.rango_vacio.titulo": "Aucune exécution sur {ventana}",
  "estado.rango_vacio.ultima": "La dernière est arrivée le {fecha}.",
  "estado.rango_vacio.fuera": "La dernière est arrivée le {fecha}, avant les {rango} consultables ici. Lancez votre agent avec Laplace activé pour voir des données récentes.",
  "estado.rango_vacio.boton": "Voir {ventana}",
  // Menos texto (D-151): el héroe, el distintivo de confianza y la ficha.
  "diag.puedes.proy": "Vous pouvez arrêter de payer jusqu’à",
  "diag.puedes.al_mes": "par mois",
  "diag.puedes.gastado": "Vous auriez pu économiser jusqu’à",
  "diag.puedes.en": "en {tiempo}",
  "diag.de_total.proy": "sur les {total} qu’il vous coûtera ce mois-ci, au rythme de {ventana}.",
  "diag.de_total.gastado": "sur les {total} dépensés en {tiempo} de données.",
  "conf.alta": "Confiance élevée",
  "conf.media": "Confiance moyenne",
  "conf.baja": "Confiance faible",
  "conf.notas_one": "{n} note",
  "conf.notas_other": "{n} notes",
  "conf.alta.texto": "Toute la dépense a un tarif connu et la part évitable n’est pas démesurée.",
  "conf.media.texto": "Le chiffre est fiable, mais lisez-le avec ces notes.",
  "conf.baja.texto": "Une partie de la dépense manque ou nous voyons mal cet agent : ne prenez pas ce chiffre pour définitif.",
  "prob.por_que.plegado": "Pourquoi cela arrive-t-il ?",
  "prob.ahorro.como": "Comment est-ce calculé ?",
  // Gráficos del Diagnóstico (D-152).
  "graf.titulo": "Où part l’argent",
  "graf.dia": "Dépense par jour",
  "graf.hora": "Dépense par heure",
  "graf.real": "travail réel",
  "graf.evitable": "évitable",
  "graf.punto": "{fecha} : {coste}, dont {evitable} évitables",
  "graf.aria": "Dépense par période avec la part évitable au-dessus",
  "graf.reparto": "Comment la part évitable est-elle répartie par jour ?",
  "graf.reparto.texto": "La part évitable est mesurée sur toute la période, pas jour par jour. Elle est répartie ici au prorata de ce que l’étape de chaque problème a dépensé chaque jour : les jours totalisent le chiffre du haut, et un jour où cette étape n’a pas tourné ne reçoit rien.",
  "graf.sin_repartir": "{coste} évitables n’ont pas pu être répartis : leur étape n’a pas de dépense tarifée sur cette période.",
  "graf.pasos": "Coût par étape",
  "graf.otros": "Autres étapes",
  "graf.paso.evitable": "{evitable} évitables",
  // Textos que pinta el CSS (`content:`): el proveedor de idioma los pasa como variables.
  "css.porque": "pourquoi ?",
  "css.avanzado": "avancé",
  // El grafo del agente en la vista de traza (D-153).
  "grafo.titulo": "Comment l’agent est construit",
  "grafo.lead": "Un bloc par étape et une flèche pour chaque étape qui en appelle une autre, avec le nombre de fois dans cette exécution.",
  "grafo.aria": "Graphe de l’agent avec {pasos} étapes",
  "grafo.llamadas_one": "{n} appel",
  "grafo.llamadas_other": "{n} appels",
  "grafo.errores_one": "{n} en erreur",
  "grafo.errores_other": "{n} en erreur",
  "grafo.tipo.agent": "agent",
  "grafo.tipo.llm": "modèle",
  "grafo.tipo.tool": "outil",
  "grafo.tipo.retrieval": "recherche",
  "grafo.tipo.chain": "étape",
  "grafo.tipo.otro": "autre",
  "grafo.sin_tarifa": "sans tarif",
  "grafo.al_menos": "≥ {coste}",
  "aj.regla.prompt_caro": "Prompt plus cher",
  "diag.ahorrado_one": "Vous avez déjà cessé de payer {coste} depuis que vous avez corrigé un problème.",
  "diag.ahorrado_other": "Vous avez déjà cessé de payer {coste} depuis que vous avez corrigé {n} problèmes.",
  "diag.ahorrado.suelo": "au moins {coste}",
  "ciclo.titulo": "Où en est ce problème",
  "ciclo.detectar": "Détecter",
  "ciclo.probar": "Tester",
  "ciclo.arreglar": "Corriger",
  "ciclo.verificar": "Vérifier",
  "ciclo.estado.hecho": "fait",
  "ciclo.estado.en_curso": "en cours",
  "ciclo.estado.pendiente": "à faire",
  "ciclo.estado.fallo": "n’a pas marché",
  "ciclo.detectar.hecho": "Nous l’avons trouvé dans vos traces.",
  "ciclo.probar.pendiente": "Testez la correction sur ses appels réels avant de changer quoi que ce soit.",
  "ciclo.probar.conjunto": "Ses exécutions sont enregistrées dans « {nombre} » ; il reste à lancer le test.",
  "ciclo.probar.hecho_one": "{n} passe sur « {nombre} ».",
  "ciclo.probar.hecho_other": "{n} passes sur « {nombre} ».",
  "ciclo.probar.sin_paso": "Ce problème ne concerne pas une seule étape : testez-le sur l’agent entier.",
  "ciclo.arreglar.pendiente": "Appliquez la correction et marquez-la ici.",
  "ciclo.arreglar.hecho": "Marqué comme corrigé le {fecha}.",
  "ciclo.verificar.pendiente": "Nous le vérifions tout seuls dès qu’il y a des exécutions après la correction.",
  "ciclo.ignorado": "Vous l’avez ignoré : le cycle s’arrête ici.",
  "seg.probar.texto.prompt": "La différence de coût est mesurée ; que la v{a} soit aussi juste que la v{b}, non. Enregistrez les exécutions réelles de cette étape comme jeu de cas et lancez-les avec chaque version : Tester vous dira laquelle est la plus juste et ce que coûte chacune.",
  "seg.probar.texto.otro": "L’économie est mesurée ; que l’agent corrigé réponde aussi bien, non. Enregistrez les exécutions réelles de cette étape comme jeu de cas et lancez-les avec la correction en place : Tester vous dira s’il est aussi juste et combien il coûte en moins.",
  "seg.probar.existe": "Déjà enregistrées : « {nombre} », {n} cas.",
  "seg.probar.arreglado": "corrigé",
  "prob.prompt.titulo": "Revenez à la v{a} depuis Prompts",
  "prob.prompt.texto": "La fiche de « {prompt} » montre les deux versions avec ce que coûte et la justesse de chacune, et met la v{a} en production en un clic.",
  "prob.prompt.ir": "Ouvrir « {prompt} » dans Prompts →",
  "pr.hallazgo": "Il apparaît dans le Diagnostic : {titulo}.",
  "pr.hallazgo.ver": "Voir le problème →",
  "ev.por_probar.titulo": "Corrections à tester",
  "ev.por_probar.lead": "Les problèmes ouverts du Diagnostic, avec ce qu’ils rapportent et s’ils ont déjà leur test. Enregistrer leurs exécutions crée le jeu de cas avec les appels réels de cette étape.",
  "ev.por_probar.sin_probar": "non testé",
  "ev.por_probar.guardado": "enregistré, sans passe",
  "ev.por_probar.probado_one": "{n} passe",
  "ev.por_probar.probado_other": "{n} passes",
  "ev.por_probar.guardar": "Enregistrer ses exécutions",
  "ev.por_probar.guardado_como": "Enregistré sous « {nombre} ». Lancez-le avec la correction en place :",
  "ev.por_probar.ver": "Voir le problème",
  "ev.por_probar.error": "impossible d’enregistrer",
  "aj.contraste.alto": "Contraste élevé",
  "aj.contraste.texto": "Fonds opaques, sans transparence ni flou, et texte au contraste maximal. Fonctionne avec le thème clair comme avec le sombre.",
};
