import type { Mensajes } from "./es";

export const pt: Mensajes = {
  "tiempo.dias_one": "{n} dia",
  "tiempo.dias_other": "{n} dias",
  "tiempo.horas_one": "{n} hora",
  "tiempo.horas_other": "{n} horas",
  "tiempo.minutos_one": "{n} minuto",
  "tiempo.minutos_other": "{n} minutos",
  "tiempo.menos_de_un_minuto": "menos de um minuto",
  "ventana.dias_one": "o último dia",
  "ventana.dias_other": "os últimos {n} dias",
  "ventana.horas_one": "a última hora",
  "ventana.horas_other": "as últimas {n} horas",
  "ventana.minutos_one": "o último minuto",
  "ventana.minutos_other": "os últimos {n} minutos",
  "relativo.ahora": "agora mesmo",
  "relativo.min": "há {n} min",
  "relativo.h": "há {n} h",
  "relativo.d": "há {n} d",

  "nav.diagnostico": "Diagnóstico",
  "nav.trazas": "Traces",
  "nav.panel": "Painel",
  "nav.evaluaciones": "Testar",
  "nav.prompts": "Prompts",
  "nav.ajustes": "Configurações",

  "barra.proyecto": "Projeto",
  "barra.sin_proyectos": "Sem projetos",
  "barra.rango": "Intervalo de tempo",
  "barra.idioma": "Idioma",
  "barra.avanzado": "Avançado",
  "barra.avanzado_ayuda": "Mostra a camada técnica: consultas, atributos, identificadores",
  "barra.tu_cuenta": "Sua conta: {email}",
  "barra.organizacion": "Organização e conta",
  "barra.salir": "Sair",
  "rango.1": "24 horas",
  "rango.7": "7 dias",
  "rango.30": "30 dias",

  "estado.sin_backend.titulo": "Não conseguimos conectar ao backend",
  "estado.sin_backend.texto":
    "Ele não responde. Se você está rodando localmente, inicie com {local}; na instalação completa, com {docker}.",
  "estado.reintentar": "Tentar de novo",
  "estado.sin_proyecto.titulo": "Ainda não há nenhum projeto",
  "estado.sin_proyecto.texto":
    "Assim que seu agente enviar a primeira execução, ela aparecerá aqui. Instrumentá-lo é uma linha:",
  "estado.primer_proyecto":
    "Nesta instalação o agente precisa de uma chave para enviar traces. {enlace}: ali mesmo aparece o trecho acima com a chave preenchida.",
  "estado.primer_proyecto.enlace": "Crie-a em Organização",
  "estado.demo.texto":
    "Só quer ver funcionando? Carregue alguns traces de exemplo (dados inventados, em um projeto separado chamado “demo”) e veja o que ele detecta.",
  "estado.demo.cargando": "Carregando…",
  "estado.demo.boton": "Carregar dados de exemplo",
  "estado.demo.terminal": "Em um terminal: {comando}.",
  "estado.demo.error": "não foi possível carregá-los",
  "estado.sin_trazas.titulo": "Aguardando a primeira execução de “{proyecto}”",
  "estado.sin_trazas.texto":
    "Nenhum trace deste projeto chegou ainda. Assim que você executar seu agente com o Laplace ativado, ele aparecerá aqui:",
  "estado.nada.titulo_con_aviso": "Não encontramos nada para corrigir, mas não conseguimos olhar tudo",
  "estado.nada.titulo": "Você não está desperdiçando dinheiro agora",
  "estado.nada.texto":
    "Procuramos chamadas repetidas, etapas que usam um modelo mais caro do que precisam e contexto reenviado sem necessidade. Não há nada disso neste intervalo.",
  "estado.clave.titulo": "Esta instalação exige uma chave",
  "estado.clave.sin_clave":
    "Se você não tem uma, quem administra esta organização a cria, em Organização → Chaves.",
  "estado.clave.guardar": "Salvar e entrar",
  "estado.clave.con_cuenta": "Entrar com sua conta",
  "estado.clave.cookie":
    "Ela é verificada e guardada em um cookie que só este Laplace vê: nem a página nem nenhum script podem lê-la, e ela nunca vai na URL, porque o que vai na URL acaba nos logs de qualquer proxy por onde passe.",
  "estado.ajeno.titulo": "Sua chave não dá acesso a este projeto",
  "estado.ajeno.texto": "Esta chave serve para outro projeto desta instalação.",
  "estado.ajeno.otra": "Usar outra chave",
  "estado.volver": "Voltar",
  "diag.titulo": "Seu agente “{proyecto}”",
  "diag.al_ritmo": "No ritmo observado durante {ventana}",
  "diag.en_datos": "Em {tiempo} de dados",
  "diag.costara": "vai custar este mês",
  "diag.ha_costado": "custou até agora",
  "diag.contexto": "Contexto",
  "diag.cobertura": "Cobertura",
  "diag.metricas": "Métricas",
  "diag.m.p95": "Latência p95",
  "diag.m.errores": "Execuções com erro",
  "diag.m.tokens": "Tokens",
  "diag.m.trazas": "Traces",
  "diag.m.pasos": "Etapas",
  "diag.m.coste": "Custo por execução",
  "diag.m.cache": "Já economizado pelo cache",
  "diag.m.datos": "Dados observados",
  "diag.nada.aviso": "Com essa cobertura, “não há nada para corrigir” significa “não sabemos”, não “está tudo bem”.",
  "diag.nada.gastado": "Você já gastou {coste} em {ejecuciones} execuções.",
  "diag.ver_trazas": "Ver todos os traces",
  "diag.cosas_one": "Uma coisa para corrigir",
  "diag.cosas_other": "{n} coisas para corrigir",
  "comun.exportar_csv": "Exportar CSV",
  "diag.orden": "Da que mais dinheiro devolve à que menos devolve.",
  "diag.cifras_proyeccion": "Os valores são a projeção para 30 dias do ritmo observado durante {ventana}.",
  "diag.cifras_gastado": "Os valores são dinheiro já gasto durante {ventana}.",
  "diag.nota.proyeccion": "Os valores são uma estimativa a partir dos dados coletados durante {ventana}, projetada para 30 dias. Se seu tráfego mudar, eles mudam.",
  "diag.nota.gastado": "Os valores são dinheiro {ya} durante {ventana}, não uma projeção: não há dados suficientes para estimar o mês.",
  "diag.nota.ya_gastado": "já gasto",
  "diag.nota.moneda": "O custo está em {moneda} porque é a moeda em que os provedores faturam.",
  "diag.ver_mas_one": "Ver mais um",
  "diag.ver_mas_other": "Ver mais {n}",
  "diag.tiempo_one": "E um que não custa dinheiro, só tempo",
  "diag.tiempo_other": "E {n} que não custam dinheiro, só tempo",
  "diag.presupuesto": "Orçamento",
  "diag.presupuesto.invitar": "{enlace} e avisamos antes de você passar.",
  "diag.presupuesto.enlace": "Defina um orçamento mensal",
  "diag.presupuesto.aria": "{n} por cento do orçamento",
  "estado.arreglado": "Corrigido",
  "estado.ignorado": "Ignorado",
  "estado.desaparecido": "Não ocorre mais",
  "diag.apartados_one": "Um problema que não está mais pendente",
  "diag.apartados_other": "{n} problemas que não estão mais pendentes",
  "diag.desaparecido": "Não ocorre desde {fecha}. Não conta como economia: corrigi-lo não devolveria mais nada.",
  "diag.ignorado_coste": "{coste} no intervalo, que não contam como evitável.",
  "csv.abierto": "aberto",
  "csv.si": "sim",
  "csv.no": "não",
  "csv.h.problema": "Problema",
  "csv.h.tipo": "Tipo",
  "csv.h.estado": "Status",
  "csv.h.gastado": "Já gasto (USD)",
  "csv.h.al_mes": "Por mês (USD)",
  "csv.h.suelo": "É um piso",
  "csv.h.tokens": "Tokens a mais",
  "csv.h.espera": "Espera evitável (s)",
  "csv.h.ejecuciones": "Execuções afetadas",
  "csv.h.arreglo": "Correção",
  "csv.nombre.problemas": "problemas",
  "piezas.gap.aria": "{necesario} de custo necessário, {evitable} evitável",
  "piezas.gap.real": "{coste} de trabalho real",
  "piezas.gap.tirando": "{coste} que você está jogando fora",
  "piezas.puesto": "Posição {n}",
  "piezas.tokens_de_mas": "tokens a mais",
  "piezas.espera": "de espera evitável",
  "piezas.al_mes": "por mês",
  "piezas.ya_gastado": "já gasto",
  "piezas.reaparecido": "Você marcou como corrigido e continua aparecendo.",
  "piezas.marcado": "Marcado como corrigido.",
  "piezas.sin_tarifa": "Gasta tokens; sem preço para dar um valor",
  "piezas.suelo": "É um piso: o custo real pode ser maior",
  "piezas.sin_verificar": "Com preço não verificado",
  "piezas.ver_arreglo": "Ver como corrigir →",
  "avisos.casi_todo": "Quase tudo o que você gasta está apontado aqui embaixo:",
  "avisos.casi_todo.cifras": "{evitable} de {total} ({pct}).",
  "avisos.casi_todo.porque": "Por que não apresentamos isso como economia?",
  "avisos.casi_todo.texto": "Porque “você pode deixar de pagar seu agente” quase nunca é o que significa. O que costuma haver por trás é um agente pequeno ou recém-lançado em que duas ou três etapas são praticamente a fatura inteira, e corrigi-las muda essas etapas, não o agente inteiro. Veja o detalhamento de cada problema antes de contar com este valor.",
  "avisos.no_lo_usas": "não usa",
  "avisos.pct_aria": "{n} por cento",
  "avisos.de_llamadas": "{n} de {total} chamadas",
  "avisos.incompleto": "Este total está incompleto:",
  "avisos.incompleto.linea": "{n} etapas sem preço ({modelos}).",
  "avisos.incompleto.porque": "O modelo delas não está na nossa tabela de preços, então não sabemos quanto custam e não são somadas. Você pode definir um preço em Configurações, e o que já está salvo é recalculado.",
  "avisos.suelo": "É um piso:",
  "avisos.suelo.linea_one": "em {n} etapa cobramos a tarifa padrão.",
  "avisos.suelo.linea_other": "em {n} etapas cobramos a tarifa padrão.",
  "avisos.suelo.porque": "Contexto longo, residência de dados ou modo rápido são cobranças à parte que a resposta do provedor nem sempre revela. O custo real pode ser um pouco maior, nunca menor. Em cada etapa, no modo avançado, diz-se qual é a dúvida.",
  "avisos.proyeccion": "Projeção a partir dos dados coletados durante {ventana}.",
  "avisos.proyeccion.porque": "É o que você vem enviando, não o intervalo que o seletor pede. Gasto e economia saem da mesma base: se um muda, o outro também.",
  "avisos.sin_proyectar": "Dinheiro já gasto, sem projeção.",
  "avisos.sin_proyectar.linea": "A previsão mensal aparece com {tiempo} de dados.",
  "avisos.sin_proyectar.porque": "Com os dados coletados durante {ventana}, multiplicar para chegar a 30 dias dá um valor que não se sustenta: um pico de dez minutos viraria centenas de dólares.",
  "avisos.mucho": "A economia estimada é {pct} do que você gasta.",
  "avisos.mucho.porque": "É muito: costuma acontecer em agentes pequenos ou recém-lançados, em que poucas etapas dominam a fatura. Antes de dar como certo, veja o detalhamento de cada problema.",
  "avisos.sin_dinero": "Não conseguimos calcular o dinheiro",
  "prob.no_aparece.titulo": "Esse problema não aparece mais",
  "prob.no_aparece.texto": "Ou você o corrigiu, ou ele deixou de acontecer no intervalo que você está vendo. Parabéns em qualquer dos casos.",
  "prob.que_pasa": "O que está acontecendo",
  "prob.deteccion": "Como detectamos",
  "prob.deteccion.nota": "É a consulta que foi executada, não uma versão de exemplo. Os limites das regras são os mesmos para todos os projetos: em Configurações se decide o que avisa, não o que se detecta.",
  "prob.traza": "O trace completo",
  "prob.traza.texto": "Uma execução real em que o problema aparece.",
  "prob.traza.abrir": "Abra para navegar etapa por etapa →",
  "prob.atributos": "Atributos da etapa apontada",
  "prob.arreglo": "Como corrigir",
  "prob.ahorro": "Quanto você economiza",
  "prob.ahorro.ya": "Durante {ventana} já foram {coste} por aqui.",
  "prob.ahorro.mes": "Nesse ritmo, corrigi-lo deixa de custar {coste}.",
  "prob.ahorro.al_mes": "{coste} por mês",
  "prob.ahorro.sin_mes": "Ainda não projetamos o mês: com {tiempo} de dados, multiplicar até 30 dias daria um valor que não se sustenta.",
  "prob.ahorro.suelo": "E é um {suelo}: há etapas aqui dentro cujo custo não conseguimos confirmar, então o valor real pode ser maior, nunca menor.",
  "prob.ahorro.suelo.palabra": "piso",
  "prob.ahorro.sin_verificar": "Não verificamos o preço de {modelos}: ele vem da tabela comunitária do LiteLLM e pode não coincidir com a sua fatura, para mais ou para menos.",
  "prob.ahorro.tokens": "Isto gasta {tokens} a mais e {espera} de espera no intervalo analisado. Quanto dinheiro é, não sabemos: {motivo}.",
  "prob.ahorro.tokens.n": "{n} tokens",
  "prob.ahorro.sin_tarifa": "esse modelo não tem preço conhecido",
  "prob.ahorro.tiempo": "Este problema não custa dinheiro: as etapas repetidas não consomem tokens. O que custa é espera, {espera} no intervalo analisado. Corrigi-lo faz seu agente responder mais rápido.",
  "prob.calculo": "Cálculo:",
  "prob.solo_lectura": "Sua função neste projeto ({rol}) permite vê-lo, não marcá-lo como corrigido nem ignorá-lo.",
  "prob.ver_afectadas": "Ver os traces afetados",
  "prob.ver_ultimas": "Ver as últimas execuções desta etapa",
  "tec.al_mes": "por mês se nada mudar",
  "tec.ya_gastados": "já gastos em {ventana}",
  "tec.espera": "de espera evitável em {ventana}",
  "tec.afectadas": "afetadas",
  "tec.vueltas_mas_one": "…mais {n} volta, todas com a mesma resposta.",
  "tec.vueltas_mas_other": "…mais {n} voltas, todas com a mesma resposta.",
  "tec.identicas_mas_one": "…mais {n} chamada idêntica, todas com a mesma resposta.",
  "tec.identicas_mas_other": "…mais {n} chamadas idênticas, todas com a mesma resposta.",
  "tec.tarifa_aplicada": "tarifa aplicada",
  "tec.tarifa_no_verificada": "preço não verificado",
  "tec.tarifa_asumida": "tarifa presumida",
  "seg.error.guardar": "não foi possível salvar",
  "seg.error.deshacer": "não foi possível desfazer",
  "seg.error.crear": "não foi possível criar",
  "seg.titulo.ignorado": "Você marcou como ignorado",
  "seg.titulo.reaparecido": "Você marcou como corrigido, e continua aparecendo",
  "seg.titulo.arreglado": "Você marcou como corrigido",
  "seg.fecha": "Em {fecha}.",
  "seg.antes": "Antes, por execução",
  "seg.despues": "Depois",
  "seg.ejecuciones": "{n} execuções",
  "seg.ignorado.nota": "Não conta no evitável do início nem manda alertas.",
  "seg.deshacer": "Desfazer e devolver à lista",
  "seg.ya_arreglado": "Você já corrigiu?",
  "seg.ya_arreglado.texto": "Marque e nós verificamos: comparamos quanto custava cada execução antes com quanto custa depois. Se continuar aparecendo igual, volta à lista.",
  "seg.nota.placeholder": "Por que não é um problema (opcional)",
  "seg.ignorar": "Ignorar este problema",
  "comun.cancelar": "Cancelar",
  "seg.arreglado.boton": "Já corrigi: verifique",
  "seg.no_problema": "Não é um problema para mim",
  "seg.probar.titulo": "Antes de trocar, verifique",
  "seg.probar.texto": "A economia está medida; que {modelo} responda igualmente bem, não. Salve as execuções reais desta etapa e reenvie as chamadas delas para {modelo} com o comando abaixo: roda na sua máquina, com a sua chave e um teto de gasto, e o juiz compara cada resposta com a original. Testar dirá se acerta igual e quanto custa menos.",
  "seg.probar.barato": "o modelo barato",
  "seg.probar.ir": "Ir para Testar →",
  "seg.probar.crear": "Criar o conjunto “{nombre}” com estas execuções",
  "seg.tokens": "{n} tokens",
  "trazas.orden.coste": "Mais caros primeiro",
  "trazas.orden.reciente": "Mais recentes",
  "trazas.orden.duracion": "Mais lentos",
  "trazas.tipo.cualquiera": "Qualquer etapa",
  "trazas.tipo.llm": "Com chamada a modelo",
  "trazas.tipo.tool": "Com ferramenta",
  "trazas.tipo.retrieval": "Com busca",
  "trazas.titulo": "Traces",
  "trazas.lead": "Cada linha é uma execução completa do seu agente. Ordenadas pelo custo.",
  "trazas.buscar.contenido": "Buscar um pedido, uma frase, um id…",
  "trazas.buscar.nombres": "Buscar por etapa, ferramenta ou id do trace",
  "trazas.buscar": "Buscar",
  "trazas.donde": "Onde buscar",
  "trazas.en_nombres": "Em nomes e id",
  "trazas.en_contenido": "Em prompts e respostas",
  "trazas.estado": "Status",
  "trazas.estado.cualquiera": "Qualquer status",
  "trazas.estado.error": "Só com erro",
  "trazas.estado.ok": "Só corretas",
  "trazas.tipo": "Tipo de etapa",
  "trazas.orden": "Ordem",
  "trazas.modelo": "Modelo",
  "trazas.modelo.cualquiera": "Qualquer modelo",
  "trazas.coste_minimo": "Custo mínimo",
  "trazas.coste_minimo.aria": "Custo mínimo em USD",
  "trazas.sesion.aria": "Identificador de sessão",
  "trazas.filtrar": "Filtrar",
  "trazas.corta": "Para buscar em prompts e respostas, digite pelo menos {n} caracteres.",
  "trazas.filtro.paso": "Só as execuções que passam pela etapa do problema: {paso}",
  "trazas.filtro.usuario": "Só as execuções do usuário {usuario}",
  "trazas.quitar": "Remover",
  "trazas.ninguna": "Nenhum trace corresponde",
  "trazas.ninguna.texto": "Tente remover filtros ou ampliar o intervalo de tempo na barra acima.",
  "trazas.quitar_filtros": "Remover filtros",
  "csv.h.traza": "Trace",
  "csv.h.agente": "Agente",
  "csv.h.inicio": "Início",
  "csv.h.sesion": "Sessão",
  "csv.h.usuario": "Usuário",
  "csv.h.pasos": "Etapas",
  "csv.h.tok_entrada": "Tokens de entrada",
  "csv.h.tok_salida": "Tokens de saída",
  "csv.h.coste": "Custo (USD)",
  "csv.h.incompleto": "Custo incompleto",
  "csv.h.duracion": "Duração (ms)",
  "csv.h.modelos": "Modelos",
  "csv.nombre.trazas": "traces",
  "lista.n_trazas": "{n} traces",
  "lista.en_pausa": " · pausado",
  "lista.cada": "Verificado a cada {n} segundos",
  "lista.vivo.necesita": "O modo ao vivo precisa da ordem por mais recentes: ao clicar, ela muda",
  "lista.vivo.pausar": "Ao vivo · pausar",
  "lista.vivo.ver": "Ver ao vivo",
  "lista.col.traza": "Trace",
  "lista.col.modelos": "Modelos",
  "lista.col.pasos": "Etapas",
  "lista.col.tokens": "Tokens",
  "lista.col.entrada": "Entrada",
  "lista.col.salida": "Saída",
  "lista.col.coste": "Custo",
  "lista.col.duracion": "Duração",
  "lista.col.cuando": "Quando",
  "lista.col.bien": "Certo?",
  "lista.todas": " (todos do intervalo)",
  "lista.antiguas": "Mais antigos →",
  "lista.sin_backend": "O backend não responde; continuamos tentando.",
  "lista.nuevas_one": "{n} trace novo desde que você ligou.",
  "lista.nuevas_other": "{n} traces novos desde que você ligou.",
  "lista.esperando": "Aguardando novos traces.",
  "lista.ultima": "Última verificação: {fecha}.",
  "lista.con_error": "com erro",
  "lista.sin_nombre": "(sem nome)",
  "lista.bucle.ayuda": "Repete etapas com a mesma entrada",
  "lista.bucle": "loop",
  "lista.errores_one": "{n} erro",
  "lista.errores_other": "{n} erros",
  "lista.sesion": " · sessão {id}",
  "lista.coste_incompleto": "custo incompleto",
  "conj.creado": "Conjunto “{nombre}” criado com este filtro.",
  "conj.ir": "Ir para Testar",
  "conj.guardar": "Salvar estes traces como conjunto de casos",
  "conj.nombre.placeholder": "Nome, p. ex. regressoes-checkout",
  "conj.nombre.aria": "Nome do conjunto",
  "conj.creando": "Criando…",
  "conj.boton": "Salvar (até 50)",
  "traza.no_encontrada": "Não encontramos esse trace",
  "traza.no_encontrada.texto": "Talvez o identificador esteja errado, ou o trace seja anterior ao que é mantido.",
  "traza.todas": "Todos os traces",
  "traza.problemas_one": "Nesta execução acontece um problema detectado:",
  "traza.problemas_other": "Nesta execução acontecem {n} problemas detectados:",
  "traza.estado.ignorado": "ignorado",
  "traza.estado.reaparecido": "marcado como corrigido, mas continua",
  "traza.estado.arreglado": "marcado como corrigido",
  "traza.bien": "Esta execução está certa?",
  "traza.juez.sin_tarifa": "Julgada com {modelo}. Não sabemos o custo: esse modelo não está na tabela de preços.",
  "traza.juez.coste": "Julgada com {modelo}. Custou {coste}.",
  "traza.juez.error": "o juiz não conseguiu opinar",
  "traza.juez.juzgando": "Julgando…",
  "traza.juez.opine": "Pedir a opinião de {modelo}",
  "traza.juez.ocultar": "Ocultar o prompt do juiz",
  "traza.juez.ver": "Ver o prompt do juiz",
  "traza.exportar": "Exportar trace em JSON",
  "traza.usuario": " · usuário {id}",
  "traza.coste.faltan": "custo (faltam {n} etapas sem preço)",
  "traza.coste.sin_verificar": "custo (preço não verificado)",
  "traza.coste": "custo",
  "traza.tokens": "tokens entrada / saída",
  "traza.duracion": "duração",
  "traza.pasos": "etapas",
  "traza.llamadas": "chamadas a modelo",
  "traza.herramientas": "ferramentas",
  "traza.modelos": "modelos",
  "traza.cache_tokens": "tokens servidos do cache",
  "traza.cache_ahorro": "economizados pelo cache",
  "traza.asumida": "etapas com tarifa presumida",
  "traza.errores": "erros",
  "arbol.titulo": "Árvore de execução",
  "arbol.n_de": "{n} de {total} etapas",
  "arbol.teclas": "↑↓ mover · ←→ recolher",
  "arbol.plegar_todo": "Recolher tudo",
  "arbol.desplegar_todo": "Expandir tudo",
  "arbol.desplegar": "expandir",
  "arbol.plegar": "recolher",
  "arbol.misma_llamada": "Mesma chamada com a mesma entrada",
  "arbol.selecciona": "Selecione uma etapa da árvore.",
  "arbol.prompt": "Prompt ({n})",
  "arbol.respuesta": "Resposta ({n})",
  "arbol.argumentos": "Argumentos",
  "arbol.salida": "Saída",
  "arbol.consulta": "Consulta",
  "arbol.documentos": "Documentos ({n})",
  "arbol.entrada": "Entrada",
  "arbol.eventos": "Eventos ({n})",
  "arbol.evento": "evento",
  "arbol.modelo": "modelo",
  "arbol.tok_entrada": "tokens entrada",
  "arbol.tok_entrada_est": "tokens entrada (estimados)",
  "arbol.tok_salida": "tokens saída",
  "arbol.tok_salida_est": "tokens saída (estimados)",
  "arbol.sin_precio": "preço desconhecido",
  "arbol.coste_minimo": "custo mínimo (tarifa presumida)",
  "arbol.desde_cache": "do cache ({coste})",
  "arbol.escritos_cache": "escritos no cache ({coste})",
  "arbol.ahorro_cache": "economizados pelo cache",
  "arbol.rama.pasos": "etapas do ramo",
  "arbol.rama.error": "com erro",
  "arbol.rama.tokens": "tokens do ramo",
  "arbol.rama.coste": "custo do ramo",
  "arbol.mensaje": "mensagem",
  "arbol.contenido": "conteúdo",
  "arbol.raiz": "(raiz)",
  "arbol.estimados": "true (nós contamos)",
  "arbol.del_proveedor": "false (do provedor)",
  "arbol.ninguna": "nenhuma: modelo desconhecido",
  "arbol.atributos": "Atributos brutos",
  "arbol.sin_contenido": "Sem conteúdo.",
  "arbol.copiado": "copiado",
  "arbol.copiar": "copiar",
  "arbol.misma_entrada": "Mesma chamada, mesma entrada",
  "ver.buena": "Marcar esta execução como boa",
  "ver.mala": "Marcar esta execução como ruim",
  "ver.solo_ver": "Sua função só permite ver",
  "ver.bien": "Certo",
  "ver.mal": "Errado",
  "ver.ocultar": "Ocultar comentário",
  "ver.ver": "Ver comentário",
  "ver.comentar": "Comentar",
  "ver.placeholder": "O que falhou, ou por que está certo. É salvo ao marcar.",
  "ver.nota": "O comentário é salvo com o veredito: clique de novo em “{bien}” ou “{mal}” depois de escrevê-lo.",
  "ver.juez": "juiz",
  "ver.no_guardado": "não foi salvo",
  "ver.maquina": "veredito de máquina",
  "ver.juez_dice": "juiz: {v}",
  "ver.bien_min": "certo",
  "ver.mal_min": "errado",
  "ver.coste_desconocido": " custo desconhecido",
  "ver.persona": "pessoa: {v}",
  "panel.titulo": "Seu agente “{proyecto}”, por unidade de trabalho",
  "panel.por_ejecucion": "Por execução",
  "panel.por_ejecucion.lead": "Quanto custa uma execução do seu agente. É o valor que importa: um gasto que sobe porque há mais trabalho não é um problema, e isto separa as duas coisas.",
  "panel.totales": "Totais, como contexto",
  "panel.totales.lead": "Estão aqui embaixo de propósito: sozinhos não dizem se algo vai mal.",
  "panel.error.cargar": "não foi possível carregar",
  "panel.quien": "Quem gasta mais",
  "panel.agrupar": "Agrupar por",
  "panel.usuarios": "Usuários",
  "panel.sesiones": "Sessões",
  "panel.sin_usuario": "Nenhuma execução deste intervalo diz de qual usuário é. Com {codigo} no seu agente, aqui você verá para quem vai o gasto.",
  "panel.sin_sesion": "Nenhuma execução deste intervalo diz de qual sessão é. Com {codigo} no seu agente, aqui você verá para quem vai o gasto.",
  "panel.col.usuario": "Usuário",
  "panel.col.sesion": "Sessão",
  "panel.col.ejecuciones": "Execuções",
  "panel.col.por_ejecucion": "Por execução",
  "panel.col.total": "Total",
  "panel.col.del_gasto": "Do gasto",
  "panel.sin_etiqueta_usuario": "Além disso, {n} execuções sem usuário ({coste}).",
  "panel.sin_etiqueta_sesion": "Além disso, {n} execuções sem sessão ({coste}).",
  "panel.menos_de": "< {x}",
  "panel.sin_comparacion": "sem comparação",
  "panel.vs_anterior": "{cambio} vs. o período anterior",
  "panel.grafica.titulo": "Custo por execução, em trechos de {tramo}",
  "panel.grafica.coste": "custo por execução",
  "panel.grafica.ejecuciones": "execuções",
  "panel.grafica.aria": "Custo por execução por trecho",
  "panel.grafica.punto": "{fecha} · {coste} por execução · {n} execuções",
  "panel.grafica.desde": " · desde o primeiro dado",
  "panel.grafica.nota": "Os trechos sem execuções ficam em branco. Não é custo zero: é que não houve nada para executar, e desenhá-lo como zero mostraria uma queda que não existiu.",
  "panel.picos": "Picos",
  "panel.picos.ninguno": "Nenhum trecho foge do normal neste intervalo. O custo por execução se mantém dentro do habitual.",
  "panel.picos.n_one": "Um trecho foge do normal",
  "panel.picos.n_other": "{n} trechos fogem do normal",
  "panel.picos.lead": "Trechos em que cada execução custou muito mais do que o normal. Do mais caro ao menos caro.",
  "panel.pico.cuando": "Começou em {inicio} e durou até as {fin}",
  "panel.pico.de_mas": "a mais",
  "panel.pico.texto_one": "Nesse trecho cada execução custou {coste}, contra os {base} habituais: {veces} sobre {n} execução.",
  "panel.pico.texto_other": "Nesse trecho cada execução custou {coste}, contra os {base} habituais: {veces} sobre {n} execuções.",
  "panel.pico.veces": "{n} vezes mais",
  "panel.pico.ver_prompt": "ver esse prompt",
  "panel.pico.ver_trazas": "Ver os traces desse trecho",
  "panel.pico.orden": "Ordenados por custo, do mais caro ao mais barato",
  "panel.pico.tramo": "trecho",
  "panel.pico.base": "linha de base",
  "panel.pico.mediana": "mediana dos trechos com execuções",
  "ev.titulo": "Teste as correções de “{proyecto}” antes de implantá-las",
  "ev.lead": "É o segundo passo do ciclo: o Diagnóstico diz quanto uma correção devolve; aqui se verifica, com as chamadas reais dessa etapa, que o agente acerta igual com a correção aplicada.",
  "ev.conj.titulo": "Conjuntos de casos",
  "ev.conj.lead": "Coleções de execuções {reales} do seu agente. Não há casos inventados aqui: cada um sai de um trace que aconteceu, e dá para abri-lo e ver de onde veio.",
  "ev.conj.reales": "reais",
  "ev.conj.nombre": "Nome",
  "ev.conj.cuantas": "Quantos traces",
  "ev.conj.crear": "Criar a partir dos mais recentes",
  "ev.conj.otro_filtro": "Quer outro filtro? Filtre no {explorador} e clique em “{guardar}”: o conjunto guarda o filtro com que foi formado, para depois se poder discutir de onde saiu.",
  "ev.explorador": "explorador",
  "ev.conj.ninguno": "Ainda não há nenhum.",
  "ev.conj.col.conjunto": "Conjunto",
  "ev.conj.col.casos": "Casos",
  "ev.conj.col.filtro": "Filtro de origem",
  "ev.conj.col.creado": "Criado",
  "ev.conj.sin_filtro": "sem filtro (os mais recentes)",
  "ev.borrar": "Apagar",
  "ev.tiradas": "Rodadas",
  "ev.tiradas.lead": "Cada uma é uma passada de um conjunto por uma versão do seu agente. O SDK as lança no seu processo; aqui só chegam o relatório e os traces.",
  "ev.col.version": "Versão",
  "ev.col.conjunto": "Conjunto",
  "ev.col.casos": "Casos",
  "ev.col.personas": "Pessoas",
  "ev.col.juez": "Juiz",
  "ev.col.coste": "Custo",
  "ev.col.juzgar": "Julgar custou",
  "ev.col.cuando": "Quando",
  "ev.sin_tiradas": "Sem rodadas de uma versão nova? Lance com {codigo} apontando para este mesmo Laplace. Os traces gerados aparecem no {explorador} como qualquer outro, e o projeto é “{proyecto}”.",
  "ev.entre": "entre {bajo} e {alto}",
  "ev.error.comparar": "não foi possível comparar",
  "ev.paso1": "Salve um conjunto de casos",
  "ev.paso1.texto": "Execuções reais do seu agente. No {explorador}, filtre e clique em “{guardar}”, ou crie aqui embaixo com as mais recentes.",
  "ev.paso2": "Rode com a versão atual",
  "ev.paso2.texto": "A rodada é lançada pelo SDK no seu processo (o Laplace não executa seu agente):",
  "ev.paso3": "E de novo com a versão nova",
  "ev.paso3.texto": "Outro prompt, outro modelo: a mesma linha com outro {variant}. Com as duas rodadas, aqui aparece a comparação de acerto e custo. O acerto vem das suas anotações ou do juiz automático.",
  "ev.comparar.titulo": "Comparar duas versões",
  "ev.comparar.pasos": "Três passos, e cada um se marca sozinho quando está feito.",
  "ev.comparar.lead": "Acerto e custo ao mesmo tempo. As duas rodadas precisam ser do mesmo conjunto: comparar o acerto sobre casos diferentes não diria nada.",
  "ev.a": "A — a de referência",
  "ev.b": "B — a nova",
  "ev.elige": "Escolha uma rodada",
  "ev.elige_a": "Escolha A primeiro",
  "ev.n_casos": "{n} casos",
  "ev.comparando": "Comparando…",
  "ev.comparar": "Comparar",
  "ev.discrepan": "As pessoas e o juiz não dizem o mesmo.",
  "ev.discrepan.texto": "Não é uma falha do produto: é o dado mais interessante que esta tela pode dar. Ou o juiz está medindo outra coisa, ou quem anotou e quem escreveu o prompt do juiz não entendem “certo” da mesma forma. Veja os casos antes de confiar em qualquer um dos dois.",
  "ev.costo": "Quanto custou cada uma",
  "ev.costo.lead": "Isto não tem margem: não é uma amostra, é a fatura do que foi executado. Se você gerencia seus prompts no Laplace, embaixo de cada lado verá {enlace}, lida dos traces e não do rótulo que você deu à rodada.",
  "ev.costo.enlace": "com qual versão rodou",
  "ev.juzgar_dos": "Julgar as duas rodadas com {modelo}",
  "ev.cuesta": "Custa dinheiro: você saberá quanto assim que terminar",
  "ev.tec.conjunto": "conjunto",
  "ev.tec.casos": "casos",
  "ev.fuente.personas": "Pessoas",
  "ev.fuente.juez": "Juiz (modelo)",
  "ev.de": "{a} de {b}",
  "ev.sin_anotar": " · {n} sem anotação",
  "ev.wilson": "entre {bajo} e {alto} (Wilson, 95%)",
  "ev.por_caso": "por caso",
  "ev.tec.total": "total",
  "ev.tec.tokens": "tokens",
  "ev.tec.duracion": "duração",
  "ev.tec.reventados": "com falha",
  "ev.juez_costo": "Julgar esta rodada custou {coste} à parte{desconocido}. É gasto nosso, não do seu agente, e por isso vai separado.",
  "ev.juez_desconocido": " (e há vereditos cujo custo não sabemos)",
  "pr.titulo": "Os prompts de “{proyecto}”",
  "pr.lead": "Cada versão com quanto custou e quanto acertou sobre o tráfego real que a usou, para decidir qual deixar em produção com os dois números à frente.",
  "pr.error.abrir": "não foi possível abrir",
  "pr.error.version": "não foi possível trocar a versão",
  "pr.en_produccion": "v{n} em produção",
  "pr.cerrar": "Fechar",
  "pr.ver_versiones": "Ver versões e diff",
  "pr.reserva_one": "{n} execução rodou com o texto de reserva.",
  "pr.reserva_other": "{n} execuções rodaram com o texto de reserva.",
  "pr.reserva.texto": "Significa que seu agente não conseguiu pedir o prompt ao Laplace e usou o que está no código. Esse tráfego é contado à parte, não dentro da versão em produção: somá-lo ali falsearia justamente o valor que você está vendo.",
  "pr.acierto.nota": "O acerto de uma versão é o das {enteras} em que participou, não o deste prompt isolado. Uma execução passa por várias etapas e, quando dá errado, ninguém mediu qual delas a estragou. É um sinal útil, não uma divisão de culpas.",
  "pr.acierto.enteras": "execuções inteiras",
  "pr.tec.versiones": "versões",
  "pr.tec.creado": "criado",
  "pr.col.version": "Versão",
  "pr.col.por_ejecucion": "Por execução",
  "pr.col.ejecuciones": "Execuções",
  "pr.col.tokens": "Tokens/exec.",
  "pr.col.ultimo": "Último uso",
  "pr.produccion": "produção",
  "pr.poner": "Colocar em produção",
  "pr.ocultar_mudas": "Ocultar as versões sem tráfego",
  "pr.ver_mudas_one": "Ver {n} versão que não rodou neste intervalo",
  "pr.ver_mudas_other": "Ver {n} versões que não rodaram neste intervalo",
  "pr.wilson": "{bajo}–{alto} (Wilson)",
  "pr.nuevo": "Tirar um prompt do código",
  "pr.nuevo.lead": "O nome é com o qual você vai pedi-lo: {codigo}. A primeira versão entra em produção sozinha; a partir da segunda, salvar e implantar são dois gestos.",
  "pr.nombre": "Nome",
  "pr.nuevo.placeholder": "Você é um assistente que responde em {{idioma}} e em menos de três frases.",
  "pr.crear": "Criar e colocar em produção",
  "pr.que_cambio": "O que mudou",
  "pr.de": "De",
  "pr.a": "Para",
  "pr.elige_dos": "Escolha duas versões diferentes para ver o diff. Com uma só não há nada para comparar.",
  "pr.texto_v": "O texto da v{n}",
  "pr.guardar_nueva": "Salvar uma versão nova",
  "pr.guardar_nueva.lead": "Salvar não implanta. São dois gestos diferentes de propósito: é o que permite preparar uma versão com calma e o que faz existir o botão de voltar atrás.",
  "pr.texto.placeholder": "O texto do prompt. Use {{variable}} para o que mudar em cada chamada.",
  "pr.guardando": "Salvando…",
  "pr.guardar": "Salvar versão",
  "pr.guardada": "Fica salva, não servida",
  "pr.historial": "Histórico de implantações",
  "pr.col.cuando": "Quando",
  "pr.col.quien": "Quem",
  "pr.col.nota": "Nota",
  "pr.vuelta_atras": "reversão",
  "pr.historial.nota": "Este histórico conta a história; {no} atribui picos. Para isso, o {panel} usa a versão que aparece nos traces do trecho, que é um fato medido e não uma coincidência de horários.",
  "pr.no": "não",
  "pr.panel": "painel",
  "pr.borrar": "Apagar este prompt",
  "pr.borrar.nota": "Os traces não são alterados: continuarão dizendo com qual versão rodaram",
  "pr.sin_adoptar": "Você ainda não gerencia nenhum prompt aqui",
  "pr.sin_adoptar.1": "Seus prompts vivem no seu código, que é um lugar perfeitamente razoável. O que se perde com isso é poder responder “quanto custava o de antes e quanto acertava?”, porque um {blame} sabe o que mudou e não sabe o que aconteceu depois.",
  "pr.sin_adoptar.2": "Se você os mover para cá, o SDK os serve e deixa escrito em cada trace com qual versão foi executado. {nada}: só te dá o texto, e se o Laplace não responder, o SDK usa a cópia salva ou o texto de reserva que você passar.",
  "pr.sin_adoptar.nada": "O Laplace continua sem executar nada seu",
  "pr.sin_adoptar.3": "Enquanto isso, aqui embaixo está o que dá para saber dos seus traces: quais etapas mudaram de instruções e quando.",
  "pr.obs.titulo": "O que se vê nos seus traces",
  "pr.obs.nada": "Nada ainda.",
  "pr.obs.gestion": "Isto vem dos traces, não da gestão de prompts: são os conjuntos de instruções com que cada etapa foi vista rodando. Serve para ver se algo mudou por fora daqui.",
  "pr.obs.sin_gestion": "Cada etapa do seu agente e os conjuntos de instruções com que foi vista rodando neste intervalo. Se uma etapa muda de instruções entre uma execução e outra, é uma mudança de prompt: não sabemos o texto inteiro (só guardamos o começo), mas sabemos quando mudou e quanto custou.",
  "pr.obs.cambio": "Vê uma mudança que não reconhece? {enlace} e veja as instruções completas dessas execuções.",
  "pr.obs.abrir": "Abra no explorador",
  "pr.obs.no_versiones": "não são versões",
  "pr.obs.llamadas": "chamadas em cada execução",
  "pr.obs.juego_one": "conjunto de instruções",
  "pr.obs.juego_other": "conjuntos de instruções",
  "pr.obs.col.instrucciones": "Instruções (começo)",
  "pr.obs.col.desde": "Desde",
  "pr.obs.col.hasta": "Até",
  "pr.obs.sin_instrucciones": "(sem instruções capturadas)",
  "comun.guardar": "Salvar",
  "comun.quitar": "Remover",
  "aj.titulo": "Configurações de “{proyecto}”",
  "aj.lead": "Orçamento, alertas, preços e dados. Cada bloco é salvo separadamente.",
  "aj.solo_lectura": "Orçamento, alertas e apagar o projeto são alterados por um admin da organização. Sua função ({rol}) permite vê-los.",
  "aj.pres.guardado": "Orçamento salvo.",
  "aj.pres.quitado": "Orçamento removido.",
  "aj.pres.titulo": "Orçamento mensal",
  "aj.pres.lead": "Sobre o mês civil, que é o que o provedor fatura. Avisa em 80% e 100% pelos canais abaixo, uma vez cada por mês.",
  "aj.pres.dolares": "Dólares por mês",
  "aj.error.borrar": "não foi possível apagar",
  "aj.datos": "Dados",
  "aj.datos.retencion": "Esta instalação guarda os traces por {n} dias; o que for anterior é apagado sozinho todo dia.",
  "aj.datos.siempre": "Esta instalação guarda os traces para sempre. Para apagar o antigo automaticamente, inicie-a com LAPLACE_RETENTION_DAYS.",
  "aj.ret.dias": "Dias que este projeto guarda",
  "aj.ret.guardado": "Guardado: este projeto guarda {n} dias; o anterior é apagado uma vez por dia.",
  "aj.ret.quitado": "Removido: este projeto guarda o que a instalação disser.",
  "aj.ret.explica": "Um projeto pode guardar menos que a instalação, não mais. O anterior é apagado uma vez por dia.",
  "aj.ret.manda_instalacion": "A instalação guarda {n} dias e vale a mais curta: este projeto guarda {n}.",
  "aj.sujeto.titulo": "Apagar os dados de uma pessoa ou de um cliente.",
  "aj.sujeto.texto": "Apaga os traces inteiros em que o id aparece, não só os passos que o levam. Não pode ser desfeito. Repita o id para confirmar.",
  "aj.sujeto.tipo": "O que se apaga",
  "aj.sujeto.persona": "Uma pessoa (user_id)",
  "aj.sujeto.cliente": "Um cliente (customer_id)",
  "aj.sujeto.id": "Id da pessoa ou do cliente",
  "aj.sujeto.repite": "Repita o id",
  "aj.sujeto.boton": "Apagar os traces",
  "aj.sujeto.borrado": "Apagados {n} traces de «{id}».",
  "aj.borrar.titulo": "Apagar “{proyecto}” inteiro.",
  "aj.borrar.texto": "Traces, anotações, conjuntos de casos, prompts, orçamento e alertas. Não pode ser desfeito. Digite o nome do projeto para confirmar.",
  "aj.borrar.aria": "Nome do projeto para confirmar",
  "aj.borrar.boton": "Apagar o projeto",
  "aj.apariencia": "Aparência",
  "aj.en_navegador": "Fica salvo neste navegador.",
  "aj.tema": "Tema",
  "aj.tema.sistema": "Como o sistema",
  "aj.tema.claro": "Claro",
  "aj.tema.oscuro": "Escuro",
  "aj.euros": "Ver também em euros",
  "aj.euros.lead": "Os provedores faturam em dólares e esse continua sendo o valor. Se você definir uma taxa de câmbio, ao lado dos valores principais aparece o equivalente em euros com “≈”. A taxa é definida por você e fica salva só neste navegador: não a baixamos de lugar nenhum.",
  "aj.euros.tipo": "1 $ são … €",
  "aj.euros.guardado": "Taxa salva.",
  "aj.euros.desactivados": "Euros desativados.",
  "aj.tar.guardada": "Preço de {modelo} salvo. {n} chamadas já salvas agora têm seu custo.",
  "aj.tar.quitada": "Preço de {modelo} removido.",
  "aj.error.quitar": "não foi possível remover",
  "aj.tar.titulo": "Preços próprios",
  "aj.tar.lead": "Para um modelo que não está na nossa tabela, ou com preço negociado. Em dólares por milhão de tokens, da página do provedor. Ao salvar, também é recalculado o que você já tinha enviado. Se o modelo roda na sua máquina, não lhe dê preço: ninguém te cobra.",
  "aj.tar.instalacion": "Os preços valem para toda a instalação: só uma chave de instalação pode alterá-los.",
  "aj.tar.sin_tarifa": "Sem preço agora:",
  "aj.tar.modelo": "Modelo",
  "aj.tar.entrada": "Entrada",
  "aj.tar.salida": "Saída",
  "aj.tar.entrada_m": "Entrada ($/M)",
  "aj.tar.salida_m": "Saída ($/M)",
  "aj.tar.guardar": "Salvar preço",
  "aj.al.prueba_ok": "Mensagem de teste enviada. Veja no canal.",
  "aj.al.prueba_mal": "Não chegou por nenhum canal. Revise os endereços.",
  "aj.al.error.probar": "não foi possível testar",
  "aj.al.titulo": "Alertas",
  "aj.al.lead": "Uma mensagem quando um problema passa do limite em dinheiro já gasto. O mesmo aviso nunca se repete dentro do período de silêncio, e o que você marcar como corrigido ou ignorado não avisa.",
  "aj.al.silenciadas": "Silenciados para este projeto.",
  "aj.al.activas": "Ativos.",
  "aj.al.apagadas": "Desligados: coloque pelo menos um canal.",
  "aj.al.slack_guardado": "Webhook do Slack salvo.",
  "aj.al.slack_quitado": "Slack removido.",
  "aj.al.webhook_titulo": "Webhook (Teams, Discord, n8n…)",
  "aj.al.webhook_guardado": "Webhook salvo.",
  "aj.al.webhook_quitado": "Webhook removido.",
  "aj.al.correo": "E-mail",
  "aj.al.correo_placeholder": "equipe@empresa.com",
  "aj.al.correo_guardado": "E-mail salvo.",
  "aj.al.correo_quitado": "E-mail removido.",
  "aj.al.smtp": "Falta o servidor de e-mail da instalação: inicie o Laplace com LAPLACE_SMTP_HOST, LAPLACE_SMTP_USER e LAPLACE_SMTP_PASSWORD.",
  "aj.al.umbral": "Limite (dólares já gastos)",
  "aj.al.calma": "Silêncio por problema (horas)",
  "aj.al.umbral_guardado": "Limite e silêncio salvos.",
  "aj.al.que_avisa": "O que avisa",
  "aj.al.reglas_guardadas": "Regras salvas.",
  "aj.al.probar": "Enviar uma mensagem de teste",
  "aj.al.reactivadas": "Alertas reativados.",
  "aj.al.silenciadas_ok": "Alertas silenciados.",
  "aj.al.reactivar": "Reativar",
  "aj.al.silenciar": "Silenciar este projeto",
  "aj.al.puesto": " · definido ({actual})",
  "aj.al.otro": "Cole outro para trocá-lo",
  "aj.regla.repeticion": "Repetições",
  "aj.regla.bucle": "Loops",
  "aj.regla.modelo_caro": "Modelo caro",
  "aj.regla.contexto_fijo": "Contexto sem cache",
  "titulo.ajustes": "Configurações",
  "titulo.configurar": "Configurar",
  "titulo.entrar": "Entrar",
  "titulo.evaluaciones": "Testar",
  "titulo.invitacion": "Convite",
  "titulo.organizacion": "Organização",
  "titulo.panel": "Painel",
  "titulo.problema": "Problema",
  "titulo.prompts": "Prompts",
  "titulo.traza": "Trace",
  "titulo.trazas": "Traces",
  "rol.lector": "leitor",
  "rol.miembro": "membro",
  "rol.admin": "admin",
  "rol.propietario": "proprietário",
  "org.error.cargar": "não foi possível carregar",
  "org.local.titulo": "O modo local não tem contas",
  "org.local.texto": "É um processo na sua máquina com seus traces: não há mais ninguém a quem dar acesso. Contas, funções e chaves existem na instalação em nuvem.",
  "org.tu_cuenta": "Sua conta",
  "org.eres": "Você é {rol} desta organização.",
  "org.sin_org": "Você ainda não pertence a nenhuma organização: peça um convite.",
  "org.org": "Organização",
  "org.miembros": "Membros",
  "org.col.persona": "Pessoa",
  "org.col.rol": "Função",
  "org.col.desde": "Desde",
  "org.tu": " · você",
  "org.rol_de": "Função de {email}",
  "org.ahora_es": "{email} agora é {rol}.",
  "org.salir_confirm": "Sair da organização?",
  "org.quitar_confirm": "Remover {email}?",
  "org.hecho": "Feito.",
  "org.salir": "Sair",
  "org.roles.nota": "Leitor: vê. Membro: além disso anota execuções, marca problemas e gerencia prompts e conjuntos. Admin: além disso membros, chaves, alertas, orçamento e apagar. Remover alguém encerra suas sessões na hora.",
  "org.invitar": "Convidar",
  "org.email": "E-mail",
  "org.email_placeholder": "pessoa@empresa.com",
  "org.enviado": "Enviamos o link por e-mail. Você também pode copiá-lo:",
  "org.sin_correo": "Esta instalação não tem e-mail configurado: envie você mesmo este link. Só é mostrado agora e expira em 7 dias.",
  "org.pendientes": "Pendentes",
  "org.caduca": "expira em {fecha}",
  "org.anulada": "Convite cancelado.",
  "org.anular": "Cancelar",
  "org.acc.configurar_instalacion": "configurou a instalação",
  "org.acc.login": "entrou",
  "org.acc.login_fallido": "tentativa de entrada falhou",
  "org.acc.invitar": "convidou",
  "org.acc.anular_invitacion": "cancelou o convite de",
  "org.acc.aceptar_invitacion": "aceitou o convite como",
  "org.acc.cambiar_rol": "mudou a função de",
  "org.acc.quitar_miembro": "removeu",
  "org.acc.crear_clave": "criou uma chave para",
  "org.acc.revocar_clave": "revogou a chave",
  "org.acc.borrar_proyecto": "apagou o projeto",
  "org.registro": "Registro de atividade",
  "org.cargando": "Carregando…",
  "org.nada": "Nada ainda.",
  "org.alguien": "alguém",
  "org.admin_instalacion": " · você administra esta instalação",
  "org.pass_actual": "Senha atual",
  "org.pass_nueva": "Nova (10 caracteres ou mais)",
  "org.pass_cambiada": "Senha alterada. As outras sessões foram encerradas.",
  "org.pass_cambiar": "Alterar senha",
  "org.cerrar_todo": "Sair em todos os dispositivos",
  "org.error.generico": "não foi possível",
  "cla.titulo": "Chaves de API",
  "cla.lead": "Uma chave por projeto: é com ela que seu agente envia traces. Digite um nome de projeto novo para criá-lo.",
  "cla.proyecto": "Projeto",
  "cla.para_que": "Para que serve",
  "cla.para_que_placeholder": "ingestão produção",
  "cla.caduca": "Expira",
  "cla.nunca": "nunca",
  "cla.30": "em 30 dias",
  "cla.90": "em 90 dias",
  "cla.365": "em um ano",
  "cla.crear": "Criar chave",
  "cla.copiala": "Copie agora:",
  "cla.copiala.texto": "só se guarda a impressão dela e não dá para vê-la de novo. Se perdê-la, revogue e crie outra.",
  "cla.col.nombre": "Nome",
  "cla.col.ultimo": "Último uso",
  "cla.no_caduca": "não expira",
  "cla.revocar_confirm": "Revogar “{nombre}”? Deixa de funcionar na hora.",
  "cla.revocada": "Chave revogada.",
  "cla.revocar": "Revogar",
  "cla.rotar": "Para rotar uma chave: crie a nova, troque no seu agente e revogue a antiga.",
  "cla.copiado": "Copiado",
  "cla.copiar": "Copiar",
  "ent.error": "não foi possível entrar",
  "ent.titulo": "Entrar no Laplace",
  "ent.contrasena": "Senha",
  "ent.entrando": "Entrando…",
  "ent.entrar": "Entrar",
  "ent.sin_cuenta": "Não tem conta? Peça um convite a quem administra sua organização.",
  "ent.tengo_clave": "Tenho uma chave de API",
  "ent.comprobando": "Verificando…",
  "ent.usar_clave": "Usar a chave",
  "conf.error": "não foi possível configurar",
  "conf.titulo": "Configure esta instalação",
  "conf.texto": "Ainda não há nenhuma conta. A primeira administra a instalação inteira e fica com os projetos que já tenham dados.",
  "conf.codigo": "Código de configuração",
  "conf.codigo.ayuda": "Está no log do servidor, na linha “no hay ninguna cuenta todavía”. Com Docker: {comando}",
  "conf.org": "Nome da sua organização",
  "conf.org_placeholder": "Minha empresa",
  "conf.nombre": "Seu nome",
  "conf.contrasena": "Senha (10 caracteres ou mais)",
  "conf.creando": "Criando…",
  "conf.crear": "Criar a conta de administração",
  "inv.puede.lector": "ver os dados dos projetos",
  "inv.puede.miembro": "ver, anotar execuções, marcar problemas e gerenciar prompts",
  "inv.puede.admin": "tudo o que foi dito, mais membros, chaves, alertas e orçamento",
  "inv.puede.propietario": "tudo, incluindo tornar e deixar de ser proprietários",
  "inv.no_vale": "esse convite não vale",
  "inv.error": "não foi possível aceitar",
  "inv.no_vale.titulo": "Este convite não vale",
  "inv.no_vale.texto": "{motivo}. Os convites expiram em sete dias e só servem uma vez: peça outro a quem te convidou.",
  "inv.unete": "Entre em “{org}”",
  "inv.como": "Como {rol}: você poderá {puede}.",
  "inv.con_cuenta": "Você já tem conta com este e-mail: sua senha",
  "inv.elige": "Escolha uma senha (10 caracteres ou mais)",
  "inv.uniendote": "Entrando…",
  "inv.aceptar": "Aceitar o convite",
  "nf.titulo": "Esta página não existe",
  "nf.texto": "O link pode estar errado, ou apontar para algo que não existe mais.",
  "nf.ir": "Ir para o diagnóstico",
  "err.titulo": "Algo falhou ao carregar esta tela",
  "err.texto": "Não conseguimos preparar os dados. Costuma ser coisa de um momento: tente de novo e, se continuar igual, verifique se o backend está no ar.",
  "prob.paso_titulo": "{titulo}.",
  // Errores de la API que no traen una frase propia.
  "api.fallo": "Erro {estado} em {ruta}",
  "api.no_valida": "A requisição não é válida: {campos}",
  // A1: un rango vacío no es un proyecto vacío.
  "estado.rango_vacio.titulo": "Nenhuma execução durante {ventana}",
  "estado.rango_vacio.ultima": "A última chegou em {fecha}.",
  "estado.rango_vacio.fuera": "A última chegou em {fecha}, antes dos {rango} que dá para ver aqui. Execute seu agente com o Laplace ativado para ver dados novos.",
  "estado.rango_vacio.boton": "Ver {ventana}",
  // Menos texto (D-151): el héroe, el distintivo de confianza y la ficha.
  "diag.puedes.proy": "Você pode deixar de pagar até",
  "diag.puedes.al_mes": "por mês",
  "diag.puedes.gastado": "Você poderia ter economizado até",
  "diag.puedes.en": "em {tiempo}",
  "diag.de_total.proy": "dos {total} que vai custar este mês, no ritmo de {ventana}.",
  "diag.de_total.gastado": "dos {total} gastos em {tiempo} de dados.",
  "conf.alta": "Confiança alta",
  "conf.media": "Confiança média",
  "conf.baja": "Confiança baixa",
  "conf.notas_one": "{n} nota",
  "conf.notas_other": "{n} notas",
  "conf.alta.texto": "Todo o gasto tem tarifa conhecida e a parte evitável não é desproporcional.",
  "conf.media.texto": "O número é confiável, mas leia-o com estas notas.",
  "conf.baja.texto": "Falta parte do gasto ou não conseguimos ver bem este agente: não tome o número como definitivo.",
  "prob.por_que.plegado": "Por que acontece?",
  "prob.ahorro.como": "Como é calculado?",
  // Gráficos del Diagnóstico (D-152).
  "graf.titulo": "Para onde vai o dinheiro",
  "graf.dia": "Gasto por dia",
  "graf.hora": "Gasto por hora",
  "graf.real": "trabalho real",
  "graf.evitable": "evitável",
  "graf.punto": "{fecha}: {coste}, dos quais {evitable} evitáveis",
  "graf.aria": "Gasto por período com a parte evitável por cima",
  "graf.reparto": "Como a parte evitável é distribuída pelos dias?",
  "graf.reparto.texto": "A parte evitável é medida sobre todo o intervalo, não dia a dia. Aqui ela é distribuída na proporção do que a etapa de cada problema gastou em cada dia: os dias somam o número de cima, e um dia em que essa etapa não trabalhou não recebe nada.",
  "graf.sin_repartir": "{coste} evitáveis não puderam ser distribuídos: a etapa não tem gasto com tarifa neste intervalo.",
  "graf.pasos": "Custo por etapa",
  "graf.otros": "Outras etapas",
  "graf.paso.evitable": "{evitable} evitáveis",
  // Textos que pinta el CSS (`content:`): el proveedor de idioma los pasa como variables.
  "css.porque": "por quê?",
  "css.avanzado": "avançado",
  // El grafo del agente en la vista de traza (D-153).
  "grafo.titulo": "Como o agente é construído",
  "grafo.lead": "Um bloco por etapa e uma seta para cada etapa que chama outra, com quantas vezes fez isso nesta execução.",
  "grafo.aria": "Grafo do agente com {pasos} etapas",
  "grafo.llamadas_one": "{n} chamada",
  "grafo.llamadas_other": "{n} chamadas",
  "grafo.errores_one": "{n} com erro",
  "grafo.errores_other": "{n} com erro",
  "grafo.tipo.agent": "agente",
  "grafo.tipo.llm": "modelo",
  "grafo.tipo.tool": "ferramenta",
  "grafo.tipo.retrieval": "busca",
  "grafo.tipo.chain": "etapa",
  "grafo.tipo.otro": "outro",
  "grafo.sin_tarifa": "sem tarifa",
  "grafo.al_menos": "≥ {coste}",
  "aj.regla.prompt_caro": "Prompt mais caro",
  "aj.regla.cache_compartida": "Cache não partilhado",
  "diag.ahorrado_one": "Você já deixou de pagar {coste} desde que corrigiu um problema.",
  "diag.ahorrado_other": "Você já deixou de pagar {coste} desde que corrigiu {n} problemas.",
  "diag.ahorrado.suelo": "pelo menos {coste}",
  "ciclo.titulo": "Onde está este problema",
  "ciclo.detectar": "Detectar",
  "ciclo.probar": "Testar",
  "ciclo.arreglar": "Corrigir",
  "ciclo.verificar": "Verificar",
  "ciclo.estado.hecho": "feito",
  "ciclo.estado.en_curso": "em andamento",
  "ciclo.estado.pendiente": "pendente",
  "ciclo.estado.fallo": "não funcionou",
  "ciclo.detectar.hecho": "Nós o encontramos nos seus traces.",
  "ciclo.probar.pendiente": "Teste a correção com as chamadas reais antes de mudar qualquer coisa.",
  "ciclo.probar.conjunto": "As execuções estão salvas em “{nombre}”; falta rodar o teste.",
  "ciclo.probar.hecho_one": "{n} rodada sobre “{nombre}”.",
  "ciclo.probar.hecho_other": "{n} rodadas sobre “{nombre}”.",
  "ciclo.probar.sin_paso": "Este problema não é de uma só etapa: teste-o no agente inteiro.",
  "ciclo.arreglar.pendiente": "Aplique a correção e marque-a aqui.",
  "ciclo.arreglar.hecho": "Marcado como corrigido em {fecha}.",
  "ciclo.verificar.pendiente": "Verificamos sozinhos quando houver execuções depois da correção.",
  "ciclo.ignorado": "Você o ignorou: o ciclo para aqui.",
  "seg.probar.texto.prompt": "A diferença de custo está medida; que a v{a} acerte igual à v{b}, não. Salve as execuções reais desta etapa como conjunto de casos e rode-as com cada versão: Testar dirá qual acerta mais e quanto custa cada uma.",
  "seg.probar.texto.otro": "A economia está medida; que o agente corrigido responda igualmente bem, não. Salve as execuções reais desta etapa como conjunto de casos e rode-as com a correção aplicada: Testar dirá se acerta igual e quanto custa menos.",
  "seg.probar.existe": "Já estão salvas: “{nombre}”, {n} casos.",
  "seg.probar.arreglado": "corrigido",
  "prob.prompt.titulo": "Volte para a v{a} pela aba Prompts",
  "prob.prompt.texto": "A ficha de “{prompt}” mostra as duas versões com quanto custa e quanto acerta cada uma, e coloca a v{a} em produção com um clique.",
  "prob.prompt.ir": "Abrir “{prompt}” em Prompts →",
  "pr.hallazgo": "Aparece no Diagnóstico: {titulo}.",
  "pr.hallazgo.ver": "Ver o problema →",
  "ev.por_probar.titulo": "Correções para testar",
  "ev.por_probar.lead": "Os problemas abertos do Diagnóstico, com o que devolvem e se já têm seu teste. Salvar as execuções cria o conjunto com as chamadas reais dessa etapa.",
  "ev.por_probar.sin_probar": "sem teste",
  "ev.por_probar.guardado": "salvo, sem rodada",
  "ev.por_probar.probado_one": "{n} rodada",
  "ev.por_probar.probado_other": "{n} rodadas",
  "ev.por_probar.guardar": "Salvar as execuções",
  "ev.por_probar.guardado_como": "Salvo como “{nombre}”. Rode-o com a correção aplicada:",
  "ev.por_probar.ver": "Ver o problema",
  "ev.por_probar.error": "não foi possível salvar",
  "aj.contraste.alto": "Alto contraste",
  "aj.contraste.texto": "Fundos opacos, sem transparências nem desfoque, e texto com o máximo de contraste. Vale para o tema claro e para o escuro.",
  "arbol.envoltorio": "O mesmo que “{hijo}”, que está dentro: esta etapa só o envolve.",
  "nav.clientes": "Clientes",
  "titulo.clientes": "Clientes",
  "cl.titulo": "Margem por cliente de “{proyecto}”",
  "cl.lead": "Quanto cada cliente paga frente ao que custa o trabalho dele, por mês. O custo sai das execuções; quanto paga, você informa.",
  "cl.aviso_one": "Este cliente faz você perder dinheiro",
  "cl.aviso_other": "Estes {n} clientes fazem você perder dinheiro",
  "cl.aviso.texto": "O trabalho deles custa mais do que pagam. Veja quais problemas do Diagnóstico acontecem nas execuções deles, ou revise o preço.",
  "cl.h.cliente": "Cliente",
  "cl.h.ejecuciones": "Execuções",
  "cl.h.coste": "Custo por mês",
  "cl.h.ingresos": "Paga por mês ($)",
  "cl.h.margen": "Margem por mês",
  "cl.estado.pierde": "dá prejuízo",
  "cl.estado.ajustado": "margem apertada",
  "cl.estado.gana": "dá margem",
  "cl.estado.sin-ingresos": "sem receita",
  "cl.estado.sin-proyeccion": "poucos dados",
  "cl.estado.sin-trafico": "sem execuções",
  "cl.ingresos.aria": "Quanto {cliente} paga por mês, em dólares",
  "cl.guardar": "Salvar",
  "cl.error.guardar": "não foi possível salvar",
  "cl.sin_cliente": "{coste} de {n} execuções não dizem de qual cliente são: contam à parte, sem repartir.",
  "cl.como.titulo": "Como dizer de qual cliente é cada execução",
  "cl.como.texto": "Uma linha antes de o agente trabalhar para esse cliente. Rodadas de avaliação não contam: não são trabalho de nenhum cliente.",
  "cl.anadir": "Informar quanto paga um cliente que ainda não chegou",
  "cl.anadir.id": "Cliente",
  "cl.anadir.importe": "Paga por mês ($)",
  "diag.clientes": "Clientes",
  "diag.clientes.pierden_one": "{n} cliente faz você perder dinheiro.",
  "diag.clientes.pierden_other": "{n} clientes fazem você perder dinheiro.",
  "diag.clientes.ver": "Ver a margem por cliente",
  "trazas.filtro.cliente": "Só as execuções do cliente {cliente}",
  "cl.problemas": "Acontece nas execuções dele:",
  "cl.ver_ejecuciones": "Ver as execuções →",
  "aj.regla.cliente_pierde": "Cliente que dá prejuízo",
  "cl.stripe.titulo": "Receita do Stripe",
  "cl.stripe.lead": "Em vez de digitar: quanto cada cliente paga sai das faturas pagas no último mês, levado a um mês (um plano anual conta um doze avos). Cada cliente do Stripe é casado com o dos seus traces por metadata.laplace_customer_id, ou pelo id. Basta uma chave restrita com leitura de faturas e clientes.",
  "cl.stripe.clave": "Chave do Stripe",
  "cl.stripe.puesta": "Chave definida ({pista}).",
  "cl.stripe.ultima": "Última vez: {fecha}, {n} clientes.",
  "cl.stripe.nunca": "Ainda não foi trazido nada.",
  "cl.stripe.traer": "Trazer do Stripe",
  "cl.stripe.quitar": "Remover a chave",
  "cl.stripe.fuente": "Stripe",
};
