import type { Mensajes } from "./es";

// 中文没有单复数之分：`_one` 与 `_other` 写成一样。
export const zh: Mensajes = {
  "tiempo.dias_one": "{n} 天",
  "tiempo.dias_other": "{n} 天",
  "tiempo.horas_one": "{n} 小时",
  "tiempo.horas_other": "{n} 小时",
  "tiempo.minutos_one": "{n} 分钟",
  "tiempo.minutos_other": "{n} 分钟",
  "tiempo.menos_de_un_minuto": "不到一分钟",
  "ventana.dias_one": "过去 {n} 天",
  "ventana.dias_other": "过去 {n} 天",
  "ventana.horas_one": "过去 {n} 小时",
  "ventana.horas_other": "过去 {n} 小时",
  "ventana.minutos_one": "过去 {n} 分钟",
  "ventana.minutos_other": "过去 {n} 分钟",
  "relativo.ahora": "刚刚",
  "relativo.min": "{n} 分钟前",
  "relativo.h": "{n} 小时前",
  "relativo.d": "{n} 天前",

  "nav.diagnostico": "诊断",
  "nav.trazas": "追踪",
  "nav.panel": "面板",
  "nav.evaluaciones": "评估",
  "nav.prompts": "提示词",
  "nav.ajustes": "设置",

  "barra.proyecto": "项目",
  "barra.sin_proyectos": "暂无项目",
  "barra.rango": "时间范围",
  "barra.idioma": "语言",
  "barra.avanzado": "高级",
  "barra.avanzado_ayuda": "显示技术层：查询、属性、标识符",
  "barra.tu_cuenta": "你的账户：{email}",
  "barra.organizacion": "组织与账户",
  "barra.salir": "退出",
  "rango.1": "24 小时",
  "rango.7": "7 天",
  "rango.30": "30 天",

  "estado.sin_backend.titulo": "无法连接到后端",
  "estado.sin_backend.texto": "后端没有响应。本地运行请用 {local} 启动；完整安装请用 {docker}。",
  "estado.reintentar": "重试",
  "estado.sin_proyecto.titulo": "还没有任何项目",
  "estado.sin_proyecto.texto": "你的智能体发送第一次运行后，就会出现在这里。接入只需一行：",
  "estado.primer_proyecto":
    "在此安装中，智能体需要密钥才能发送追踪。{enlace}：那里会显示上面的代码片段，并已填好密钥。",
  "estado.primer_proyecto.enlace": "在“组织”中创建",
  "estado.demo.texto":
    "只想看看它如何工作？加载一些示例追踪（虚构数据，放在名为“demo”的单独项目中），看看它能发现什么。",
  "estado.demo.cargando": "加载中…",
  "estado.demo.boton": "加载示例数据",
  "estado.demo.terminal": "在终端中运行：{comando}。",
  "estado.demo.error": "无法加载",
  "estado.sin_trazas.titulo": "正在等待“{proyecto}”的第一次运行",
  "estado.sin_trazas.texto":
    "项目已存在，但在当前时间范围内没有收到任何追踪。可以在上方栏中扩大时间范围，或在启用 Laplace 的情况下运行你的智能体。",
  "estado.nada.titulo_con_aviso": "没有发现需要修复的问题，但我们没能检查全部内容",
  "estado.nada.titulo": "你现在没有在浪费钱",
  "estado.nada.texto":
    "我们查找了重复调用、使用了超出所需的昂贵模型的步骤，以及无故重复发送的上下文。在此时间范围内都没有。",
  "estado.clave.titulo": "此安装需要密钥",
  "estado.clave.sin_clave": "如果没有，请由本组织的管理员在“组织 → 密钥”中创建。",
  "estado.clave.guardar": "保存并进入",
  "estado.clave.con_cuenta": "使用账户登录",
  "estado.clave.cookie":
    "密钥会先经过校验，再保存在只有此 Laplace 能读取的 cookie 中：页面和任何脚本都无法读取它，也绝不会出现在 URL 里，因为 URL 中的内容会留在经过的每个代理的日志里。",
  "estado.ajeno.titulo": "你的密钥无权访问此项目",
  "estado.ajeno.texto": "此密钥属于本安装中的另一个项目。",
  "estado.ajeno.otra": "使用其他密钥",
  "estado.volver": "返回",
};
