import type { Mensajes } from "./es";

// 中文没有单复数之分：`_one` 与 `_other` 写成一样。
export const zh: Mensajes = {
  "tiempo.dias_one": "{n} 天",
  "tiempo.dias_other": "{n} 天",
  "tiempo.horas_one": "{n} 小时",
  "tiempo.horas_other": "{n} 小时",
  "tiempo.minutos_one": "{n} 分钟",
  "tiempo.minutos_other": "{n} 分钟",
  "tiempo.menos_de_un_minuto": "不到一分钟",
  "ventana.dias_one": "过去 {n} 天",
  "ventana.dias_other": "过去 {n} 天",
  "ventana.horas_one": "过去 {n} 小时",
  "ventana.horas_other": "过去 {n} 小时",
  "ventana.minutos_one": "过去 {n} 分钟",
  "ventana.minutos_other": "过去 {n} 分钟",
  "relativo.ahora": "刚刚",
  "relativo.min": "{n} 分钟前",
  "relativo.h": "{n} 小时前",
  "relativo.d": "{n} 天前",

  "nav.diagnostico": "诊断",
  "nav.trazas": "追踪",
  "nav.panel": "面板",
  "nav.evaluaciones": "测试",
  "nav.prompts": "提示词",
  "nav.ajustes": "设置",

  "barra.proyecto": "项目",
  "barra.sin_proyectos": "暂无项目",
  "barra.rango": "时间范围",
  "barra.idioma": "语言",
  "barra.avanzado": "高级",
  "barra.avanzado_ayuda": "显示技术层：查询、属性、标识符",
  "barra.tu_cuenta": "你的账户：{email}",
  "barra.organizacion": "组织与账户",
  "barra.salir": "退出",
  "rango.1": "24 小时",
  "rango.7": "7 天",
  "rango.30": "30 天",

  "estado.sin_backend.titulo": "无法连接到后端",
  "estado.sin_backend.texto": "后端没有响应。本地运行请用 {local} 启动；完整安装请用 {docker}。",
  "estado.reintentar": "重试",
  "estado.sin_proyecto.titulo": "还没有任何项目",
  "estado.sin_proyecto.texto": "你的智能体发送第一次运行后，就会出现在这里。接入只需一行：",
  "estado.primer_proyecto":
    "在此安装中，智能体需要密钥才能发送追踪。{enlace}：那里会显示上面的代码片段，并已填好密钥。",
  "estado.primer_proyecto.enlace": "在“组织”中创建",
  "estado.demo.texto":
    "只想看看它如何工作？加载一些示例追踪（虚构数据，放在名为“demo”的单独项目中），看看它能发现什么。",
  "estado.demo.cargando": "加载中…",
  "estado.demo.boton": "加载示例数据",
  "estado.demo.terminal": "在终端中运行：{comando}。",
  "estado.demo.error": "无法加载",
  "estado.sin_trazas.titulo": "正在等待“{proyecto}”的第一次运行",
  "estado.sin_trazas.texto":
    "该项目尚未收到任何追踪。只要在启用 Laplace 的情况下运行你的智能体，它就会出现在这里：",
  "estado.nada.titulo_con_aviso": "没有发现需要修复的问题，但我们没能检查全部内容",
  "estado.nada.titulo": "你现在没有在浪费钱",
  "estado.nada.texto":
    "我们查找了重复调用、使用了超出所需的昂贵模型的步骤，以及无故重复发送的上下文。在此时间范围内都没有。",
  "estado.clave.titulo": "此安装需要密钥",
  "estado.clave.sin_clave": "如果没有，请由本组织的管理员在“组织 → 密钥”中创建。",
  "estado.clave.guardar": "保存并进入",
  "estado.clave.con_cuenta": "使用账户登录",
  "estado.clave.cookie":
    "密钥会先经过校验，再保存在只有此 Laplace 能读取的 cookie 中：页面和任何脚本都无法读取它，也绝不会出现在 URL 里，因为 URL 中的内容会留在经过的每个代理的日志里。",
  "estado.ajeno.titulo": "你的密钥无权访问此项目",
  "estado.ajeno.texto": "此密钥属于本安装中的另一个项目。",
  "estado.ajeno.otra": "使用其他密钥",
  "estado.volver": "返回",
  "diag.titulo": "你的智能体“{proyecto}”",
  "diag.al_ritmo": "按{ventana}的速度",
  "diag.en_datos": "基于 {tiempo} 的数据",
  "diag.costara": "本月将花费",
  "diag.ha_costado": "到目前为止已花费",
  "diag.contexto": "背景信息",
  "diag.cobertura": "覆盖率",
  "diag.metricas": "指标",
  "diag.m.p95": "p95 延迟",
  "diag.m.errores": "出错的运行",
  "diag.m.tokens": "Token 数",
  "diag.m.trazas": "追踪数",
  "diag.m.pasos": "步骤数",
  "diag.m.coste": "每次运行成本",
  "diag.m.cache": "缓存已节省",
  "diag.m.datos": "已观察的数据",
  "diag.nada.aviso": "在这样的覆盖率下，“没有需要修复的问题”意味着“我们不知道”，而不是“一切正常”。",
  "diag.nada.gastado": "你已在 {ejecuciones} 次运行中花费 {coste}。",
  "diag.ver_trazas": "查看全部追踪",
  "diag.cosas_one": "1 个需要修复的问题",
  "diag.cosas_other": "{n} 个需要修复的问题",
  "comun.exportar_csv": "导出 CSV",
  "diag.orden": "按能帮你省下的钱从多到少排列。",
  "diag.cifras_proyeccion": "这些数字是按{ventana}推算的 30 天数据。",
  "diag.cifras_gastado": "这些数字是{ventana}内已经花掉的钱。",
  "diag.nota.proyeccion": "金额是根据{ventana}的数据推算到 30 天的估计。如果你的流量变化，金额也会变化。",
  "diag.nota.gastado": "金额是{ventana}内{ya}的钱，不是推算：数据还不足以估算整月。",
  "diag.nota.ya_gastado": "已经花掉",
  "diag.nota.moneda": "成本以 {moneda} 计，因为这是提供商计费使用的货币。",
  "diag.ver_mas_one": "再看 1 个",
  "diag.ver_mas_other": "再看 {n} 个",
  "diag.tiempo_one": "还有 1 个不花钱、只花时间的问题",
  "diag.tiempo_other": "还有 {n} 个不花钱、只花时间的问题",
  "diag.presupuesto": "预算",
  "diag.presupuesto.invitar": "{enlace}，超支前我们会提醒你。",
  "diag.presupuesto.enlace": "设置每月预算",
  "diag.presupuesto.aria": "预算的 {n}%",
  "estado.arreglado": "已修复",
  "estado.ignorado": "已忽略",
  "estado.desaparecido": "已不再发生",
  "diag.apartados_one": "1 个已不再待处理的问题",
  "diag.apartados_other": "{n} 个已不再待处理的问题",
  "diag.desaparecido": "自 {fecha} 起未再发生。不计入节省：现在修复也不会帮你省下任何钱。",
  "diag.ignorado_coste": "此范围内 {coste}，不计入可避免的花费。",
  "csv.abierto": "未解决",
  "csv.si": "是",
  "csv.no": "否",
  "csv.h.problema": "问题",
  "csv.h.tipo": "类型",
  "csv.h.estado": "状态",
  "csv.h.gastado": "已花费（USD）",
  "csv.h.al_mes": "每月（USD）",
  "csv.h.suelo": "是否为下限",
  "csv.h.tokens": "多余 token",
  "csv.h.espera": "可避免的等待（秒）",
  "csv.h.ejecuciones": "受影响的运行",
  "csv.h.arreglo": "修复方式",
  "csv.nombre.problemas": "problems",
  "piezas.gap.aria": "必要成本 {necesario}，可避免 {evitable}",
  "piezas.gap.real": "{coste} 是真实工作",
  "piezas.gap.tirando": "{coste} 被白白浪费",
  "piezas.puesto": "第 {n} 位",
  "piezas.tokens_de_mas": "多余 token",
  "piezas.espera": "可避免的等待",
  "piezas.al_mes": "每月",
  "piezas.ya_gastado": "已花费",
  "piezas.reaparecido": "你已标记为已修复，但它仍在出现。",
  "piezas.marcado": "已标记为已修复。",
  "piezas.sin_tarifa": "消耗 token；没有价格可以估算金额",
  "piezas.suelo": "这是下限：实际成本可能更高",
  "piezas.sin_verificar": "价格未经核实",
  "piezas.ver_arreglo": "查看修复方法 →",
  "avisos.casi_todo": "你的几乎全部花费都在下方被标出：",
  "avisos.casi_todo.cifras": "{total} 中的 {evitable}（{pct}）。",
  "avisos.casi_todo.porque": "为什么我们不把它当作节省来展示？",
  "avisos.casi_todo.texto": "因为“你可以不再为智能体付费”几乎从来不是它的意思。背后通常是一个小型或刚上线的智能体，其中两三个步骤几乎就是全部账单，修复它们改变的是这几个步骤，而不是整个智能体。在指望这个数字之前，先看看每个问题的明细。",
  "avisos.no_lo_usas": "未使用",
  "avisos.pct_aria": "{n}%",
  "avisos.de_llamadas": "{total} 次调用中的 {n} 次",
  "avisos.incompleto": "这个总数不完整：",
  "avisos.incompleto.linea": "{n} 个步骤没有价格（{modelos}）。",
  "avisos.incompleto.porque": "它们的模型不在我们的价格表中，所以不知道成本，也没有计入总数。你可以在“设置”里填写价格，已保存的数据会重新计算。",
  "avisos.suelo": "这是下限：",
  "avisos.suelo.linea_one": "有 {n} 个步骤按标准价格计费。",
  "avisos.suelo.linea_other": "有 {n} 个步骤按标准价格计费。",
  "avisos.suelo.porque": "长上下文、数据驻留或快速模式属于单独计费，提供商的响应并不总会说明。实际成本可能略高，但不会更低。在高级模式下，每个步骤都会说明存疑之处。",
  "avisos.proyeccion": "基于{ventana}的数据推算。",
  "avisos.proyeccion.porque": "这是你实际发送的数据量，而不是选择器要求的时间范围。花费和节省来自同一基础：一个变了，另一个也会变。",
  "avisos.sin_proyectar": "已花费的钱，未做推算。",
  "avisos.sin_proyectar.linea": "有 {tiempo} 的数据后才会显示月度预测。",
  "avisos.sin_proyectar.porque": "只有{ventana}的数据时，乘到 30 天得出的数字站不住脚：一个十分钟的峰值会变成几百美元。",
  "avisos.mucho": "估计节省占你花费的 {pct}。",
  "avisos.mucho.porque": "这个比例很高：通常出现在小型或刚上线的智能体中，少数几个步骤占了大部分账单。在当真之前，先看看每个问题的明细。",
  "avisos.sin_dinero": "无法计算金额",
  "prob.no_aparece.titulo": "该问题已不再出现",
  "prob.no_aparece.texto": "要么你已经修复了它，要么它在你查看的时间范围内不再发生。无论哪种情况，都恭喜你。",
  "prob.que_pasa": "发生了什么",
  "prob.deteccion": "我们如何发现的",
  "prob.deteccion.nota": "这是实际执行的查询，不是示例。规则阈值对所有项目都一样：“设置”决定的是哪些问题会提醒，而不是哪些会被检测到。",
  "prob.traza": "完整追踪",
  "prob.traza.texto": "一次能看到该问题的真实运行。",
  "prob.traza.abrir": "打开它逐步查看 →",
  "prob.atributos": "被标记步骤的属性",
  "prob.arreglo": "如何修复",
  "prob.ahorro": "能省多少",
  "prob.ahorro.ya": "在{ventana}中，这里已经花掉了 {coste}。",
  "prob.ahorro.mes": "按这个速度，修复后可不再花费{coste}。",
  "prob.ahorro.al_mes": "每月 {coste}",
  "prob.ahorro.sin_mes": "暂不推算整月：只有 {tiempo} 的数据，乘到 30 天得出的数字站不住脚。",
  "prob.ahorro.suelo": "而且这是{suelo}：这里有些步骤的成本无法确认，所以实际数字可能更高，但不会更低。",
  "prob.ahorro.suelo.palabra": "下限",
  "prob.ahorro.sin_verificar": "{modelos} 的价格我们没有核实：它来自 LiteLLM 的社区价格表，可能与你的账单不一致，偏高或偏低都有可能。",
  "prob.ahorro.tokens": "在所分析的范围内，这多消耗了 {tokens}，并增加了 {espera} 的等待。具体多少钱我们不知道：{motivo}。",
  "prob.ahorro.tokens.n": "{n} 个 token",
  "prob.ahorro.sin_tarifa": "该模型没有已知价格",
  "prob.ahorro.tiempo": "这个问题不花钱：重复的步骤不消耗 token。它花的是等待时间，在所分析的范围内共 {espera}。修复后你的智能体会更快作答。",
  "prob.calculo": "计算：",
  "prob.solo_lectura": "你在这个项目中的角色（{rol}）只能查看，不能标记为已修复或忽略。",
  "prob.ver_afectadas": "查看受影响的追踪",
  "prob.ver_ultimas": "查看该步骤最近的运行",
  "tec.al_mes": "若不做改变，每月",
  "tec.ya_gastados": "{ventana}内已花费",
  "tec.espera": "{ventana}内可避免的等待",
  "tec.afectadas": "受影响",
  "tec.vueltas_mas_one": "……还有 {n} 轮，答案都一样。",
  "tec.vueltas_mas_other": "……还有 {n} 轮，答案都一样。",
  "tec.identicas_mas_one": "……还有 {n} 次相同的调用，答案都一样。",
  "tec.identicas_mas_other": "……还有 {n} 次相同的调用，答案都一样。",
  "tec.tarifa_aplicada": "适用价格",
  "tec.tarifa_no_verificada": "价格未核实",
  "tec.tarifa_asumida": "假定价格",
  "seg.error.guardar": "无法保存",
  "seg.error.deshacer": "无法撤销",
  "seg.error.crear": "无法创建",
  "seg.titulo.ignorado": "你已标记为忽略",
  "seg.titulo.reaparecido": "你已标记为已修复，但它仍在出现",
  "seg.titulo.arreglado": "你已标记为已修复",
  "seg.fecha": "于 {fecha}。",
  "seg.antes": "之前（每次运行）",
  "seg.despues": "之后",
  "seg.ejecuciones": "{n} 次运行",
  "seg.ignorado.nota": "它不计入首页的可避免花费，也不会发送提醒。",
  "seg.deshacer": "撤销并放回列表",
  "seg.ya_arreglado": "已经修复了吗？",
  "seg.ya_arreglado.texto": "标记后我们会验证：比较每次运行之前和之后的成本。如果仍然照旧出现，它会回到列表中。",
  "seg.nota.placeholder": "为什么这不是问题（可选）",
  "seg.ignorar": "忽略此问题",
  "comun.cancelar": "取消",
  "seg.arreglado.boton": "我已修复：请验证",
  "seg.no_problema": "这对我来说不是问题",
  "seg.probar.titulo": "切换前先验证",
  "seg.probar.texto": "节省是实测的；但 {modelo} 能否答得一样好还不知道。把这个步骤的真实运行保存为案例集，用新模型运行：“测试”会告诉你它是否同样准确、便宜多少。",
  "seg.probar.barato": "便宜的模型",
  "seg.probar.ir": "前往“测试” →",
  "seg.probar.crear": "用这些运行创建“{nombre}”案例集",
  "seg.tokens": "{n} 个 token",
  "trazas.orden.coste": "最贵的在前",
  "trazas.orden.reciente": "最新的在前",
  "trazas.orden.duracion": "最慢的在前",
  "trazas.tipo.cualquiera": "任意步骤",
  "trazas.tipo.llm": "包含模型调用",
  "trazas.tipo.tool": "包含工具",
  "trazas.tipo.retrieval": "包含检索",
  "trazas.titulo": "追踪",
  "trazas.lead": "每一行都是智能体的一次完整运行，按成本排序。",
  "trazas.buscar.contenido": "搜索订单、一句话或 ID…",
  "trazas.buscar.nombres": "按步骤、工具或追踪 ID 搜索",
  "trazas.buscar": "搜索",
  "trazas.donde": "搜索范围",
  "trazas.en_nombres": "在名称和 ID 中",
  "trazas.en_contenido": "在提示词和回答中",
  "trazas.estado": "状态",
  "trazas.estado.cualquiera": "任意状态",
  "trazas.estado.error": "仅出错的",
  "trazas.estado.ok": "仅成功的",
  "trazas.tipo": "步骤类型",
  "trazas.orden": "排序",
  "trazas.modelo": "模型",
  "trazas.modelo.cualquiera": "任意模型",
  "trazas.coste_minimo": "最低成本",
  "trazas.coste_minimo.aria": "最低成本（USD）",
  "trazas.sesion.aria": "会话标识",
  "trazas.filtrar": "筛选",
  "trazas.corta": "要在提示词和回答中搜索，请至少输入 {n} 个字符。",
  "trazas.filtro.paso": "仅显示经过该问题步骤的运行：{paso}",
  "trazas.filtro.usuario": "仅显示用户 {usuario} 的运行",
  "trazas.quitar": "移除",
  "trazas.ninguna": "没有匹配的追踪",
  "trazas.ninguna.texto": "试试移除筛选条件，或在上方栏中扩大时间范围。",
  "trazas.quitar_filtros": "清除筛选",
  "csv.h.traza": "追踪",
  "csv.h.agente": "智能体",
  "csv.h.inicio": "开始时间",
  "csv.h.sesion": "会话",
  "csv.h.usuario": "用户",
  "csv.h.pasos": "步骤数",
  "csv.h.tok_entrada": "输入 token",
  "csv.h.tok_salida": "输出 token",
  "csv.h.coste": "成本（USD）",
  "csv.h.incompleto": "成本不完整",
  "csv.h.duracion": "耗时（毫秒）",
  "csv.h.modelos": "模型",
  "csv.nombre.trazas": "traces",
  "lista.n_trazas": "{n} 条追踪",
  "lista.en_pausa": " · 已暂停",
  "lista.cada": "每 {n} 秒检查一次",
  "lista.vivo.necesita": "实时模式需要按最新排序：点击后会自动切换",
  "lista.vivo.pausar": "实时 · 暂停",
  "lista.vivo.ver": "实时查看",
  "lista.col.traza": "追踪",
  "lista.col.modelos": "模型",
  "lista.col.pasos": "步骤",
  "lista.col.tokens": "Token",
  "lista.col.entrada": "输入",
  "lista.col.salida": "输出",
  "lista.col.coste": "成本",
  "lista.col.duracion": "耗时",
  "lista.col.cuando": "时间",
  "lista.col.bien": "是否正确？",
  "lista.todas": "（该范围内全部）",
  "lista.antiguas": "更早的 →",
  "lista.sin_backend": "后端没有响应，正在重试。",
  "lista.nuevas_one": "开启以来有 {n} 条新追踪。",
  "lista.nuevas_other": "开启以来有 {n} 条新追踪。",
  "lista.esperando": "正在等待新的追踪。",
  "lista.ultima": "上次检查：{fecha}。",
  "lista.con_error": "出错",
  "lista.sin_nombre": "（未命名）",
  "lista.bucle.ayuda": "用相同输入重复步骤",
  "lista.bucle": "循环",
  "lista.errores_one": "{n} 个错误",
  "lista.errores_other": "{n} 个错误",
  "lista.sesion": " · 会话 {id}",
  "lista.coste_incompleto": "成本不完整",
  "conj.creado": "已用此筛选条件创建案例集“{nombre}”。",
  "conj.ir": "前往“测试”",
  "conj.guardar": "将这些追踪保存为案例集",
  "conj.nombre.placeholder": "名称，例如 checkout-regressions",
  "conj.nombre.aria": "案例集名称",
  "conj.creando": "正在创建…",
  "conj.boton": "保存（最多 50 条）",
  "traza.no_encontrada": "找不到该追踪",
  "traza.no_encontrada.texto": "可能是标识符有误，或者该追踪早于保留期限。",
  "traza.todas": "全部追踪",
  "traza.problemas_one": "这次运行中出现了 1 个已检测到的问题：",
  "traza.problemas_other": "这次运行中出现了 {n} 个已检测到的问题：",
  "traza.estado.ignorado": "已忽略",
  "traza.estado.reaparecido": "已标记为已修复，但仍在发生",
  "traza.estado.arreglado": "已标记为已修复",
  "traza.bien": "这次运行是否正确？",
  "traza.juez.sin_tarifa": "已用 {modelo} 评审。成本未知：该模型不在价格表中。",
  "traza.juez.coste": "已用 {modelo} 评审。花费 {coste}。",
  "traza.juez.error": "评审模型无法给出判断",
  "traza.juez.juzgando": "评审中…",
  "traza.juez.opine": "让 {modelo} 评审",
  "traza.juez.ocultar": "隐藏评审提示词",
  "traza.juez.ver": "查看评审提示词",
  "traza.exportar": "导出追踪为 JSON",
  "traza.usuario": " · 用户 {id}",
  "traza.coste.faltan": "成本（缺少 {n} 个无价格步骤）",
  "traza.coste.sin_verificar": "成本（价格未核实）",
  "traza.coste": "成本",
  "traza.tokens": "输入 / 输出 token",
  "traza.duracion": "耗时",
  "traza.pasos": "步骤",
  "traza.llamadas": "模型调用",
  "traza.herramientas": "工具",
  "traza.modelos": "模型",
  "traza.cache_tokens": "由缓存提供的 token",
  "traza.cache_ahorro": "缓存为你节省的金额",
  "traza.asumida": "按假定价格计费的步骤",
  "traza.errores": "错误",
  "arbol.titulo": "执行树",
  "arbol.n_de": "{total} 个步骤中的 {n} 个",
  "arbol.teclas": "↑↓ 移动 · ←→ 折叠",
  "arbol.plegar_todo": "全部折叠",
  "arbol.desplegar_todo": "全部展开",
  "arbol.desplegar": "展开",
  "arbol.plegar": "折叠",
  "arbol.misma_llamada": "相同输入的相同调用",
  "arbol.selecciona": "在树中选择一个步骤。",
  "arbol.prompt": "提示词（{n}）",
  "arbol.respuesta": "回答（{n}）",
  "arbol.argumentos": "参数",
  "arbol.salida": "输出",
  "arbol.consulta": "查询",
  "arbol.documentos": "文档（{n}）",
  "arbol.entrada": "输入",
  "arbol.eventos": "事件（{n}）",
  "arbol.evento": "事件",
  "arbol.modelo": "模型",
  "arbol.tok_entrada": "输入 token",
  "arbol.tok_entrada_est": "输入 token（估算）",
  "arbol.tok_salida": "输出 token",
  "arbol.tok_salida_est": "输出 token（估算）",
  "arbol.sin_precio": "价格未知",
  "arbol.coste_minimo": "最低成本（假定价格）",
  "arbol.desde_cache": "来自缓存（{coste}）",
  "arbol.escritos_cache": "写入缓存（{coste}）",
  "arbol.ahorro_cache": "缓存节省的金额",
  "arbol.rama.pasos": "分支步骤",
  "arbol.rama.error": "出错",
  "arbol.rama.tokens": "分支 token",
  "arbol.rama.coste": "分支成本",
  "arbol.mensaje": "消息",
  "arbol.contenido": "内容",
  "arbol.raiz": "（根）",
  "arbol.estimados": "true（由我们统计）",
  "arbol.del_proveedor": "false（来自提供商）",
  "arbol.ninguna": "无：未知模型",
  "arbol.atributos": "原始属性",
  "arbol.sin_contenido": "无内容。",
  "arbol.copiado": "已复制",
  "arbol.copiar": "复制",
  "arbol.misma_entrada": "相同调用，相同输入",
  "ver.buena": "将这次运行标记为正确",
  "ver.mala": "将这次运行标记为错误",
  "ver.solo_ver": "你的角色只能查看",
  "ver.bien": "正确",
  "ver.mal": "错误",
  "ver.ocultar": "隐藏评论",
  "ver.ver": "查看评论",
  "ver.comentar": "评论",
  "ver.placeholder": "哪里出错了，或者为什么是正确的。标记时保存。",
  "ver.nota": "评论会随判定一起保存：写完后请再次点击“{bien}”或“{mal}”。",
  "ver.juez": "评审",
  "ver.no_guardado": "未保存",
  "ver.maquina": "机器判定",
  "ver.juez_dice": "评审：{v}",
  "ver.bien_min": "正确",
  "ver.mal_min": "错误",
  "ver.coste_desconocido": " 成本未知",
  "ver.persona": "人工：{v}",
  "panel.titulo": "你的智能体“{proyecto}”，按每单位工作计",
  "panel.por_ejecucion": "每次运行",
  "panel.por_ejecucion.lead": "你的智能体每次运行的成本。这才是关键数字：因为工作量增加而上涨的花费不是问题，这里把两者区分开来。",
  "panel.totales": "总计（作为背景）",
  "panel.totales.lead": "它们特意放在下方：单看总数无法判断是否出了问题。",
  "panel.error.cargar": "无法加载",
  "panel.quien": "谁花得最多",
  "panel.agrupar": "分组依据",
  "panel.usuarios": "用户",
  "panel.sesiones": "会话",
  "panel.sin_usuario": "此范围内没有任何运行标明所属用户。在智能体中加入 {codigo}，这里就会显示花费都去了哪里。",
  "panel.sin_sesion": "此范围内没有任何运行标明所属会话。在智能体中加入 {codigo}，这里就会显示花费都去了哪里。",
  "panel.col.usuario": "用户",
  "panel.col.sesion": "会话",
  "panel.col.ejecuciones": "运行次数",
  "panel.col.por_ejecucion": "每次运行",
  "panel.col.total": "总计",
  "panel.col.del_gasto": "占花费",
  "panel.sin_etiqueta_usuario": "另外还有 {n} 次运行没有用户信息（{coste}）。",
  "panel.sin_etiqueta_sesion": "另外还有 {n} 次运行没有会话信息（{coste}）。",
  "panel.menos_de": "< {x}",
  "panel.sin_comparacion": "无对比",
  "panel.vs_anterior": "与上一时间段相比 {cambio}",
  "panel.grafica.titulo": "每次运行成本（每 {tramo} 一段）",
  "panel.grafica.coste": "每次运行成本",
  "panel.grafica.ejecuciones": "运行次数",
  "panel.grafica.aria": "各时间段每次运行成本",
  "panel.grafica.punto": "{fecha} · 每次运行 {coste} · {n} 次运行",
  "panel.grafica.desde": " · 从第一条数据开始",
  "panel.grafica.nota": "没有运行的时间段保持空白。这不代表成本为零：只是那段时间没有运行，画成零会显示一次并不存在的下降。",
  "panel.picos": "峰值",
  "panel.picos.ninguno": "此范围内没有异常的时间段。每次运行的成本保持在正常水平。",
  "panel.picos.n_one": "1 个时间段出现异常",
  "panel.picos.n_other": "{n} 个时间段出现异常",
  "panel.picos.lead": "每次运行成本远高于平常的时间段，按从贵到便宜排列。",
  "panel.pico.cuando": "开始于 {inicio}，持续到 {fin}",
  "panel.pico.de_mas": "多出",
  "panel.pico.texto_one": "在那段时间，每次运行花费 {coste}，而平常是 {base}：共 {n} 次运行，{veces}。",
  "panel.pico.texto_other": "在那段时间，每次运行花费 {coste}，而平常是 {base}：共 {n} 次运行，{veces}。",
  "panel.pico.veces": "高出 {n} 倍",
  "panel.pico.ver_prompt": "查看该提示词",
  "panel.pico.ver_trazas": "查看该时间段的追踪",
  "panel.pico.orden": "按成本从高到低排序",
  "panel.pico.tramo": "时间段",
  "panel.pico.base": "基线",
  "panel.pico.mediana": "有运行的时间段的中位数",
  "ev.titulo": "在部署之前测试“{proyecto}”的修复",
  "ev.lead": "这是流程的第二步：诊断告诉你一个修复能省回多少；这里用该步骤的真实调用确认，应用修复后智能体依然同样准确。",
  "ev.conj.titulo": "案例集",
  "ev.conj.lead": "智能体{reales}运行的集合。这里没有编造的案例：每个都来自真实发生过的追踪，可以打开查看来源。",
  "ev.conj.reales": "真实",
  "ev.conj.nombre": "名称",
  "ev.conj.cuantas": "追踪数量",
  "ev.conj.crear": "从最新的创建",
  "ev.conj.otro_filtro": "想用其他筛选条件？在{explorador}中筛选后点击“{guardar}”：案例集会保存生成它时的筛选条件，方便之后追溯来源。",
  "ev.explorador": "追踪浏览器",
  "ev.conj.ninguno": "目前还没有。",
  "ev.conj.col.conjunto": "案例集",
  "ev.conj.col.casos": "案例数",
  "ev.conj.col.filtro": "来源筛选",
  "ev.conj.col.creado": "创建时间",
  "ev.conj.sin_filtro": "无筛选（最新的）",
  "ev.borrar": "删除",
  "ev.tiradas": "评估运行",
  "ev.tiradas.lead": "每次运行都是用某个版本的智能体跑一遍案例集。由 SDK 在你的进程中启动；这里只接收报告和追踪。",
  "ev.col.version": "版本",
  "ev.col.conjunto": "案例集",
  "ev.col.casos": "案例数",
  "ev.col.personas": "人工",
  "ev.col.juez": "评审",
  "ev.col.coste": "成本",
  "ev.col.juzgar": "评审花费",
  "ev.col.cuando": "时间",
  "ev.sin_tiradas": "还没有新版本的评估运行？用 {codigo} 指向这个 Laplace 来启动。生成的追踪会像其他追踪一样出现在{explorador}中，项目为“{proyecto}”。",
  "ev.entre": "在 {bajo} 到 {alto} 之间",
  "ev.error.comparar": "无法比较",
  "ev.paso1": "保存一个案例集",
  "ev.paso1.texto": "智能体的真实运行。在{explorador}中筛选后点击“{guardar}”，或在下方用最新的运行创建。",
  "ev.paso2": "用当前版本运行",
  "ev.paso2.texto": "评估由 SDK 在你的进程中启动（Laplace 不会运行你的智能体）：",
  "ev.paso3": "再用新版本运行一次",
  "ev.paso3.texto": "换个提示词、换个模型：同一行代码换一个 {variant}。有了两次运行，这里就会出现准确率和成本的对比。准确率来自你的标注或自动评审。",
  "ev.comparar.titulo": "比较两个版本",
  "ev.comparar.pasos": "三个步骤，每完成一步都会自动勾选。",
  "ev.comparar.lead": "同时看准确率和成本。两次运行必须来自同一个案例集：在不同案例上比较准确率没有意义。",
  "ev.a": "A — 参照版本",
  "ev.b": "B — 新版本",
  "ev.elige": "选择一次运行",
  "ev.elige_a": "请先选择 A",
  "ev.n_casos": "{n} 个案例",
  "ev.comparando": "比较中…",
  "ev.comparar": "比较",
  "ev.discrepan": "人工和评审模型的结论不一致。",
  "ev.discrepan.texto": "这不是产品故障，而是这个页面能给你的最有价值的信息。要么评审模型衡量的是别的东西，要么标注者和编写评审提示词的人对“正确”的理解不同。在信任任何一方之前，先看看具体案例。",
  "ev.costo": "各自的成本",
  "ev.costo.lead": "这里没有误差范围：它不是样本，而是实际运行的账单。如果你在 Laplace 中管理提示词，每一侧下方会显示{enlace}，这是从追踪中读取的，而不是你给运行打的标签。",
  "ev.costo.enlace": "使用的版本",
  "ev.juzgar_dos": "用 {modelo} 评审两次运行",
  "ev.cuesta": "这会产生费用：完成后会告诉你花了多少",
  "ev.tec.conjunto": "案例集",
  "ev.tec.casos": "案例",
  "ev.fuente.personas": "人工",
  "ev.fuente.juez": "评审（模型）",
  "ev.de": "{b} 中的 {a}",
  "ev.sin_anotar": " · {n} 个未标注",
  "ev.wilson": "在 {bajo} 到 {alto} 之间（Wilson，95%）",
  "ev.por_caso": "每个案例",
  "ev.tec.total": "总计",
  "ev.tec.tokens": "token",
  "ev.tec.duracion": "耗时",
  "ev.tec.reventados": "崩溃",
  "ev.juez_costo": "评审这次运行另外花费了 {coste}{desconocido}。这是我们产生的花费，不是你的智能体的，所以单独列出。",
  "ev.juez_desconocido": "（还有一些判定的成本未知）",
  "pr.titulo": "“{proyecto}”的提示词",
  "pr.lead": "每个版本在实际流量上的成本和准确率，让你对照这两个数字决定哪个版本留在生产环境。",
  "pr.error.abrir": "无法打开",
  "pr.error.version": "无法切换版本",
  "pr.en_produccion": "v{n} 已在生产环境",
  "pr.cerrar": "关闭",
  "pr.ver_versiones": "查看版本与差异",
  "pr.reserva_one": "{n} 次运行使用了备用文本。",
  "pr.reserva_other": "{n} 次运行使用了备用文本。",
  "pr.reserva.texto": "这说明你的智能体无法从 Laplace 获取提示词，于是使用了代码中的版本。这部分流量单独统计，不计入生产版本：计入会扭曲你正在看的这个数字。",
  "pr.acierto.nota": "一个版本的准确率指的是它参与的{enteras}的准确率，而不是这个提示词单独的准确率。一次运行会经过多个步骤，出错时并没有人测量是哪一步导致的。这是一个有用的信号，而不是追责。",
  "pr.acierto.enteras": "完整运行",
  "pr.tec.versiones": "版本数",
  "pr.tec.creado": "创建时间",
  "pr.col.version": "版本",
  "pr.col.por_ejecucion": "每次运行",
  "pr.col.ejecuciones": "运行次数",
  "pr.col.tokens": "每次 token",
  "pr.col.ultimo": "最近使用",
  "pr.produccion": "生产",
  "pr.poner": "设为生产版本",
  "pr.ocultar_mudas": "隐藏没有流量的版本",
  "pr.ver_mudas_one": "查看 {n} 个在此范围内未运行的版本",
  "pr.ver_mudas_other": "查看 {n} 个在此范围内未运行的版本",
  "pr.wilson": "{bajo}–{alto}（Wilson）",
  "pr.nuevo": "把提示词从代码中移出",
  "pr.nuevo.lead": "名称就是你获取它时使用的名字：{codigo}。第一个版本会自动设为生产版本；从第二个版本起，保存和部署是两个独立的操作。",
  "pr.nombre": "名称",
  "pr.nuevo.placeholder": "你是一个用 {{idioma}} 回答、且不超过三句话的助手。",
  "pr.crear": "创建并设为生产版本",
  "pr.que_cambio": "改了什么",
  "pr.de": "从",
  "pr.a": "到",
  "pr.elige_dos": "选择两个不同的版本来查看差异。只有一个版本就没什么可比较的。",
  "pr.texto_v": "v{n} 的文本",
  "pr.guardar_nueva": "保存新版本",
  "pr.guardar_nueva.lead": "保存不会部署。这两个操作特意分开：这样你可以从容准备新版本，也才有“回退”按钮。",
  "pr.texto.placeholder": "提示词文本。每次调用会变化的内容请用 {{variable}}。",
  "pr.guardando": "保存中…",
  "pr.guardar": "保存版本",
  "pr.guardada": "已保存，未投入使用",
  "pr.historial": "部署历史",
  "pr.col.cuando": "时间",
  "pr.col.quien": "操作人",
  "pr.col.nota": "备注",
  "pr.vuelta_atras": "回退",
  "pr.historial.nota": "这份历史只记录经过，{no}用于归因峰值。归因时，{panel}使用的是该时间段追踪中出现的版本，这是实测事实，而不是时间上的巧合。",
  "pr.no": "不",
  "pr.panel": "面板",
  "pr.borrar": "删除此提示词",
  "pr.borrar.nota": "追踪不会被修改：它们仍会显示当时使用的版本",
  "pr.sin_adoptar": "你还没有在这里管理任何提示词",
  "pr.sin_adoptar.1": "你的提示词存放在代码里，这完全合理。但这样就无法回答“之前那个版本花了多少、准确率如何？”，因为 {blame} 只知道改了什么，不知道之后发生了什么。",
  "pr.sin_adoptar.2": "如果把它们移到这里，SDK 会提供提示词，并在每条追踪中记录使用的版本。{nada}：它只提供文本；如果 Laplace 没有响应，SDK 会使用保存的副本或你传入的备用文本。",
  "pr.sin_adoptar.nada": "Laplace 依然不会运行你的任何代码",
  "pr.sin_adoptar.3": "与此同时，下方是能从你的追踪中得知的信息：哪些步骤改了指令、何时改的。",
  "pr.obs.titulo": "追踪中能看到的",
  "pr.obs.nada": "暂时没有。",
  "pr.obs.gestion": "这些信息来自追踪，而不是提示词管理：它们是每个步骤运行时使用过的指令集合。可以用来发现在这里之外发生的改动。",
  "pr.obs.sin_gestion": "你的智能体的每个步骤，以及此范围内它运行时使用过的指令集合。如果某个步骤的指令在不同运行之间发生变化，那就是提示词改动：我们不知道完整文本（只保存开头），但知道何时改的、花了多少。",
  "pr.obs.cambio": "看到不认识的改动？{enlace}，查看这些运行的完整指令。",
  "pr.obs.abrir": "在追踪浏览器中打开",
  "pr.obs.no_versiones": "不是版本",
  "pr.obs.llamadas": "每次运行的调用",
  "pr.obs.juego_one": "组指令",
  "pr.obs.juego_other": "组指令",
  "pr.obs.col.instrucciones": "指令（开头）",
  "pr.obs.col.desde": "开始",
  "pr.obs.col.hasta": "结束",
  "pr.obs.sin_instrucciones": "（未采集到指令）",
  "comun.guardar": "保存",
  "comun.quitar": "移除",
  "aj.titulo": "“{proyecto}”的设置",
  "aj.lead": "预算、提醒、价格和数据。每个部分单独保存。",
  "aj.solo_lectura": "预算、提醒和删除项目由组织管理员修改。你的角色（{rol}）只能查看。",
  "aj.pres.guardado": "预算已保存。",
  "aj.pres.quitado": "预算已移除。",
  "aj.pres.titulo": "每月预算",
  "aj.pres.lead": "按自然月计算，与提供商的计费周期一致。达到 80% 和 100% 时会通过下方渠道各提醒一次，每月一次。",
  "aj.pres.dolares": "每月美元",
  "aj.error.borrar": "无法删除",
  "aj.datos": "数据",
  "aj.datos.retencion": "此安装会保留 {n} 天的追踪；更早的数据每天自动删除。",
  "aj.datos.siempre": "此安装会永久保留追踪。要自动删除旧数据，请使用 LAPLACE_RETENTION_DAYS 启动。",
  "aj.borrar.titulo": "彻底删除“{proyecto}”。",
  "aj.borrar.texto": "包括追踪、标注、案例集、提示词、预算和提醒。无法撤销。请输入项目名称以确认。",
  "aj.borrar.aria": "输入项目名称以确认",
  "aj.borrar.boton": "删除项目",
  "aj.apariencia": "外观",
  "aj.en_navegador": "保存在此浏览器中。",
  "aj.tema": "主题",
  "aj.tema.sistema": "跟随系统",
  "aj.tema.claro": "浅色",
  "aj.tema.oscuro": "深色",
  "aj.euros": "同时显示欧元",
  "aj.euros.lead": "提供商以美元计费，主数字仍然是美元。如果你填写汇率，主要金额旁会显示带“≈”的欧元等值。汇率由你设置，只保存在此浏览器中：我们不会从任何地方下载它。",
  "aj.euros.tipo": "1 美元等于 … 欧元",
  "aj.euros.guardado": "汇率已保存。",
  "aj.euros.desactivados": "已关闭欧元显示。",
  "aj.tar.guardada": "已保存 {modelo} 的价格。已存储的 {n} 次调用现已计算成本。",
  "aj.tar.quitada": "已移除 {modelo} 的价格。",
  "aj.error.quitar": "无法移除",
  "aj.tar.titulo": "自定义价格",
  "aj.tar.lead": "用于不在我们价格表中的模型，或有协议价格的模型。单位是每百万 token 的美元，取自提供商页面。保存后会重新计算你已发送的数据。如果模型运行在你自己的机器上，就不要设价格：没人向你收费。",
  "aj.tar.instalacion": "价格对整个安装生效：只有安装密钥才能修改。",
  "aj.tar.sin_tarifa": "目前没有价格：",
  "aj.tar.modelo": "模型",
  "aj.tar.entrada": "输入",
  "aj.tar.salida": "输出",
  "aj.tar.entrada_m": "输入（$/M）",
  "aj.tar.salida_m": "输出（$/M）",
  "aj.tar.guardar": "保存价格",
  "aj.al.prueba_ok": "测试消息已发送。请到对应渠道查看。",
  "aj.al.prueba_mal": "没有从任何渠道送达。请检查地址。",
  "aj.al.error.probar": "无法测试",
  "aj.al.titulo": "提醒",
  "aj.al.lead": "当某个问题已花费的金额超过阈值时发送消息。静默期内不会重复同一提醒，标记为已修复或忽略的问题不会提醒。",
  "aj.al.silenciadas": "此项目的提醒已静音。",
  "aj.al.activas": "已开启。",
  "aj.al.apagadas": "已关闭：请至少设置一个渠道。",
  "aj.al.slack_guardado": "Slack webhook 已保存。",
  "aj.al.slack_quitado": "Slack 已移除。",
  "aj.al.webhook_titulo": "Webhook（Teams、Discord、n8n…）",
  "aj.al.webhook_guardado": "Webhook 已保存。",
  "aj.al.webhook_quitado": "Webhook 已移除。",
  "aj.al.correo": "邮件",
  "aj.al.correo_placeholder": "team@company.com",
  "aj.al.correo_guardado": "邮箱已保存。",
  "aj.al.correo_quitado": "邮箱已移除。",
  "aj.al.smtp": "缺少安装的邮件服务器：请使用 LAPLACE_SMTP_HOST、LAPLACE_SMTP_USER 和 LAPLACE_SMTP_PASSWORD 启动 Laplace。",
  "aj.al.umbral": "阈值（已花费美元）",
  "aj.al.calma": "每个问题的静默期（小时）",
  "aj.al.umbral_guardado": "阈值和静默期已保存。",
  "aj.al.que_avisa": "提醒内容",
  "aj.al.reglas_guardadas": "规则已保存。",
  "aj.al.probar": "发送测试消息",
  "aj.al.reactivadas": "提醒已重新开启。",
  "aj.al.silenciadas_ok": "提醒已静音。",
  "aj.al.reactivar": "重新开启",
  "aj.al.silenciar": "将此项目静音",
  "aj.al.puesto": " · 已设置（{actual}）",
  "aj.al.otro": "粘贴另一个以替换",
  "aj.regla.repeticion": "重复",
  "aj.regla.bucle": "循环",
  "aj.regla.modelo_caro": "昂贵模型",
  "aj.regla.contexto_fijo": "未缓存的上下文",
  "titulo.ajustes": "设置",
  "titulo.configurar": "初始化",
  "titulo.entrar": "登录",
  "titulo.evaluaciones": "测试",
  "titulo.invitacion": "邀请",
  "titulo.organizacion": "组织",
  "titulo.panel": "面板",
  "titulo.problema": "问题",
  "titulo.prompts": "提示词",
  "titulo.traza": "追踪",
  "titulo.trazas": "追踪",
  "rol.lector": "查看者",
  "rol.miembro": "成员",
  "rol.admin": "管理员",
  "rol.propietario": "所有者",
  "org.error.cargar": "无法加载",
  "org.local.titulo": "本地模式没有账户",
  "org.local.texto": "这是运行在你机器上的进程，只有你的追踪：没有其他人需要访问。账户、角色和密钥只存在于云端安装中。",
  "org.tu_cuenta": "你的账户",
  "org.eres": "你是该组织的{rol}。",
  "org.sin_org": "你还不属于任何组织：请申请邀请。",
  "org.org": "组织",
  "org.miembros": "成员",
  "org.col.persona": "人员",
  "org.col.rol": "角色",
  "org.col.desde": "加入时间",
  "org.tu": " · 你",
  "org.rol_de": "{email} 的角色",
  "org.ahora_es": "{email} 现在是{rol}。",
  "org.salir_confirm": "确定退出该组织？",
  "org.quitar_confirm": "确定移除 {email}？",
  "org.hecho": "已完成。",
  "org.salir": "退出",
  "org.roles.nota": "查看者：只能查看。成员：还可以标注运行、标记问题、管理提示词和案例集。管理员：还可以管理成员、密钥、提醒、预算和删除。移除某人会立即结束其所有会话。",
  "org.invitar": "邀请",
  "org.email": "邮箱",
  "org.email_placeholder": "person@company.com",
  "org.enviado": "我们已通过邮件发送链接。你也可以复制它：",
  "org.sin_correo": "此安装没有配置邮件：请你自己把这个链接发给对方。它只显示这一次，7 天后过期。",
  "org.pendientes": "待接受",
  "org.caduca": "{fecha} 过期",
  "org.anulada": "邀请已撤销。",
  "org.anular": "撤销",
  "org.acc.configurar_instalacion": "初始化了安装",
  "org.acc.login": "登录了",
  "org.acc.login_fallido": "登录失败",
  "org.acc.invitar": "邀请了",
  "org.acc.anular_invitacion": "撤销了邀请：",
  "org.acc.aceptar_invitacion": "接受了邀请，角色为",
  "org.acc.cambiar_rol": "修改了角色：",
  "org.acc.quitar_miembro": "移除了",
  "org.acc.crear_clave": "创建了密钥：",
  "org.acc.revocar_clave": "吊销了密钥",
  "org.acc.borrar_proyecto": "删除了项目",
  "org.registro": "活动日志",
  "org.cargando": "加载中…",
  "org.nada": "暂时没有。",
  "org.alguien": "某人",
  "org.admin_instalacion": " · 你是此安装的管理员",
  "org.pass_actual": "当前密码",
  "org.pass_nueva": "新密码（至少 10 个字符）",
  "org.pass_cambiada": "密码已修改。其他会话已退出。",
  "org.pass_cambiar": "修改密码",
  "org.cerrar_todo": "在所有设备上退出",
  "org.error.generico": "操作失败",
  "cla.titulo": "API 密钥",
  "cla.lead": "每个项目一个密钥：你的智能体用它发送追踪。输入新的项目名称即可创建项目。",
  "cla.proyecto": "项目",
  "cla.para_que": "用途",
  "cla.para_que_placeholder": "生产环境接入",
  "cla.caduca": "过期",
  "cla.nunca": "永不",
  "cla.30": "30 天后",
  "cla.90": "90 天后",
  "cla.365": "一年后",
  "cla.crear": "创建密钥",
  "cla.copiala": "现在就复制：",
  "cla.copiala.texto": "我们只保存它的指纹，之后无法再次查看。如果丢失，请吊销并重新创建。",
  "cla.col.nombre": "名称",
  "cla.col.ultimo": "最近使用",
  "cla.no_caduca": "永不过期",
  "cla.revocar_confirm": "吊销“{nombre}”？它将立即失效。",
  "cla.revocada": "密钥已吊销。",
  "cla.revocar": "吊销",
  "cla.rotar": "轮换密钥：先创建新密钥，在智能体中替换，再吊销旧密钥。",
  "cla.copiado": "已复制",
  "cla.copiar": "复制",
  "ent.error": "无法登录",
  "ent.titulo": "登录 Laplace",
  "ent.contrasena": "密码",
  "ent.entrando": "登录中…",
  "ent.entrar": "登录",
  "ent.sin_cuenta": "没有账户？请向你所在组织的管理员申请邀请。",
  "ent.tengo_clave": "我有 API 密钥",
  "ent.comprobando": "验证中…",
  "ent.usar_clave": "使用密钥",
  "conf.error": "无法完成初始化",
  "conf.titulo": "初始化此安装",
  "conf.texto": "目前还没有任何账户。第一个账户将管理整个安装，并接管已有数据的项目。",
  "conf.codigo": "初始化代码",
  "conf.codigo.ayuda": "它在服务器日志中，位于“no hay ninguna cuenta todavía”那一行。使用 Docker 时：{comando}",
  "conf.org": "组织名称",
  "conf.org_placeholder": "我的公司",
  "conf.nombre": "你的名字",
  "conf.contrasena": "密码（至少 10 个字符）",
  "conf.creando": "创建中…",
  "conf.crear": "创建管理员账户",
  "inv.puede.lector": "查看其项目的数据",
  "inv.puede.miembro": "查看、标注运行、标记问题和管理提示词",
  "inv.puede.admin": "以上全部，外加成员、密钥、提醒和预算",
  "inv.puede.propietario": "全部权限，包括任免所有者",
  "inv.no_vale": "该邀请无效",
  "inv.error": "无法接受",
  "inv.no_vale.titulo": "此邀请无效",
  "inv.no_vale.texto": "{motivo}。邀请 7 天后过期，且只能使用一次：请让邀请你的人再发一次。",
  "inv.unete": "加入“{org}”",
  "inv.como": "作为{rol}：你将可以{puede}。",
  "inv.con_cuenta": "此邮箱已有账户：请输入密码",
  "inv.elige": "设置密码（至少 10 个字符）",
  "inv.uniendote": "加入中…",
  "inv.aceptar": "接受邀请",
  "nf.titulo": "此页面不存在",
  "nf.texto": "链接可能有误，或指向已不存在的内容。",
  "nf.ir": "前往诊断",
  "err.titulo": "加载此页面时出错",
  "err.texto": "我们无法准备数据。通常只是暂时的：请重试，如果仍然如此，请检查后端是否正常运行。",
  "prob.paso_titulo": "{titulo}。",
  // Errores de la API que no traen una frase propia.
  "api.fallo": "{ruta} 返回错误 {estado}",
  "api.no_valida": "请求无效：{campos}",
  // A1: un rango vacío no es un proyecto vacío.
  "estado.rango_vacio.titulo": "{ventana}没有运行",
  "estado.rango_vacio.ultima": "最近一次运行在 {fecha} 到达。",
  "estado.rango_vacio.fuera": "最近一次运行在 {fecha} 到达，早于此处可查看的 {rango}。请在启用 Laplace 的情况下运行你的智能体以查看新数据。",
  "estado.rango_vacio.boton": "查看{ventana}",
  // Menos texto (D-151): el héroe, el distintivo de confianza y la ficha.
  "diag.puedes.proy": "你最多可以少付",
  "diag.puedes.al_mes": "每月",
  "diag.puedes.gastado": "你本可以最多节省",
  "diag.puedes.en": "（{tiempo}内）",
  "diag.de_total.proy": "本月按{ventana}的节奏将花费 {total}。",
  "diag.de_total.gastado": "{tiempo}的数据中共花费 {total}。",
  "conf.alta": "可信度高",
  "conf.media": "可信度中等",
  "conf.baja": "可信度低",
  "conf.notas_one": "{n} 条说明",
  "conf.notas_other": "{n} 条说明",
  "conf.alta.texto": "所有花费都有已知费率，可避免部分也不过高。",
  "conf.media.texto": "该数字可信，但请结合这些说明阅读。",
  "conf.baja.texto": "部分花费缺失，或我们无法很好地看到这个智能体：不要把该数字当作最终结果。",
  "prob.por_que.plegado": "为什么会这样？",
  "prob.ahorro.como": "如何计算？",
  // Gráficos del Diagnóstico (D-152).
  "graf.titulo": "钱花在了哪里",
  "graf.dia": "每日花费",
  "graf.hora": "每小时花费",
  "graf.real": "实际工作",
  "graf.evitable": "可避免",
  "graf.punto": "{fecha}：{coste}，其中 {evitable} 可避免",
  "graf.aria": "按时间段的花费，上方为可避免部分",
  "graf.reparto": "可避免部分如何按天分摊？",
  "graf.reparto.texto": "可避免部分是在整个时间范围内计算的，而不是逐日计算。这里按每个问题所在步骤每天的花费比例分摊：各天之和等于上方的数字，该步骤未运行的日子不分摊。",
  "graf.sin_repartir": "{coste} 的可避免花费无法分摊：其步骤在此范围内没有带费率的花费。",
  "graf.pasos": "每个步骤的成本",
  "graf.otros": "其他步骤",
  "graf.paso.evitable": "{evitable} 可避免",
  // Textos que pinta el CSS (`content:`): el proveedor de idioma los pasa como variables.
  "css.porque": "为什么？",
  "css.avanzado": "高级",
  // El grafo del agente en la vista de traza (D-153).
  "grafo.titulo": "智能体的结构",
  "grafo.lead": "每个步骤一个方框，每当一个步骤调用另一个步骤就有一条箭头，并标出本次运行中调用的次数。",
  "grafo.aria": "包含 {pasos} 个步骤的智能体图",
  "grafo.llamadas_one": "{n} 次调用",
  "grafo.llamadas_other": "{n} 次调用",
  "grafo.errores_one": "{n} 次出错",
  "grafo.errores_other": "{n} 次出错",
  "grafo.tipo.agent": "智能体",
  "grafo.tipo.llm": "模型",
  "grafo.tipo.tool": "工具",
  "grafo.tipo.retrieval": "检索",
  "grafo.tipo.chain": "步骤",
  "grafo.tipo.otro": "其他",
  "grafo.sin_tarifa": "无费率",
  "grafo.al_menos": "≥ {coste}",
  "aj.regla.prompt_caro": "更贵的提示词",
  "diag.ahorrado_one": "自从你修复了一个问题，已经少付了 {coste}。",
  "diag.ahorrado_other": "自从你修复了 {n} 个问题，已经少付了 {coste}。",
  "diag.ahorrado.suelo": "至少 {coste}",
  "ciclo.titulo": "这个问题进行到哪一步",
  "ciclo.detectar": "发现",
  "ciclo.probar": "测试",
  "ciclo.arreglar": "修复",
  "ciclo.verificar": "验证",
  "ciclo.estado.hecho": "已完成",
  "ciclo.estado.en_curso": "进行中",
  "ciclo.estado.pendiente": "待处理",
  "ciclo.estado.fallo": "没有生效",
  "ciclo.detectar.hecho": "我们在你的追踪中发现了它。",
  "ciclo.probar.pendiente": "在改动之前，先用它的真实调用测试修复。",
  "ciclo.probar.conjunto": "它的运行已保存在“{nombre}”中；还没有运行测试。",
  "ciclo.probar.hecho_one": "在“{nombre}”上有 {n} 次评估运行。",
  "ciclo.probar.hecho_other": "在“{nombre}”上有 {n} 次评估运行。",
  "ciclo.probar.sin_paso": "这个问题不属于单个步骤：请在整个智能体上测试。",
  "ciclo.arreglar.pendiente": "应用修复后在这里标记。",
  "ciclo.arreglar.hecho": "已于 {fecha} 标记为已修复。",
  "ciclo.verificar.pendiente": "修复之后有了运行，我们会自动检查。",
  "ciclo.ignorado": "你忽略了它：流程到此为止。",
  "seg.probar.texto.prompt": "成本差异是实测的；但 v{a} 是否和 v{b} 一样准确还不知道。把这个步骤的真实运行保存为案例集，分别用两个版本运行：“测试”会告诉你哪个更准确、各自花费多少。",
  "seg.probar.texto.otro": "节省是实测的；但修复后的智能体能否答得一样好还不知道。把这个步骤的真实运行保存为案例集，在应用修复后运行：“测试”会告诉你它是否同样准确、便宜多少。",
  "seg.probar.existe": "已保存：“{nombre}”，{n} 个案例。",
  "seg.probar.arreglado": "已修复",
  "prob.prompt.titulo": "在提示词页面回到 v{a}",
  "prob.prompt.texto": "“{prompt}”的卡片会显示两个版本各自的成本和准确率，点一下就能把 v{a} 设为生产版本。",
  "prob.prompt.ir": "在提示词页面打开“{prompt}” →",
  "pr.hallazgo": "它出现在诊断中：{titulo}。",
  "pr.hallazgo.ver": "查看问题 →",
  "ev.por_probar.titulo": "待测试的修复",
  "ev.por_probar.lead": "诊断中未解决的问题，附上能省回多少，以及是否已有测试。保存它们的运行会用该步骤的真实调用创建案例集。",
  "ev.por_probar.sin_probar": "未测试",
  "ev.por_probar.guardado": "已保存，未运行",
  "ev.por_probar.probado_one": "{n} 次运行",
  "ev.por_probar.probado_other": "{n} 次运行",
  "ev.por_probar.guardar": "保存它的运行",
  "ev.por_probar.guardado_como": "已保存为“{nombre}”。在应用修复后运行它：",
  "ev.por_probar.ver": "查看问题",
  "ev.por_probar.error": "无法保存",
  "aj.contraste.alto": "高对比度",
  "aj.contraste.texto": "不透明背景，没有透明和模糊效果，文字达到最高对比度。浅色和深色主题都适用。",
  "arbol.envoltorio": "与内部的“{hijo}”相同：这个步骤只是包裹它。",
  "nav.clientes": "客户",
  "titulo.clientes": "客户",
  "cl.titulo": "“{proyecto}”各客户的利润",
  "cl.lead": "每个客户每月付给你的钱，对比其工作让你花的成本。成本来自其运行；付款金额由你填写。",
  "cl.aviso_one": "这个客户让你亏钱",
  "cl.aviso_other": "这 {n} 个客户让你亏钱",
  "cl.aviso.texto": "他们的工作花费超过了他们付的钱。看看他们的运行中出现了哪些诊断问题，或者重新审视价格。",
  "cl.h.cliente": "客户",
  "cl.h.ejecuciones": "运行次数",
  "cl.h.coste": "每月成本",
  "cl.h.ingresos": "每月付款（$）",
  "cl.h.margen": "每月利润",
  "cl.estado.pierde": "亏损",
  "cl.estado.ajustado": "利润微薄",
  "cl.estado.gana": "有利润",
  "cl.estado.sin-ingresos": "无收入",
  "cl.estado.sin-proyeccion": "数据不足",
  "cl.estado.sin-trafico": "无运行",
  "cl.ingresos.aria": "{cliente} 每月付款（美元）",
  "cl.guardar": "保存",
  "cl.error.guardar": "无法保存",
  "cl.sin_cliente": "{n} 次运行共 {coste} 没有标明属于哪个客户：单独计算，不分摊。",
  "cl.como.titulo": "如何标明每次运行属于哪个客户",
  "cl.como.texto": "在智能体为该客户工作之前加一行。评估运行不计入：它们不是任何客户的工作。",
  "cl.anadir": "为还没有运行的客户填写付款",
  "cl.anadir.id": "客户",
  "cl.anadir.importe": "每月付款（$）",
  "diag.clientes": "客户",
  "diag.clientes.pierden_one": "{n} 个客户让你亏钱。",
  "diag.clientes.pierden_other": "{n} 个客户让你亏钱。",
  "diag.clientes.ver": "查看各客户利润",
  "trazas.filtro.cliente": "只看客户 {cliente} 的运行",
  "cl.problemas": "在其运行中出现：",
  "cl.ver_ejecuciones": "查看其运行 →",
  "aj.regla.cliente_pierde": "让你亏钱的客户",
  "cl.stripe.titulo": "来自 Stripe 的收入",
  "cl.stripe.lead": "无需手动填写：每个客户的付款来自其上个月已支付的发票，并折算为每月金额（年度方案按十二分之一计算）。每个 Stripe 客户通过 metadata.laplace_customer_id 或其 id 与追踪中的客户对应。只需一个可读取发票和客户的受限密钥。",
  "cl.stripe.clave": "Stripe 密钥",
  "cl.stripe.puesta": "已设置密钥（{pista}）。",
  "cl.stripe.ultima": "上次：{fecha}，{n} 个客户。",
  "cl.stripe.nunca": "还没有获取任何数据。",
  "cl.stripe.traer": "从 Stripe 获取",
  "cl.stripe.quitar": "移除密钥",
  "cl.stripe.fuente": "Stripe",
};
